// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("twilio");

/**
 * Your SubAccount SID can be found on the Twilio dashboard at www.twilio.com/console.
 */
export declare const accountSid: string | undefined;
Object.defineProperty(exports, "accountSid", {
    get() {
        return __config.get("accountSid") ?? utilities.getEnv("TWILIO_SUBACCOUNT_SID", "TWILIO_ACCOUNT_SID");
    },
    enumerable: true,
});

/**
 * https://www.twilio.com/docs/global-infrastructure/edge-locations#public-edge-locations
 */
export declare const edge: string | undefined;
Object.defineProperty(exports, "edge", {
    get() {
        return __config.get("edge") ?? utilities.getEnv("TWILIO_EDGE");
    },
    enumerable: true,
});

/**
 * Your Auth Token/ API Secret can be found on the Twilio dashboard at www.twilio.com/console.
 */
export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password") ?? utilities.getEnv("TWILIO_API_SECRET", "TWILIO_AUTH_TOKEN");
    },
    enumerable: true,
});

/**
 * https://www.twilio.com/docs/global-infrastructure/edge-locations/legacy-regions
 */
export declare const region: string | undefined;
Object.defineProperty(exports, "region", {
    get() {
        return __config.get("region") ?? utilities.getEnv("TWILIO_REGION");
    },
    enumerable: true,
});

/**
 * Your Account SID/ API Key can be found on the Twilio dashboard at www.twilio.com/console.
 */
export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username") ?? utilities.getEnv("TWILIO_API_KEY", "TWILIO_ACCOUNT_SID");
    },
    enumerable: true,
});

