// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AccountsCredentialsAwsV1 extends pulumi.CustomResource {
    /**
     * Get an existing AccountsCredentialsAwsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AccountsCredentialsAwsV1State, opts?: pulumi.CustomResourceOptions): AccountsCredentialsAwsV1 {
        return new AccountsCredentialsAwsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/accountsCredentialsAwsV1:AccountsCredentialsAwsV1';

    /**
     * Returns true if the given object is an instance of AccountsCredentialsAwsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AccountsCredentialsAwsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AccountsCredentialsAwsV1.__pulumiType;
    }

    declare public readonly accountSid: pulumi.Output<string>;
    declare public readonly credentials: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a AccountsCredentialsAwsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AccountsCredentialsAwsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AccountsCredentialsAwsV1Args | AccountsCredentialsAwsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AccountsCredentialsAwsV1State | undefined;
            resourceInputs["accountSid"] = state?.accountSid;
            resourceInputs["credentials"] = state?.credentials;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as AccountsCredentialsAwsV1Args | undefined;
            if (args?.credentials === undefined && !opts.urn) {
                throw new Error("Missing required property 'credentials'");
            }
            resourceInputs["accountSid"] = args?.accountSid;
            resourceInputs["credentials"] = args?.credentials;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AccountsCredentialsAwsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AccountsCredentialsAwsV1 resources.
 */
export interface AccountsCredentialsAwsV1State {
    accountSid?: pulumi.Input<string | undefined>;
    credentials?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a AccountsCredentialsAwsV1 resource.
 */
export interface AccountsCredentialsAwsV1Args {
    accountSid?: pulumi.Input<string | undefined>;
    credentials: pulumi.Input<string>;
    friendlyName?: pulumi.Input<string | undefined>;
}
