// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AccountsCredentialsPublicKeysV1 extends pulumi.CustomResource {
    /**
     * Get an existing AccountsCredentialsPublicKeysV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AccountsCredentialsPublicKeysV1State, opts?: pulumi.CustomResourceOptions): AccountsCredentialsPublicKeysV1 {
        return new AccountsCredentialsPublicKeysV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/accountsCredentialsPublicKeysV1:AccountsCredentialsPublicKeysV1';

    /**
     * Returns true if the given object is an instance of AccountsCredentialsPublicKeysV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AccountsCredentialsPublicKeysV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AccountsCredentialsPublicKeysV1.__pulumiType;
    }

    declare public readonly accountSid: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly publicKey: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a AccountsCredentialsPublicKeysV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AccountsCredentialsPublicKeysV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AccountsCredentialsPublicKeysV1Args | AccountsCredentialsPublicKeysV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AccountsCredentialsPublicKeysV1State | undefined;
            resourceInputs["accountSid"] = state?.accountSid;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["publicKey"] = state?.publicKey;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as AccountsCredentialsPublicKeysV1Args | undefined;
            if (args?.publicKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'publicKey'");
            }
            resourceInputs["accountSid"] = args?.accountSid;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["publicKey"] = args?.publicKey;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AccountsCredentialsPublicKeysV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AccountsCredentialsPublicKeysV1 resources.
 */
export interface AccountsCredentialsPublicKeysV1State {
    accountSid?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    publicKey?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a AccountsCredentialsPublicKeysV1 resource.
 */
export interface AccountsCredentialsPublicKeysV1Args {
    accountSid?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    publicKey: pulumi.Input<string>;
}
