// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ApiAccountsApplications extends pulumi.CustomResource {
    /**
     * Get an existing ApiAccountsApplications resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApiAccountsApplicationsState, opts?: pulumi.CustomResourceOptions): ApiAccountsApplications {
        return new ApiAccountsApplications(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/apiAccountsApplications:ApiAccountsApplications';

    /**
     * Returns true if the given object is an instance of ApiAccountsApplications.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApiAccountsApplications {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApiAccountsApplications.__pulumiType;
    }

    declare public readonly apiVersion: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly messageStatusCallback: pulumi.Output<string>;
    declare public readonly pathAccountSid: pulumi.Output<string>;
    declare public readonly publicApplicationConnectEnabled: pulumi.Output<boolean>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly smsFallbackMethod: pulumi.Output<string>;
    declare public readonly smsFallbackUrl: pulumi.Output<string>;
    declare public readonly smsMethod: pulumi.Output<string>;
    declare public readonly smsStatusCallback: pulumi.Output<string>;
    declare public readonly smsUrl: pulumi.Output<string>;
    declare public readonly statusCallback: pulumi.Output<string>;
    declare public readonly statusCallbackMethod: pulumi.Output<string>;
    declare public readonly voiceCallerIdLookup: pulumi.Output<boolean>;
    declare public readonly voiceFallbackMethod: pulumi.Output<string>;
    declare public readonly voiceFallbackUrl: pulumi.Output<string>;
    declare public readonly voiceMethod: pulumi.Output<string>;
    declare public readonly voiceUrl: pulumi.Output<string>;

    /**
     * Create a ApiAccountsApplications resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ApiAccountsApplicationsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApiAccountsApplicationsArgs | ApiAccountsApplicationsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApiAccountsApplicationsState | undefined;
            resourceInputs["apiVersion"] = state?.apiVersion;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["messageStatusCallback"] = state?.messageStatusCallback;
            resourceInputs["pathAccountSid"] = state?.pathAccountSid;
            resourceInputs["publicApplicationConnectEnabled"] = state?.publicApplicationConnectEnabled;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["smsFallbackMethod"] = state?.smsFallbackMethod;
            resourceInputs["smsFallbackUrl"] = state?.smsFallbackUrl;
            resourceInputs["smsMethod"] = state?.smsMethod;
            resourceInputs["smsStatusCallback"] = state?.smsStatusCallback;
            resourceInputs["smsUrl"] = state?.smsUrl;
            resourceInputs["statusCallback"] = state?.statusCallback;
            resourceInputs["statusCallbackMethod"] = state?.statusCallbackMethod;
            resourceInputs["voiceCallerIdLookup"] = state?.voiceCallerIdLookup;
            resourceInputs["voiceFallbackMethod"] = state?.voiceFallbackMethod;
            resourceInputs["voiceFallbackUrl"] = state?.voiceFallbackUrl;
            resourceInputs["voiceMethod"] = state?.voiceMethod;
            resourceInputs["voiceUrl"] = state?.voiceUrl;
        } else {
            const args = argsOrState as ApiAccountsApplicationsArgs | undefined;
            resourceInputs["apiVersion"] = args?.apiVersion;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["messageStatusCallback"] = args?.messageStatusCallback;
            resourceInputs["pathAccountSid"] = args?.pathAccountSid;
            resourceInputs["publicApplicationConnectEnabled"] = args?.publicApplicationConnectEnabled;
            resourceInputs["smsFallbackMethod"] = args?.smsFallbackMethod;
            resourceInputs["smsFallbackUrl"] = args?.smsFallbackUrl;
            resourceInputs["smsMethod"] = args?.smsMethod;
            resourceInputs["smsStatusCallback"] = args?.smsStatusCallback;
            resourceInputs["smsUrl"] = args?.smsUrl;
            resourceInputs["statusCallback"] = args?.statusCallback;
            resourceInputs["statusCallbackMethod"] = args?.statusCallbackMethod;
            resourceInputs["voiceCallerIdLookup"] = args?.voiceCallerIdLookup;
            resourceInputs["voiceFallbackMethod"] = args?.voiceFallbackMethod;
            resourceInputs["voiceFallbackUrl"] = args?.voiceFallbackUrl;
            resourceInputs["voiceMethod"] = args?.voiceMethod;
            resourceInputs["voiceUrl"] = args?.voiceUrl;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ApiAccountsApplications.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ApiAccountsApplications resources.
 */
export interface ApiAccountsApplicationsState {
    apiVersion?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    messageStatusCallback?: pulumi.Input<string | undefined>;
    pathAccountSid?: pulumi.Input<string | undefined>;
    publicApplicationConnectEnabled?: pulumi.Input<boolean | undefined>;
    sid?: pulumi.Input<string | undefined>;
    smsFallbackMethod?: pulumi.Input<string | undefined>;
    smsFallbackUrl?: pulumi.Input<string | undefined>;
    smsMethod?: pulumi.Input<string | undefined>;
    smsStatusCallback?: pulumi.Input<string | undefined>;
    smsUrl?: pulumi.Input<string | undefined>;
    statusCallback?: pulumi.Input<string | undefined>;
    statusCallbackMethod?: pulumi.Input<string | undefined>;
    voiceCallerIdLookup?: pulumi.Input<boolean | undefined>;
    voiceFallbackMethod?: pulumi.Input<string | undefined>;
    voiceFallbackUrl?: pulumi.Input<string | undefined>;
    voiceMethod?: pulumi.Input<string | undefined>;
    voiceUrl?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ApiAccountsApplications resource.
 */
export interface ApiAccountsApplicationsArgs {
    apiVersion?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    messageStatusCallback?: pulumi.Input<string | undefined>;
    pathAccountSid?: pulumi.Input<string | undefined>;
    publicApplicationConnectEnabled?: pulumi.Input<boolean | undefined>;
    smsFallbackMethod?: pulumi.Input<string | undefined>;
    smsFallbackUrl?: pulumi.Input<string | undefined>;
    smsMethod?: pulumi.Input<string | undefined>;
    smsStatusCallback?: pulumi.Input<string | undefined>;
    smsUrl?: pulumi.Input<string | undefined>;
    statusCallback?: pulumi.Input<string | undefined>;
    statusCallbackMethod?: pulumi.Input<string | undefined>;
    voiceCallerIdLookup?: pulumi.Input<boolean | undefined>;
    voiceFallbackMethod?: pulumi.Input<string | undefined>;
    voiceFallbackUrl?: pulumi.Input<string | undefined>;
    voiceMethod?: pulumi.Input<string | undefined>;
    voiceUrl?: pulumi.Input<string | undefined>;
}
