// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ApiAccountsCalls extends pulumi.CustomResource {
    /**
     * Get an existing ApiAccountsCalls resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApiAccountsCallsState, opts?: pulumi.CustomResourceOptions): ApiAccountsCalls {
        return new ApiAccountsCalls(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/apiAccountsCalls:ApiAccountsCalls';

    /**
     * Returns true if the given object is an instance of ApiAccountsCalls.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApiAccountsCalls {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApiAccountsCalls.__pulumiType;
    }

    declare public readonly applicationSid: pulumi.Output<string>;
    declare public readonly asyncAmd: pulumi.Output<string>;
    declare public readonly asyncAmdStatusCallback: pulumi.Output<string>;
    declare public readonly asyncAmdStatusCallbackMethod: pulumi.Output<string>;
    declare public readonly byoc: pulumi.Output<string>;
    declare public readonly callReason: pulumi.Output<string>;
    declare public readonly callToken: pulumi.Output<string>;
    declare public readonly callerId: pulumi.Output<string>;
    declare public readonly fallbackMethod: pulumi.Output<string>;
    declare public readonly fallbackUrl: pulumi.Output<string>;
    declare public readonly from: pulumi.Output<string>;
    declare public readonly machineDetection: pulumi.Output<string>;
    declare public readonly machineDetectionSilenceTimeout: pulumi.Output<number>;
    declare public readonly machineDetectionSpeechEndThreshold: pulumi.Output<number>;
    declare public readonly machineDetectionSpeechThreshold: pulumi.Output<number>;
    declare public readonly machineDetectionTimeout: pulumi.Output<number>;
    declare public readonly method: pulumi.Output<string>;
    declare public readonly pathAccountSid: pulumi.Output<string>;
    declare public readonly record: pulumi.Output<boolean>;
    declare public readonly recordingChannels: pulumi.Output<string>;
    declare public readonly recordingStatusCallback: pulumi.Output<string>;
    declare public readonly recordingStatusCallbackEvents: pulumi.Output<string[]>;
    declare public readonly recordingStatusCallbackMethod: pulumi.Output<string>;
    declare public readonly recordingTrack: pulumi.Output<string>;
    declare public readonly sendDigits: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly sipAuthPassword: pulumi.Output<string>;
    declare public readonly sipAuthUsername: pulumi.Output<string>;
    declare public readonly status: pulumi.Output<string>;
    declare public readonly statusCallback: pulumi.Output<string>;
    declare public readonly statusCallbackEvents: pulumi.Output<string[]>;
    declare public readonly statusCallbackMethod: pulumi.Output<string>;
    declare public readonly timeLimit: pulumi.Output<number>;
    declare public readonly timeout: pulumi.Output<number>;
    declare public readonly to: pulumi.Output<string>;
    declare public readonly trim: pulumi.Output<string>;
    declare public readonly twiml: pulumi.Output<string>;
    declare public readonly url: pulumi.Output<string>;

    /**
     * Create a ApiAccountsCalls resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApiAccountsCallsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApiAccountsCallsArgs | ApiAccountsCallsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApiAccountsCallsState | undefined;
            resourceInputs["applicationSid"] = state?.applicationSid;
            resourceInputs["asyncAmd"] = state?.asyncAmd;
            resourceInputs["asyncAmdStatusCallback"] = state?.asyncAmdStatusCallback;
            resourceInputs["asyncAmdStatusCallbackMethod"] = state?.asyncAmdStatusCallbackMethod;
            resourceInputs["byoc"] = state?.byoc;
            resourceInputs["callReason"] = state?.callReason;
            resourceInputs["callToken"] = state?.callToken;
            resourceInputs["callerId"] = state?.callerId;
            resourceInputs["fallbackMethod"] = state?.fallbackMethod;
            resourceInputs["fallbackUrl"] = state?.fallbackUrl;
            resourceInputs["from"] = state?.from;
            resourceInputs["machineDetection"] = state?.machineDetection;
            resourceInputs["machineDetectionSilenceTimeout"] = state?.machineDetectionSilenceTimeout;
            resourceInputs["machineDetectionSpeechEndThreshold"] = state?.machineDetectionSpeechEndThreshold;
            resourceInputs["machineDetectionSpeechThreshold"] = state?.machineDetectionSpeechThreshold;
            resourceInputs["machineDetectionTimeout"] = state?.machineDetectionTimeout;
            resourceInputs["method"] = state?.method;
            resourceInputs["pathAccountSid"] = state?.pathAccountSid;
            resourceInputs["record"] = state?.record;
            resourceInputs["recordingChannels"] = state?.recordingChannels;
            resourceInputs["recordingStatusCallback"] = state?.recordingStatusCallback;
            resourceInputs["recordingStatusCallbackEvents"] = state?.recordingStatusCallbackEvents;
            resourceInputs["recordingStatusCallbackMethod"] = state?.recordingStatusCallbackMethod;
            resourceInputs["recordingTrack"] = state?.recordingTrack;
            resourceInputs["sendDigits"] = state?.sendDigits;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["sipAuthPassword"] = state?.sipAuthPassword;
            resourceInputs["sipAuthUsername"] = state?.sipAuthUsername;
            resourceInputs["status"] = state?.status;
            resourceInputs["statusCallback"] = state?.statusCallback;
            resourceInputs["statusCallbackEvents"] = state?.statusCallbackEvents;
            resourceInputs["statusCallbackMethod"] = state?.statusCallbackMethod;
            resourceInputs["timeLimit"] = state?.timeLimit;
            resourceInputs["timeout"] = state?.timeout;
            resourceInputs["to"] = state?.to;
            resourceInputs["trim"] = state?.trim;
            resourceInputs["twiml"] = state?.twiml;
            resourceInputs["url"] = state?.url;
        } else {
            const args = argsOrState as ApiAccountsCallsArgs | undefined;
            if (args?.from === undefined && !opts.urn) {
                throw new Error("Missing required property 'from'");
            }
            if (args?.to === undefined && !opts.urn) {
                throw new Error("Missing required property 'to'");
            }
            resourceInputs["applicationSid"] = args?.applicationSid;
            resourceInputs["asyncAmd"] = args?.asyncAmd;
            resourceInputs["asyncAmdStatusCallback"] = args?.asyncAmdStatusCallback;
            resourceInputs["asyncAmdStatusCallbackMethod"] = args?.asyncAmdStatusCallbackMethod;
            resourceInputs["byoc"] = args?.byoc;
            resourceInputs["callReason"] = args?.callReason;
            resourceInputs["callToken"] = args?.callToken;
            resourceInputs["callerId"] = args?.callerId;
            resourceInputs["fallbackMethod"] = args?.fallbackMethod;
            resourceInputs["fallbackUrl"] = args?.fallbackUrl;
            resourceInputs["from"] = args?.from;
            resourceInputs["machineDetection"] = args?.machineDetection;
            resourceInputs["machineDetectionSilenceTimeout"] = args?.machineDetectionSilenceTimeout;
            resourceInputs["machineDetectionSpeechEndThreshold"] = args?.machineDetectionSpeechEndThreshold;
            resourceInputs["machineDetectionSpeechThreshold"] = args?.machineDetectionSpeechThreshold;
            resourceInputs["machineDetectionTimeout"] = args?.machineDetectionTimeout;
            resourceInputs["method"] = args?.method;
            resourceInputs["pathAccountSid"] = args?.pathAccountSid;
            resourceInputs["record"] = args?.record;
            resourceInputs["recordingChannels"] = args?.recordingChannels;
            resourceInputs["recordingStatusCallback"] = args?.recordingStatusCallback;
            resourceInputs["recordingStatusCallbackEvents"] = args?.recordingStatusCallbackEvents;
            resourceInputs["recordingStatusCallbackMethod"] = args?.recordingStatusCallbackMethod;
            resourceInputs["recordingTrack"] = args?.recordingTrack;
            resourceInputs["sendDigits"] = args?.sendDigits;
            resourceInputs["sipAuthPassword"] = args?.sipAuthPassword;
            resourceInputs["sipAuthUsername"] = args?.sipAuthUsername;
            resourceInputs["status"] = args?.status;
            resourceInputs["statusCallback"] = args?.statusCallback;
            resourceInputs["statusCallbackEvents"] = args?.statusCallbackEvents;
            resourceInputs["statusCallbackMethod"] = args?.statusCallbackMethod;
            resourceInputs["timeLimit"] = args?.timeLimit;
            resourceInputs["timeout"] = args?.timeout;
            resourceInputs["to"] = args?.to;
            resourceInputs["trim"] = args?.trim;
            resourceInputs["twiml"] = args?.twiml;
            resourceInputs["url"] = args?.url;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ApiAccountsCalls.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ApiAccountsCalls resources.
 */
export interface ApiAccountsCallsState {
    applicationSid?: pulumi.Input<string | undefined>;
    asyncAmd?: pulumi.Input<string | undefined>;
    asyncAmdStatusCallback?: pulumi.Input<string | undefined>;
    asyncAmdStatusCallbackMethod?: pulumi.Input<string | undefined>;
    byoc?: pulumi.Input<string | undefined>;
    callReason?: pulumi.Input<string | undefined>;
    callToken?: pulumi.Input<string | undefined>;
    callerId?: pulumi.Input<string | undefined>;
    fallbackMethod?: pulumi.Input<string | undefined>;
    fallbackUrl?: pulumi.Input<string | undefined>;
    from?: pulumi.Input<string | undefined>;
    machineDetection?: pulumi.Input<string | undefined>;
    machineDetectionSilenceTimeout?: pulumi.Input<number | undefined>;
    machineDetectionSpeechEndThreshold?: pulumi.Input<number | undefined>;
    machineDetectionSpeechThreshold?: pulumi.Input<number | undefined>;
    machineDetectionTimeout?: pulumi.Input<number | undefined>;
    method?: pulumi.Input<string | undefined>;
    pathAccountSid?: pulumi.Input<string | undefined>;
    record?: pulumi.Input<boolean | undefined>;
    recordingChannels?: pulumi.Input<string | undefined>;
    recordingStatusCallback?: pulumi.Input<string | undefined>;
    recordingStatusCallbackEvents?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    recordingStatusCallbackMethod?: pulumi.Input<string | undefined>;
    recordingTrack?: pulumi.Input<string | undefined>;
    sendDigits?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    sipAuthPassword?: pulumi.Input<string | undefined>;
    sipAuthUsername?: pulumi.Input<string | undefined>;
    status?: pulumi.Input<string | undefined>;
    statusCallback?: pulumi.Input<string | undefined>;
    statusCallbackEvents?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    statusCallbackMethod?: pulumi.Input<string | undefined>;
    timeLimit?: pulumi.Input<number | undefined>;
    timeout?: pulumi.Input<number | undefined>;
    to?: pulumi.Input<string | undefined>;
    trim?: pulumi.Input<string | undefined>;
    twiml?: pulumi.Input<string | undefined>;
    url?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ApiAccountsCalls resource.
 */
export interface ApiAccountsCallsArgs {
    applicationSid?: pulumi.Input<string | undefined>;
    asyncAmd?: pulumi.Input<string | undefined>;
    asyncAmdStatusCallback?: pulumi.Input<string | undefined>;
    asyncAmdStatusCallbackMethod?: pulumi.Input<string | undefined>;
    byoc?: pulumi.Input<string | undefined>;
    callReason?: pulumi.Input<string | undefined>;
    callToken?: pulumi.Input<string | undefined>;
    callerId?: pulumi.Input<string | undefined>;
    fallbackMethod?: pulumi.Input<string | undefined>;
    fallbackUrl?: pulumi.Input<string | undefined>;
    from: pulumi.Input<string>;
    machineDetection?: pulumi.Input<string | undefined>;
    machineDetectionSilenceTimeout?: pulumi.Input<number | undefined>;
    machineDetectionSpeechEndThreshold?: pulumi.Input<number | undefined>;
    machineDetectionSpeechThreshold?: pulumi.Input<number | undefined>;
    machineDetectionTimeout?: pulumi.Input<number | undefined>;
    method?: pulumi.Input<string | undefined>;
    pathAccountSid?: pulumi.Input<string | undefined>;
    record?: pulumi.Input<boolean | undefined>;
    recordingChannels?: pulumi.Input<string | undefined>;
    recordingStatusCallback?: pulumi.Input<string | undefined>;
    recordingStatusCallbackEvents?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    recordingStatusCallbackMethod?: pulumi.Input<string | undefined>;
    recordingTrack?: pulumi.Input<string | undefined>;
    sendDigits?: pulumi.Input<string | undefined>;
    sipAuthPassword?: pulumi.Input<string | undefined>;
    sipAuthUsername?: pulumi.Input<string | undefined>;
    status?: pulumi.Input<string | undefined>;
    statusCallback?: pulumi.Input<string | undefined>;
    statusCallbackEvents?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    statusCallbackMethod?: pulumi.Input<string | undefined>;
    timeLimit?: pulumi.Input<number | undefined>;
    timeout?: pulumi.Input<number | undefined>;
    to: pulumi.Input<string>;
    trim?: pulumi.Input<string | undefined>;
    twiml?: pulumi.Input<string | undefined>;
    url?: pulumi.Input<string | undefined>;
}
