// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ApiAccountsMessages extends pulumi.CustomResource {
    /**
     * Get an existing ApiAccountsMessages resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApiAccountsMessagesState, opts?: pulumi.CustomResourceOptions): ApiAccountsMessages {
        return new ApiAccountsMessages(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/apiAccountsMessages:ApiAccountsMessages';

    /**
     * Returns true if the given object is an instance of ApiAccountsMessages.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApiAccountsMessages {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApiAccountsMessages.__pulumiType;
    }

    declare public readonly addressRetention: pulumi.Output<string>;
    declare public readonly applicationSid: pulumi.Output<string>;
    declare public readonly attempt: pulumi.Output<number>;
    declare public readonly body: pulumi.Output<string>;
    declare public readonly contentRetention: pulumi.Output<string>;
    declare public readonly contentSid: pulumi.Output<string>;
    declare public readonly contentVariables: pulumi.Output<string>;
    declare public readonly forceDelivery: pulumi.Output<boolean>;
    declare public readonly from: pulumi.Output<string>;
    declare public readonly maxPrice: pulumi.Output<number>;
    declare public readonly mediaUrls: pulumi.Output<string[]>;
    declare public readonly messagingServiceSid: pulumi.Output<string>;
    declare public readonly pathAccountSid: pulumi.Output<string>;
    declare public readonly persistentActions: pulumi.Output<string[]>;
    declare public readonly provideFeedback: pulumi.Output<boolean>;
    declare public readonly riskCheck: pulumi.Output<string>;
    declare public readonly scheduleType: pulumi.Output<string>;
    declare public readonly sendAsMms: pulumi.Output<boolean>;
    declare public readonly sendAt: pulumi.Output<string>;
    declare public readonly shortenUrls: pulumi.Output<boolean>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly smartEncoded: pulumi.Output<boolean>;
    declare public readonly status: pulumi.Output<string>;
    declare public readonly statusCallback: pulumi.Output<string>;
    declare public readonly to: pulumi.Output<string>;
    declare public readonly validityPeriod: pulumi.Output<number>;

    /**
     * Create a ApiAccountsMessages resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApiAccountsMessagesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApiAccountsMessagesArgs | ApiAccountsMessagesState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApiAccountsMessagesState | undefined;
            resourceInputs["addressRetention"] = state?.addressRetention;
            resourceInputs["applicationSid"] = state?.applicationSid;
            resourceInputs["attempt"] = state?.attempt;
            resourceInputs["body"] = state?.body;
            resourceInputs["contentRetention"] = state?.contentRetention;
            resourceInputs["contentSid"] = state?.contentSid;
            resourceInputs["contentVariables"] = state?.contentVariables;
            resourceInputs["forceDelivery"] = state?.forceDelivery;
            resourceInputs["from"] = state?.from;
            resourceInputs["maxPrice"] = state?.maxPrice;
            resourceInputs["mediaUrls"] = state?.mediaUrls;
            resourceInputs["messagingServiceSid"] = state?.messagingServiceSid;
            resourceInputs["pathAccountSid"] = state?.pathAccountSid;
            resourceInputs["persistentActions"] = state?.persistentActions;
            resourceInputs["provideFeedback"] = state?.provideFeedback;
            resourceInputs["riskCheck"] = state?.riskCheck;
            resourceInputs["scheduleType"] = state?.scheduleType;
            resourceInputs["sendAsMms"] = state?.sendAsMms;
            resourceInputs["sendAt"] = state?.sendAt;
            resourceInputs["shortenUrls"] = state?.shortenUrls;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["smartEncoded"] = state?.smartEncoded;
            resourceInputs["status"] = state?.status;
            resourceInputs["statusCallback"] = state?.statusCallback;
            resourceInputs["to"] = state?.to;
            resourceInputs["validityPeriod"] = state?.validityPeriod;
        } else {
            const args = argsOrState as ApiAccountsMessagesArgs | undefined;
            if (args?.to === undefined && !opts.urn) {
                throw new Error("Missing required property 'to'");
            }
            resourceInputs["addressRetention"] = args?.addressRetention;
            resourceInputs["applicationSid"] = args?.applicationSid;
            resourceInputs["attempt"] = args?.attempt;
            resourceInputs["body"] = args?.body;
            resourceInputs["contentRetention"] = args?.contentRetention;
            resourceInputs["contentSid"] = args?.contentSid;
            resourceInputs["contentVariables"] = args?.contentVariables;
            resourceInputs["forceDelivery"] = args?.forceDelivery;
            resourceInputs["from"] = args?.from;
            resourceInputs["maxPrice"] = args?.maxPrice;
            resourceInputs["mediaUrls"] = args?.mediaUrls;
            resourceInputs["messagingServiceSid"] = args?.messagingServiceSid;
            resourceInputs["pathAccountSid"] = args?.pathAccountSid;
            resourceInputs["persistentActions"] = args?.persistentActions;
            resourceInputs["provideFeedback"] = args?.provideFeedback;
            resourceInputs["riskCheck"] = args?.riskCheck;
            resourceInputs["scheduleType"] = args?.scheduleType;
            resourceInputs["sendAsMms"] = args?.sendAsMms;
            resourceInputs["sendAt"] = args?.sendAt;
            resourceInputs["shortenUrls"] = args?.shortenUrls;
            resourceInputs["smartEncoded"] = args?.smartEncoded;
            resourceInputs["status"] = args?.status;
            resourceInputs["statusCallback"] = args?.statusCallback;
            resourceInputs["to"] = args?.to;
            resourceInputs["validityPeriod"] = args?.validityPeriod;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ApiAccountsMessages.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ApiAccountsMessages resources.
 */
export interface ApiAccountsMessagesState {
    addressRetention?: pulumi.Input<string | undefined>;
    applicationSid?: pulumi.Input<string | undefined>;
    attempt?: pulumi.Input<number | undefined>;
    body?: pulumi.Input<string | undefined>;
    contentRetention?: pulumi.Input<string | undefined>;
    contentSid?: pulumi.Input<string | undefined>;
    contentVariables?: pulumi.Input<string | undefined>;
    forceDelivery?: pulumi.Input<boolean | undefined>;
    from?: pulumi.Input<string | undefined>;
    maxPrice?: pulumi.Input<number | undefined>;
    mediaUrls?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    messagingServiceSid?: pulumi.Input<string | undefined>;
    pathAccountSid?: pulumi.Input<string | undefined>;
    persistentActions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    provideFeedback?: pulumi.Input<boolean | undefined>;
    riskCheck?: pulumi.Input<string | undefined>;
    scheduleType?: pulumi.Input<string | undefined>;
    sendAsMms?: pulumi.Input<boolean | undefined>;
    sendAt?: pulumi.Input<string | undefined>;
    shortenUrls?: pulumi.Input<boolean | undefined>;
    sid?: pulumi.Input<string | undefined>;
    smartEncoded?: pulumi.Input<boolean | undefined>;
    status?: pulumi.Input<string | undefined>;
    statusCallback?: pulumi.Input<string | undefined>;
    to?: pulumi.Input<string | undefined>;
    validityPeriod?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a ApiAccountsMessages resource.
 */
export interface ApiAccountsMessagesArgs {
    addressRetention?: pulumi.Input<string | undefined>;
    applicationSid?: pulumi.Input<string | undefined>;
    attempt?: pulumi.Input<number | undefined>;
    body?: pulumi.Input<string | undefined>;
    contentRetention?: pulumi.Input<string | undefined>;
    contentSid?: pulumi.Input<string | undefined>;
    contentVariables?: pulumi.Input<string | undefined>;
    forceDelivery?: pulumi.Input<boolean | undefined>;
    from?: pulumi.Input<string | undefined>;
    maxPrice?: pulumi.Input<number | undefined>;
    mediaUrls?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    messagingServiceSid?: pulumi.Input<string | undefined>;
    pathAccountSid?: pulumi.Input<string | undefined>;
    persistentActions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    provideFeedback?: pulumi.Input<boolean | undefined>;
    riskCheck?: pulumi.Input<string | undefined>;
    scheduleType?: pulumi.Input<string | undefined>;
    sendAsMms?: pulumi.Input<boolean | undefined>;
    sendAt?: pulumi.Input<string | undefined>;
    shortenUrls?: pulumi.Input<boolean | undefined>;
    smartEncoded?: pulumi.Input<boolean | undefined>;
    status?: pulumi.Input<string | undefined>;
    statusCallback?: pulumi.Input<string | undefined>;
    to: pulumi.Input<string>;
    validityPeriod?: pulumi.Input<number | undefined>;
}
