// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ApiAccountsQueues extends pulumi.CustomResource {
    /**
     * Get an existing ApiAccountsQueues resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApiAccountsQueuesState, opts?: pulumi.CustomResourceOptions): ApiAccountsQueues {
        return new ApiAccountsQueues(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/apiAccountsQueues:ApiAccountsQueues';

    /**
     * Returns true if the given object is an instance of ApiAccountsQueues.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApiAccountsQueues {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApiAccountsQueues.__pulumiType;
    }

    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly maxSize: pulumi.Output<number>;
    declare public readonly pathAccountSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a ApiAccountsQueues resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApiAccountsQueuesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApiAccountsQueuesArgs | ApiAccountsQueuesState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApiAccountsQueuesState | undefined;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["maxSize"] = state?.maxSize;
            resourceInputs["pathAccountSid"] = state?.pathAccountSid;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as ApiAccountsQueuesArgs | undefined;
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["maxSize"] = args?.maxSize;
            resourceInputs["pathAccountSid"] = args?.pathAccountSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ApiAccountsQueues.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ApiAccountsQueues resources.
 */
export interface ApiAccountsQueuesState {
    friendlyName?: pulumi.Input<string | undefined>;
    maxSize?: pulumi.Input<number | undefined>;
    pathAccountSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ApiAccountsQueues resource.
 */
export interface ApiAccountsQueuesArgs {
    friendlyName: pulumi.Input<string>;
    maxSize?: pulumi.Input<number | undefined>;
    pathAccountSid?: pulumi.Input<string | undefined>;
}
