// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ApiAccountsIncomingPhoneNumbers extends pulumi.CustomResource {
    /**
     * Get an existing ApiAccountsIncomingPhoneNumbers resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApiAccountsIncomingPhoneNumbersState, opts?: pulumi.CustomResourceOptions): ApiAccountsIncomingPhoneNumbers {
        return new ApiAccountsIncomingPhoneNumbers(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/apiAccountsIncomingPhoneNumbers:ApiAccountsIncomingPhoneNumbers';

    /**
     * Returns true if the given object is an instance of ApiAccountsIncomingPhoneNumbers.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApiAccountsIncomingPhoneNumbers {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApiAccountsIncomingPhoneNumbers.__pulumiType;
    }

    declare public readonly accountSid: pulumi.Output<string>;
    declare public readonly addressSid: pulumi.Output<string>;
    declare public readonly apiVersion: pulumi.Output<string>;
    declare public readonly areaCode: pulumi.Output<string>;
    declare public readonly bundleSid: pulumi.Output<string>;
    declare public readonly emergencyAddressSid: pulumi.Output<string>;
    declare public readonly emergencyStatus: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly identitySid: pulumi.Output<string>;
    declare public readonly pathAccountSid: pulumi.Output<string>;
    declare public readonly phoneNumber: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly smsApplicationSid: pulumi.Output<string>;
    declare public readonly smsFallbackMethod: pulumi.Output<string>;
    declare public readonly smsFallbackUrl: pulumi.Output<string>;
    declare public readonly smsMethod: pulumi.Output<string>;
    declare public readonly smsUrl: pulumi.Output<string>;
    declare public readonly statusCallback: pulumi.Output<string>;
    declare public readonly statusCallbackMethod: pulumi.Output<string>;
    declare public readonly trunkSid: pulumi.Output<string>;
    declare public readonly voiceApplicationSid: pulumi.Output<string>;
    declare public readonly voiceCallerIdLookup: pulumi.Output<boolean>;
    declare public readonly voiceFallbackMethod: pulumi.Output<string>;
    declare public readonly voiceFallbackUrl: pulumi.Output<string>;
    declare public readonly voiceMethod: pulumi.Output<string>;
    declare public readonly voiceReceiveMode: pulumi.Output<string>;
    declare public readonly voiceUrl: pulumi.Output<string>;

    /**
     * Create a ApiAccountsIncomingPhoneNumbers resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ApiAccountsIncomingPhoneNumbersArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApiAccountsIncomingPhoneNumbersArgs | ApiAccountsIncomingPhoneNumbersState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApiAccountsIncomingPhoneNumbersState | undefined;
            resourceInputs["accountSid"] = state?.accountSid;
            resourceInputs["addressSid"] = state?.addressSid;
            resourceInputs["apiVersion"] = state?.apiVersion;
            resourceInputs["areaCode"] = state?.areaCode;
            resourceInputs["bundleSid"] = state?.bundleSid;
            resourceInputs["emergencyAddressSid"] = state?.emergencyAddressSid;
            resourceInputs["emergencyStatus"] = state?.emergencyStatus;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["identitySid"] = state?.identitySid;
            resourceInputs["pathAccountSid"] = state?.pathAccountSid;
            resourceInputs["phoneNumber"] = state?.phoneNumber;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["smsApplicationSid"] = state?.smsApplicationSid;
            resourceInputs["smsFallbackMethod"] = state?.smsFallbackMethod;
            resourceInputs["smsFallbackUrl"] = state?.smsFallbackUrl;
            resourceInputs["smsMethod"] = state?.smsMethod;
            resourceInputs["smsUrl"] = state?.smsUrl;
            resourceInputs["statusCallback"] = state?.statusCallback;
            resourceInputs["statusCallbackMethod"] = state?.statusCallbackMethod;
            resourceInputs["trunkSid"] = state?.trunkSid;
            resourceInputs["voiceApplicationSid"] = state?.voiceApplicationSid;
            resourceInputs["voiceCallerIdLookup"] = state?.voiceCallerIdLookup;
            resourceInputs["voiceFallbackMethod"] = state?.voiceFallbackMethod;
            resourceInputs["voiceFallbackUrl"] = state?.voiceFallbackUrl;
            resourceInputs["voiceMethod"] = state?.voiceMethod;
            resourceInputs["voiceReceiveMode"] = state?.voiceReceiveMode;
            resourceInputs["voiceUrl"] = state?.voiceUrl;
        } else {
            const args = argsOrState as ApiAccountsIncomingPhoneNumbersArgs | undefined;
            resourceInputs["accountSid"] = args?.accountSid;
            resourceInputs["addressSid"] = args?.addressSid;
            resourceInputs["apiVersion"] = args?.apiVersion;
            resourceInputs["areaCode"] = args?.areaCode;
            resourceInputs["bundleSid"] = args?.bundleSid;
            resourceInputs["emergencyAddressSid"] = args?.emergencyAddressSid;
            resourceInputs["emergencyStatus"] = args?.emergencyStatus;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["identitySid"] = args?.identitySid;
            resourceInputs["pathAccountSid"] = args?.pathAccountSid;
            resourceInputs["phoneNumber"] = args?.phoneNumber;
            resourceInputs["smsApplicationSid"] = args?.smsApplicationSid;
            resourceInputs["smsFallbackMethod"] = args?.smsFallbackMethod;
            resourceInputs["smsFallbackUrl"] = args?.smsFallbackUrl;
            resourceInputs["smsMethod"] = args?.smsMethod;
            resourceInputs["smsUrl"] = args?.smsUrl;
            resourceInputs["statusCallback"] = args?.statusCallback;
            resourceInputs["statusCallbackMethod"] = args?.statusCallbackMethod;
            resourceInputs["trunkSid"] = args?.trunkSid;
            resourceInputs["voiceApplicationSid"] = args?.voiceApplicationSid;
            resourceInputs["voiceCallerIdLookup"] = args?.voiceCallerIdLookup;
            resourceInputs["voiceFallbackMethod"] = args?.voiceFallbackMethod;
            resourceInputs["voiceFallbackUrl"] = args?.voiceFallbackUrl;
            resourceInputs["voiceMethod"] = args?.voiceMethod;
            resourceInputs["voiceReceiveMode"] = args?.voiceReceiveMode;
            resourceInputs["voiceUrl"] = args?.voiceUrl;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ApiAccountsIncomingPhoneNumbers.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ApiAccountsIncomingPhoneNumbers resources.
 */
export interface ApiAccountsIncomingPhoneNumbersState {
    accountSid?: pulumi.Input<string | undefined>;
    addressSid?: pulumi.Input<string | undefined>;
    apiVersion?: pulumi.Input<string | undefined>;
    areaCode?: pulumi.Input<string | undefined>;
    bundleSid?: pulumi.Input<string | undefined>;
    emergencyAddressSid?: pulumi.Input<string | undefined>;
    emergencyStatus?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    identitySid?: pulumi.Input<string | undefined>;
    pathAccountSid?: pulumi.Input<string | undefined>;
    phoneNumber?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    smsApplicationSid?: pulumi.Input<string | undefined>;
    smsFallbackMethod?: pulumi.Input<string | undefined>;
    smsFallbackUrl?: pulumi.Input<string | undefined>;
    smsMethod?: pulumi.Input<string | undefined>;
    smsUrl?: pulumi.Input<string | undefined>;
    statusCallback?: pulumi.Input<string | undefined>;
    statusCallbackMethod?: pulumi.Input<string | undefined>;
    trunkSid?: pulumi.Input<string | undefined>;
    voiceApplicationSid?: pulumi.Input<string | undefined>;
    voiceCallerIdLookup?: pulumi.Input<boolean | undefined>;
    voiceFallbackMethod?: pulumi.Input<string | undefined>;
    voiceFallbackUrl?: pulumi.Input<string | undefined>;
    voiceMethod?: pulumi.Input<string | undefined>;
    voiceReceiveMode?: pulumi.Input<string | undefined>;
    voiceUrl?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ApiAccountsIncomingPhoneNumbers resource.
 */
export interface ApiAccountsIncomingPhoneNumbersArgs {
    accountSid?: pulumi.Input<string | undefined>;
    addressSid?: pulumi.Input<string | undefined>;
    apiVersion?: pulumi.Input<string | undefined>;
    areaCode?: pulumi.Input<string | undefined>;
    bundleSid?: pulumi.Input<string | undefined>;
    emergencyAddressSid?: pulumi.Input<string | undefined>;
    emergencyStatus?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    identitySid?: pulumi.Input<string | undefined>;
    pathAccountSid?: pulumi.Input<string | undefined>;
    phoneNumber?: pulumi.Input<string | undefined>;
    smsApplicationSid?: pulumi.Input<string | undefined>;
    smsFallbackMethod?: pulumi.Input<string | undefined>;
    smsFallbackUrl?: pulumi.Input<string | undefined>;
    smsMethod?: pulumi.Input<string | undefined>;
    smsUrl?: pulumi.Input<string | undefined>;
    statusCallback?: pulumi.Input<string | undefined>;
    statusCallbackMethod?: pulumi.Input<string | undefined>;
    trunkSid?: pulumi.Input<string | undefined>;
    voiceApplicationSid?: pulumi.Input<string | undefined>;
    voiceCallerIdLookup?: pulumi.Input<boolean | undefined>;
    voiceFallbackMethod?: pulumi.Input<string | undefined>;
    voiceFallbackUrl?: pulumi.Input<string | undefined>;
    voiceMethod?: pulumi.Input<string | undefined>;
    voiceReceiveMode?: pulumi.Input<string | undefined>;
    voiceUrl?: pulumi.Input<string | undefined>;
}
