// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ApiAccountsIncomingPhoneNumbersAssignedAddOns extends pulumi.CustomResource {
    /**
     * Get an existing ApiAccountsIncomingPhoneNumbersAssignedAddOns resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApiAccountsIncomingPhoneNumbersAssignedAddOnsState, opts?: pulumi.CustomResourceOptions): ApiAccountsIncomingPhoneNumbersAssignedAddOns {
        return new ApiAccountsIncomingPhoneNumbersAssignedAddOns(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/apiAccountsIncomingPhoneNumbersAssignedAddOns:ApiAccountsIncomingPhoneNumbersAssignedAddOns';

    /**
     * Returns true if the given object is an instance of ApiAccountsIncomingPhoneNumbersAssignedAddOns.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApiAccountsIncomingPhoneNumbersAssignedAddOns {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApiAccountsIncomingPhoneNumbersAssignedAddOns.__pulumiType;
    }

    declare public readonly installedAddOnSid: pulumi.Output<string>;
    declare public readonly pathAccountSid: pulumi.Output<string>;
    declare public readonly resourceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a ApiAccountsIncomingPhoneNumbersAssignedAddOns resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApiAccountsIncomingPhoneNumbersAssignedAddOnsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApiAccountsIncomingPhoneNumbersAssignedAddOnsArgs | ApiAccountsIncomingPhoneNumbersAssignedAddOnsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApiAccountsIncomingPhoneNumbersAssignedAddOnsState | undefined;
            resourceInputs["installedAddOnSid"] = state?.installedAddOnSid;
            resourceInputs["pathAccountSid"] = state?.pathAccountSid;
            resourceInputs["resourceSid"] = state?.resourceSid;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as ApiAccountsIncomingPhoneNumbersAssignedAddOnsArgs | undefined;
            if (args?.installedAddOnSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'installedAddOnSid'");
            }
            if (args?.resourceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceSid'");
            }
            resourceInputs["installedAddOnSid"] = args?.installedAddOnSid;
            resourceInputs["pathAccountSid"] = args?.pathAccountSid;
            resourceInputs["resourceSid"] = args?.resourceSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ApiAccountsIncomingPhoneNumbersAssignedAddOns.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ApiAccountsIncomingPhoneNumbersAssignedAddOns resources.
 */
export interface ApiAccountsIncomingPhoneNumbersAssignedAddOnsState {
    installedAddOnSid?: pulumi.Input<string | undefined>;
    pathAccountSid?: pulumi.Input<string | undefined>;
    resourceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ApiAccountsIncomingPhoneNumbersAssignedAddOns resource.
 */
export interface ApiAccountsIncomingPhoneNumbersAssignedAddOnsArgs {
    installedAddOnSid: pulumi.Input<string>;
    pathAccountSid?: pulumi.Input<string | undefined>;
    resourceSid: pulumi.Input<string>;
}
