// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ChatServicesV2 extends pulumi.CustomResource {
    /**
     * Get an existing ChatServicesV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ChatServicesV2State, opts?: pulumi.CustomResourceOptions): ChatServicesV2 {
        return new ChatServicesV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/chatServicesV2:ChatServicesV2';

    /**
     * Returns true if the given object is an instance of ChatServicesV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ChatServicesV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ChatServicesV2.__pulumiType;
    }

    declare public readonly consumptionReportInterval: pulumi.Output<number>;
    declare public readonly defaultChannelCreatorRoleSid: pulumi.Output<string>;
    declare public readonly defaultChannelRoleSid: pulumi.Output<string>;
    declare public readonly defaultServiceRoleSid: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly limitsChannelMembers: pulumi.Output<number>;
    declare public readonly limitsUserChannels: pulumi.Output<number>;
    declare public readonly mediaCompatibilityMessage: pulumi.Output<string>;
    declare public readonly notificationsAddedToChannelEnabled: pulumi.Output<boolean>;
    declare public readonly notificationsAddedToChannelSound: pulumi.Output<string>;
    declare public readonly notificationsAddedToChannelTemplate: pulumi.Output<string>;
    declare public readonly notificationsInvitedToChannelEnabled: pulumi.Output<boolean>;
    declare public readonly notificationsInvitedToChannelSound: pulumi.Output<string>;
    declare public readonly notificationsInvitedToChannelTemplate: pulumi.Output<string>;
    declare public readonly notificationsLogEnabled: pulumi.Output<boolean>;
    declare public readonly notificationsNewMessageBadgeCountEnabled: pulumi.Output<boolean>;
    declare public readonly notificationsNewMessageEnabled: pulumi.Output<boolean>;
    declare public readonly notificationsNewMessageSound: pulumi.Output<string>;
    declare public readonly notificationsNewMessageTemplate: pulumi.Output<string>;
    declare public readonly notificationsRemovedFromChannelEnabled: pulumi.Output<boolean>;
    declare public readonly notificationsRemovedFromChannelSound: pulumi.Output<string>;
    declare public readonly notificationsRemovedFromChannelTemplate: pulumi.Output<string>;
    declare public readonly postWebhookRetryCount: pulumi.Output<number>;
    declare public readonly postWebhookUrl: pulumi.Output<string>;
    declare public readonly preWebhookRetryCount: pulumi.Output<number>;
    declare public readonly preWebhookUrl: pulumi.Output<string>;
    declare public readonly reachabilityEnabled: pulumi.Output<boolean>;
    declare public readonly readStatusEnabled: pulumi.Output<boolean>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly typingIndicatorTimeout: pulumi.Output<number>;
    declare public readonly webhookFilters: pulumi.Output<string[]>;
    declare public readonly webhookMethod: pulumi.Output<string>;

    /**
     * Create a ChatServicesV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ChatServicesV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ChatServicesV2Args | ChatServicesV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ChatServicesV2State | undefined;
            resourceInputs["consumptionReportInterval"] = state?.consumptionReportInterval;
            resourceInputs["defaultChannelCreatorRoleSid"] = state?.defaultChannelCreatorRoleSid;
            resourceInputs["defaultChannelRoleSid"] = state?.defaultChannelRoleSid;
            resourceInputs["defaultServiceRoleSid"] = state?.defaultServiceRoleSid;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["limitsChannelMembers"] = state?.limitsChannelMembers;
            resourceInputs["limitsUserChannels"] = state?.limitsUserChannels;
            resourceInputs["mediaCompatibilityMessage"] = state?.mediaCompatibilityMessage;
            resourceInputs["notificationsAddedToChannelEnabled"] = state?.notificationsAddedToChannelEnabled;
            resourceInputs["notificationsAddedToChannelSound"] = state?.notificationsAddedToChannelSound;
            resourceInputs["notificationsAddedToChannelTemplate"] = state?.notificationsAddedToChannelTemplate;
            resourceInputs["notificationsInvitedToChannelEnabled"] = state?.notificationsInvitedToChannelEnabled;
            resourceInputs["notificationsInvitedToChannelSound"] = state?.notificationsInvitedToChannelSound;
            resourceInputs["notificationsInvitedToChannelTemplate"] = state?.notificationsInvitedToChannelTemplate;
            resourceInputs["notificationsLogEnabled"] = state?.notificationsLogEnabled;
            resourceInputs["notificationsNewMessageBadgeCountEnabled"] = state?.notificationsNewMessageBadgeCountEnabled;
            resourceInputs["notificationsNewMessageEnabled"] = state?.notificationsNewMessageEnabled;
            resourceInputs["notificationsNewMessageSound"] = state?.notificationsNewMessageSound;
            resourceInputs["notificationsNewMessageTemplate"] = state?.notificationsNewMessageTemplate;
            resourceInputs["notificationsRemovedFromChannelEnabled"] = state?.notificationsRemovedFromChannelEnabled;
            resourceInputs["notificationsRemovedFromChannelSound"] = state?.notificationsRemovedFromChannelSound;
            resourceInputs["notificationsRemovedFromChannelTemplate"] = state?.notificationsRemovedFromChannelTemplate;
            resourceInputs["postWebhookRetryCount"] = state?.postWebhookRetryCount;
            resourceInputs["postWebhookUrl"] = state?.postWebhookUrl;
            resourceInputs["preWebhookRetryCount"] = state?.preWebhookRetryCount;
            resourceInputs["preWebhookUrl"] = state?.preWebhookUrl;
            resourceInputs["reachabilityEnabled"] = state?.reachabilityEnabled;
            resourceInputs["readStatusEnabled"] = state?.readStatusEnabled;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["typingIndicatorTimeout"] = state?.typingIndicatorTimeout;
            resourceInputs["webhookFilters"] = state?.webhookFilters;
            resourceInputs["webhookMethod"] = state?.webhookMethod;
        } else {
            const args = argsOrState as ChatServicesV2Args | undefined;
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            resourceInputs["consumptionReportInterval"] = args?.consumptionReportInterval;
            resourceInputs["defaultChannelCreatorRoleSid"] = args?.defaultChannelCreatorRoleSid;
            resourceInputs["defaultChannelRoleSid"] = args?.defaultChannelRoleSid;
            resourceInputs["defaultServiceRoleSid"] = args?.defaultServiceRoleSid;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["limitsChannelMembers"] = args?.limitsChannelMembers;
            resourceInputs["limitsUserChannels"] = args?.limitsUserChannels;
            resourceInputs["mediaCompatibilityMessage"] = args?.mediaCompatibilityMessage;
            resourceInputs["notificationsAddedToChannelEnabled"] = args?.notificationsAddedToChannelEnabled;
            resourceInputs["notificationsAddedToChannelSound"] = args?.notificationsAddedToChannelSound;
            resourceInputs["notificationsAddedToChannelTemplate"] = args?.notificationsAddedToChannelTemplate;
            resourceInputs["notificationsInvitedToChannelEnabled"] = args?.notificationsInvitedToChannelEnabled;
            resourceInputs["notificationsInvitedToChannelSound"] = args?.notificationsInvitedToChannelSound;
            resourceInputs["notificationsInvitedToChannelTemplate"] = args?.notificationsInvitedToChannelTemplate;
            resourceInputs["notificationsLogEnabled"] = args?.notificationsLogEnabled;
            resourceInputs["notificationsNewMessageBadgeCountEnabled"] = args?.notificationsNewMessageBadgeCountEnabled;
            resourceInputs["notificationsNewMessageEnabled"] = args?.notificationsNewMessageEnabled;
            resourceInputs["notificationsNewMessageSound"] = args?.notificationsNewMessageSound;
            resourceInputs["notificationsNewMessageTemplate"] = args?.notificationsNewMessageTemplate;
            resourceInputs["notificationsRemovedFromChannelEnabled"] = args?.notificationsRemovedFromChannelEnabled;
            resourceInputs["notificationsRemovedFromChannelSound"] = args?.notificationsRemovedFromChannelSound;
            resourceInputs["notificationsRemovedFromChannelTemplate"] = args?.notificationsRemovedFromChannelTemplate;
            resourceInputs["postWebhookRetryCount"] = args?.postWebhookRetryCount;
            resourceInputs["postWebhookUrl"] = args?.postWebhookUrl;
            resourceInputs["preWebhookRetryCount"] = args?.preWebhookRetryCount;
            resourceInputs["preWebhookUrl"] = args?.preWebhookUrl;
            resourceInputs["reachabilityEnabled"] = args?.reachabilityEnabled;
            resourceInputs["readStatusEnabled"] = args?.readStatusEnabled;
            resourceInputs["typingIndicatorTimeout"] = args?.typingIndicatorTimeout;
            resourceInputs["webhookFilters"] = args?.webhookFilters;
            resourceInputs["webhookMethod"] = args?.webhookMethod;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ChatServicesV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ChatServicesV2 resources.
 */
export interface ChatServicesV2State {
    consumptionReportInterval?: pulumi.Input<number | undefined>;
    defaultChannelCreatorRoleSid?: pulumi.Input<string | undefined>;
    defaultChannelRoleSid?: pulumi.Input<string | undefined>;
    defaultServiceRoleSid?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    limitsChannelMembers?: pulumi.Input<number | undefined>;
    limitsUserChannels?: pulumi.Input<number | undefined>;
    mediaCompatibilityMessage?: pulumi.Input<string | undefined>;
    notificationsAddedToChannelEnabled?: pulumi.Input<boolean | undefined>;
    notificationsAddedToChannelSound?: pulumi.Input<string | undefined>;
    notificationsAddedToChannelTemplate?: pulumi.Input<string | undefined>;
    notificationsInvitedToChannelEnabled?: pulumi.Input<boolean | undefined>;
    notificationsInvitedToChannelSound?: pulumi.Input<string | undefined>;
    notificationsInvitedToChannelTemplate?: pulumi.Input<string | undefined>;
    notificationsLogEnabled?: pulumi.Input<boolean | undefined>;
    notificationsNewMessageBadgeCountEnabled?: pulumi.Input<boolean | undefined>;
    notificationsNewMessageEnabled?: pulumi.Input<boolean | undefined>;
    notificationsNewMessageSound?: pulumi.Input<string | undefined>;
    notificationsNewMessageTemplate?: pulumi.Input<string | undefined>;
    notificationsRemovedFromChannelEnabled?: pulumi.Input<boolean | undefined>;
    notificationsRemovedFromChannelSound?: pulumi.Input<string | undefined>;
    notificationsRemovedFromChannelTemplate?: pulumi.Input<string | undefined>;
    postWebhookRetryCount?: pulumi.Input<number | undefined>;
    postWebhookUrl?: pulumi.Input<string | undefined>;
    preWebhookRetryCount?: pulumi.Input<number | undefined>;
    preWebhookUrl?: pulumi.Input<string | undefined>;
    reachabilityEnabled?: pulumi.Input<boolean | undefined>;
    readStatusEnabled?: pulumi.Input<boolean | undefined>;
    sid?: pulumi.Input<string | undefined>;
    typingIndicatorTimeout?: pulumi.Input<number | undefined>;
    webhookFilters?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    webhookMethod?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ChatServicesV2 resource.
 */
export interface ChatServicesV2Args {
    consumptionReportInterval?: pulumi.Input<number | undefined>;
    defaultChannelCreatorRoleSid?: pulumi.Input<string | undefined>;
    defaultChannelRoleSid?: pulumi.Input<string | undefined>;
    defaultServiceRoleSid?: pulumi.Input<string | undefined>;
    friendlyName: pulumi.Input<string>;
    limitsChannelMembers?: pulumi.Input<number | undefined>;
    limitsUserChannels?: pulumi.Input<number | undefined>;
    mediaCompatibilityMessage?: pulumi.Input<string | undefined>;
    notificationsAddedToChannelEnabled?: pulumi.Input<boolean | undefined>;
    notificationsAddedToChannelSound?: pulumi.Input<string | undefined>;
    notificationsAddedToChannelTemplate?: pulumi.Input<string | undefined>;
    notificationsInvitedToChannelEnabled?: pulumi.Input<boolean | undefined>;
    notificationsInvitedToChannelSound?: pulumi.Input<string | undefined>;
    notificationsInvitedToChannelTemplate?: pulumi.Input<string | undefined>;
    notificationsLogEnabled?: pulumi.Input<boolean | undefined>;
    notificationsNewMessageBadgeCountEnabled?: pulumi.Input<boolean | undefined>;
    notificationsNewMessageEnabled?: pulumi.Input<boolean | undefined>;
    notificationsNewMessageSound?: pulumi.Input<string | undefined>;
    notificationsNewMessageTemplate?: pulumi.Input<string | undefined>;
    notificationsRemovedFromChannelEnabled?: pulumi.Input<boolean | undefined>;
    notificationsRemovedFromChannelSound?: pulumi.Input<string | undefined>;
    notificationsRemovedFromChannelTemplate?: pulumi.Input<string | undefined>;
    postWebhookRetryCount?: pulumi.Input<number | undefined>;
    postWebhookUrl?: pulumi.Input<string | undefined>;
    preWebhookRetryCount?: pulumi.Input<number | undefined>;
    preWebhookUrl?: pulumi.Input<string | undefined>;
    reachabilityEnabled?: pulumi.Input<boolean | undefined>;
    readStatusEnabled?: pulumi.Input<boolean | undefined>;
    typingIndicatorTimeout?: pulumi.Input<number | undefined>;
    webhookFilters?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    webhookMethod?: pulumi.Input<string | undefined>;
}
