// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ChatServicesV1 extends pulumi.CustomResource {
    /**
     * Get an existing ChatServicesV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ChatServicesV1State, opts?: pulumi.CustomResourceOptions): ChatServicesV1 {
        return new ChatServicesV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/chatServicesV1:ChatServicesV1';

    /**
     * Returns true if the given object is an instance of ChatServicesV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ChatServicesV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ChatServicesV1.__pulumiType;
    }

    declare public readonly consumptionReportInterval: pulumi.Output<number>;
    declare public readonly defaultChannelCreatorRoleSid: pulumi.Output<string>;
    declare public readonly defaultChannelRoleSid: pulumi.Output<string>;
    declare public readonly defaultServiceRoleSid: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly limitsChannelMembers: pulumi.Output<number>;
    declare public readonly limitsUserChannels: pulumi.Output<number>;
    declare public readonly notificationsAddedToChannelEnabled: pulumi.Output<boolean>;
    declare public readonly notificationsAddedToChannelTemplate: pulumi.Output<string>;
    declare public readonly notificationsInvitedToChannelEnabled: pulumi.Output<boolean>;
    declare public readonly notificationsInvitedToChannelTemplate: pulumi.Output<string>;
    declare public readonly notificationsNewMessageEnabled: pulumi.Output<boolean>;
    declare public readonly notificationsNewMessageTemplate: pulumi.Output<string>;
    declare public readonly notificationsRemovedFromChannelEnabled: pulumi.Output<boolean>;
    declare public readonly notificationsRemovedFromChannelTemplate: pulumi.Output<string>;
    declare public readonly postWebhookUrl: pulumi.Output<string>;
    declare public readonly preWebhookUrl: pulumi.Output<string>;
    declare public readonly reachabilityEnabled: pulumi.Output<boolean>;
    declare public readonly readStatusEnabled: pulumi.Output<boolean>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly typingIndicatorTimeout: pulumi.Output<number>;
    declare public readonly webhookFilters: pulumi.Output<string[]>;
    declare public readonly webhookMethod: pulumi.Output<string>;
    declare public readonly webhooksOnChannelAddMethod: pulumi.Output<string>;
    declare public readonly webhooksOnChannelAddUrl: pulumi.Output<string>;
    declare public readonly webhooksOnChannelAddedMethod: pulumi.Output<string>;
    declare public readonly webhooksOnChannelAddedUrl: pulumi.Output<string>;
    declare public readonly webhooksOnChannelDestroyMethod: pulumi.Output<string>;
    declare public readonly webhooksOnChannelDestroyUrl: pulumi.Output<string>;
    declare public readonly webhooksOnChannelDestroyedMethod: pulumi.Output<string>;
    declare public readonly webhooksOnChannelDestroyedUrl: pulumi.Output<string>;
    declare public readonly webhooksOnChannelUpdateMethod: pulumi.Output<string>;
    declare public readonly webhooksOnChannelUpdateUrl: pulumi.Output<string>;
    declare public readonly webhooksOnChannelUpdatedMethod: pulumi.Output<string>;
    declare public readonly webhooksOnChannelUpdatedUrl: pulumi.Output<string>;
    declare public readonly webhooksOnMemberAddMethod: pulumi.Output<string>;
    declare public readonly webhooksOnMemberAddUrl: pulumi.Output<string>;
    declare public readonly webhooksOnMemberAddedMethod: pulumi.Output<string>;
    declare public readonly webhooksOnMemberAddedUrl: pulumi.Output<string>;
    declare public readonly webhooksOnMemberRemoveMethod: pulumi.Output<string>;
    declare public readonly webhooksOnMemberRemoveUrl: pulumi.Output<string>;
    declare public readonly webhooksOnMemberRemovedMethod: pulumi.Output<string>;
    declare public readonly webhooksOnMemberRemovedUrl: pulumi.Output<string>;
    declare public readonly webhooksOnMessageRemoveMethod: pulumi.Output<string>;
    declare public readonly webhooksOnMessageRemoveUrl: pulumi.Output<string>;
    declare public readonly webhooksOnMessageRemovedMethod: pulumi.Output<string>;
    declare public readonly webhooksOnMessageRemovedUrl: pulumi.Output<string>;
    declare public readonly webhooksOnMessageSendMethod: pulumi.Output<string>;
    declare public readonly webhooksOnMessageSendUrl: pulumi.Output<string>;
    declare public readonly webhooksOnMessageSentMethod: pulumi.Output<string>;
    declare public readonly webhooksOnMessageSentUrl: pulumi.Output<string>;
    declare public readonly webhooksOnMessageUpdateMethod: pulumi.Output<string>;
    declare public readonly webhooksOnMessageUpdateUrl: pulumi.Output<string>;
    declare public readonly webhooksOnMessageUpdatedMethod: pulumi.Output<string>;
    declare public readonly webhooksOnMessageUpdatedUrl: pulumi.Output<string>;

    /**
     * Create a ChatServicesV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ChatServicesV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ChatServicesV1Args | ChatServicesV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ChatServicesV1State | undefined;
            resourceInputs["consumptionReportInterval"] = state?.consumptionReportInterval;
            resourceInputs["defaultChannelCreatorRoleSid"] = state?.defaultChannelCreatorRoleSid;
            resourceInputs["defaultChannelRoleSid"] = state?.defaultChannelRoleSid;
            resourceInputs["defaultServiceRoleSid"] = state?.defaultServiceRoleSid;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["limitsChannelMembers"] = state?.limitsChannelMembers;
            resourceInputs["limitsUserChannels"] = state?.limitsUserChannels;
            resourceInputs["notificationsAddedToChannelEnabled"] = state?.notificationsAddedToChannelEnabled;
            resourceInputs["notificationsAddedToChannelTemplate"] = state?.notificationsAddedToChannelTemplate;
            resourceInputs["notificationsInvitedToChannelEnabled"] = state?.notificationsInvitedToChannelEnabled;
            resourceInputs["notificationsInvitedToChannelTemplate"] = state?.notificationsInvitedToChannelTemplate;
            resourceInputs["notificationsNewMessageEnabled"] = state?.notificationsNewMessageEnabled;
            resourceInputs["notificationsNewMessageTemplate"] = state?.notificationsNewMessageTemplate;
            resourceInputs["notificationsRemovedFromChannelEnabled"] = state?.notificationsRemovedFromChannelEnabled;
            resourceInputs["notificationsRemovedFromChannelTemplate"] = state?.notificationsRemovedFromChannelTemplate;
            resourceInputs["postWebhookUrl"] = state?.postWebhookUrl;
            resourceInputs["preWebhookUrl"] = state?.preWebhookUrl;
            resourceInputs["reachabilityEnabled"] = state?.reachabilityEnabled;
            resourceInputs["readStatusEnabled"] = state?.readStatusEnabled;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["typingIndicatorTimeout"] = state?.typingIndicatorTimeout;
            resourceInputs["webhookFilters"] = state?.webhookFilters;
            resourceInputs["webhookMethod"] = state?.webhookMethod;
            resourceInputs["webhooksOnChannelAddMethod"] = state?.webhooksOnChannelAddMethod;
            resourceInputs["webhooksOnChannelAddUrl"] = state?.webhooksOnChannelAddUrl;
            resourceInputs["webhooksOnChannelAddedMethod"] = state?.webhooksOnChannelAddedMethod;
            resourceInputs["webhooksOnChannelAddedUrl"] = state?.webhooksOnChannelAddedUrl;
            resourceInputs["webhooksOnChannelDestroyMethod"] = state?.webhooksOnChannelDestroyMethod;
            resourceInputs["webhooksOnChannelDestroyUrl"] = state?.webhooksOnChannelDestroyUrl;
            resourceInputs["webhooksOnChannelDestroyedMethod"] = state?.webhooksOnChannelDestroyedMethod;
            resourceInputs["webhooksOnChannelDestroyedUrl"] = state?.webhooksOnChannelDestroyedUrl;
            resourceInputs["webhooksOnChannelUpdateMethod"] = state?.webhooksOnChannelUpdateMethod;
            resourceInputs["webhooksOnChannelUpdateUrl"] = state?.webhooksOnChannelUpdateUrl;
            resourceInputs["webhooksOnChannelUpdatedMethod"] = state?.webhooksOnChannelUpdatedMethod;
            resourceInputs["webhooksOnChannelUpdatedUrl"] = state?.webhooksOnChannelUpdatedUrl;
            resourceInputs["webhooksOnMemberAddMethod"] = state?.webhooksOnMemberAddMethod;
            resourceInputs["webhooksOnMemberAddUrl"] = state?.webhooksOnMemberAddUrl;
            resourceInputs["webhooksOnMemberAddedMethod"] = state?.webhooksOnMemberAddedMethod;
            resourceInputs["webhooksOnMemberAddedUrl"] = state?.webhooksOnMemberAddedUrl;
            resourceInputs["webhooksOnMemberRemoveMethod"] = state?.webhooksOnMemberRemoveMethod;
            resourceInputs["webhooksOnMemberRemoveUrl"] = state?.webhooksOnMemberRemoveUrl;
            resourceInputs["webhooksOnMemberRemovedMethod"] = state?.webhooksOnMemberRemovedMethod;
            resourceInputs["webhooksOnMemberRemovedUrl"] = state?.webhooksOnMemberRemovedUrl;
            resourceInputs["webhooksOnMessageRemoveMethod"] = state?.webhooksOnMessageRemoveMethod;
            resourceInputs["webhooksOnMessageRemoveUrl"] = state?.webhooksOnMessageRemoveUrl;
            resourceInputs["webhooksOnMessageRemovedMethod"] = state?.webhooksOnMessageRemovedMethod;
            resourceInputs["webhooksOnMessageRemovedUrl"] = state?.webhooksOnMessageRemovedUrl;
            resourceInputs["webhooksOnMessageSendMethod"] = state?.webhooksOnMessageSendMethod;
            resourceInputs["webhooksOnMessageSendUrl"] = state?.webhooksOnMessageSendUrl;
            resourceInputs["webhooksOnMessageSentMethod"] = state?.webhooksOnMessageSentMethod;
            resourceInputs["webhooksOnMessageSentUrl"] = state?.webhooksOnMessageSentUrl;
            resourceInputs["webhooksOnMessageUpdateMethod"] = state?.webhooksOnMessageUpdateMethod;
            resourceInputs["webhooksOnMessageUpdateUrl"] = state?.webhooksOnMessageUpdateUrl;
            resourceInputs["webhooksOnMessageUpdatedMethod"] = state?.webhooksOnMessageUpdatedMethod;
            resourceInputs["webhooksOnMessageUpdatedUrl"] = state?.webhooksOnMessageUpdatedUrl;
        } else {
            const args = argsOrState as ChatServicesV1Args | undefined;
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            resourceInputs["consumptionReportInterval"] = args?.consumptionReportInterval;
            resourceInputs["defaultChannelCreatorRoleSid"] = args?.defaultChannelCreatorRoleSid;
            resourceInputs["defaultChannelRoleSid"] = args?.defaultChannelRoleSid;
            resourceInputs["defaultServiceRoleSid"] = args?.defaultServiceRoleSid;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["limitsChannelMembers"] = args?.limitsChannelMembers;
            resourceInputs["limitsUserChannels"] = args?.limitsUserChannels;
            resourceInputs["notificationsAddedToChannelEnabled"] = args?.notificationsAddedToChannelEnabled;
            resourceInputs["notificationsAddedToChannelTemplate"] = args?.notificationsAddedToChannelTemplate;
            resourceInputs["notificationsInvitedToChannelEnabled"] = args?.notificationsInvitedToChannelEnabled;
            resourceInputs["notificationsInvitedToChannelTemplate"] = args?.notificationsInvitedToChannelTemplate;
            resourceInputs["notificationsNewMessageEnabled"] = args?.notificationsNewMessageEnabled;
            resourceInputs["notificationsNewMessageTemplate"] = args?.notificationsNewMessageTemplate;
            resourceInputs["notificationsRemovedFromChannelEnabled"] = args?.notificationsRemovedFromChannelEnabled;
            resourceInputs["notificationsRemovedFromChannelTemplate"] = args?.notificationsRemovedFromChannelTemplate;
            resourceInputs["postWebhookUrl"] = args?.postWebhookUrl;
            resourceInputs["preWebhookUrl"] = args?.preWebhookUrl;
            resourceInputs["reachabilityEnabled"] = args?.reachabilityEnabled;
            resourceInputs["readStatusEnabled"] = args?.readStatusEnabled;
            resourceInputs["typingIndicatorTimeout"] = args?.typingIndicatorTimeout;
            resourceInputs["webhookFilters"] = args?.webhookFilters;
            resourceInputs["webhookMethod"] = args?.webhookMethod;
            resourceInputs["webhooksOnChannelAddMethod"] = args?.webhooksOnChannelAddMethod;
            resourceInputs["webhooksOnChannelAddUrl"] = args?.webhooksOnChannelAddUrl;
            resourceInputs["webhooksOnChannelAddedMethod"] = args?.webhooksOnChannelAddedMethod;
            resourceInputs["webhooksOnChannelAddedUrl"] = args?.webhooksOnChannelAddedUrl;
            resourceInputs["webhooksOnChannelDestroyMethod"] = args?.webhooksOnChannelDestroyMethod;
            resourceInputs["webhooksOnChannelDestroyUrl"] = args?.webhooksOnChannelDestroyUrl;
            resourceInputs["webhooksOnChannelDestroyedMethod"] = args?.webhooksOnChannelDestroyedMethod;
            resourceInputs["webhooksOnChannelDestroyedUrl"] = args?.webhooksOnChannelDestroyedUrl;
            resourceInputs["webhooksOnChannelUpdateMethod"] = args?.webhooksOnChannelUpdateMethod;
            resourceInputs["webhooksOnChannelUpdateUrl"] = args?.webhooksOnChannelUpdateUrl;
            resourceInputs["webhooksOnChannelUpdatedMethod"] = args?.webhooksOnChannelUpdatedMethod;
            resourceInputs["webhooksOnChannelUpdatedUrl"] = args?.webhooksOnChannelUpdatedUrl;
            resourceInputs["webhooksOnMemberAddMethod"] = args?.webhooksOnMemberAddMethod;
            resourceInputs["webhooksOnMemberAddUrl"] = args?.webhooksOnMemberAddUrl;
            resourceInputs["webhooksOnMemberAddedMethod"] = args?.webhooksOnMemberAddedMethod;
            resourceInputs["webhooksOnMemberAddedUrl"] = args?.webhooksOnMemberAddedUrl;
            resourceInputs["webhooksOnMemberRemoveMethod"] = args?.webhooksOnMemberRemoveMethod;
            resourceInputs["webhooksOnMemberRemoveUrl"] = args?.webhooksOnMemberRemoveUrl;
            resourceInputs["webhooksOnMemberRemovedMethod"] = args?.webhooksOnMemberRemovedMethod;
            resourceInputs["webhooksOnMemberRemovedUrl"] = args?.webhooksOnMemberRemovedUrl;
            resourceInputs["webhooksOnMessageRemoveMethod"] = args?.webhooksOnMessageRemoveMethod;
            resourceInputs["webhooksOnMessageRemoveUrl"] = args?.webhooksOnMessageRemoveUrl;
            resourceInputs["webhooksOnMessageRemovedMethod"] = args?.webhooksOnMessageRemovedMethod;
            resourceInputs["webhooksOnMessageRemovedUrl"] = args?.webhooksOnMessageRemovedUrl;
            resourceInputs["webhooksOnMessageSendMethod"] = args?.webhooksOnMessageSendMethod;
            resourceInputs["webhooksOnMessageSendUrl"] = args?.webhooksOnMessageSendUrl;
            resourceInputs["webhooksOnMessageSentMethod"] = args?.webhooksOnMessageSentMethod;
            resourceInputs["webhooksOnMessageSentUrl"] = args?.webhooksOnMessageSentUrl;
            resourceInputs["webhooksOnMessageUpdateMethod"] = args?.webhooksOnMessageUpdateMethod;
            resourceInputs["webhooksOnMessageUpdateUrl"] = args?.webhooksOnMessageUpdateUrl;
            resourceInputs["webhooksOnMessageUpdatedMethod"] = args?.webhooksOnMessageUpdatedMethod;
            resourceInputs["webhooksOnMessageUpdatedUrl"] = args?.webhooksOnMessageUpdatedUrl;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ChatServicesV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ChatServicesV1 resources.
 */
export interface ChatServicesV1State {
    consumptionReportInterval?: pulumi.Input<number | undefined>;
    defaultChannelCreatorRoleSid?: pulumi.Input<string | undefined>;
    defaultChannelRoleSid?: pulumi.Input<string | undefined>;
    defaultServiceRoleSid?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    limitsChannelMembers?: pulumi.Input<number | undefined>;
    limitsUserChannels?: pulumi.Input<number | undefined>;
    notificationsAddedToChannelEnabled?: pulumi.Input<boolean | undefined>;
    notificationsAddedToChannelTemplate?: pulumi.Input<string | undefined>;
    notificationsInvitedToChannelEnabled?: pulumi.Input<boolean | undefined>;
    notificationsInvitedToChannelTemplate?: pulumi.Input<string | undefined>;
    notificationsNewMessageEnabled?: pulumi.Input<boolean | undefined>;
    notificationsNewMessageTemplate?: pulumi.Input<string | undefined>;
    notificationsRemovedFromChannelEnabled?: pulumi.Input<boolean | undefined>;
    notificationsRemovedFromChannelTemplate?: pulumi.Input<string | undefined>;
    postWebhookUrl?: pulumi.Input<string | undefined>;
    preWebhookUrl?: pulumi.Input<string | undefined>;
    reachabilityEnabled?: pulumi.Input<boolean | undefined>;
    readStatusEnabled?: pulumi.Input<boolean | undefined>;
    sid?: pulumi.Input<string | undefined>;
    typingIndicatorTimeout?: pulumi.Input<number | undefined>;
    webhookFilters?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    webhookMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelAddMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelAddUrl?: pulumi.Input<string | undefined>;
    webhooksOnChannelAddedMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelAddedUrl?: pulumi.Input<string | undefined>;
    webhooksOnChannelDestroyMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelDestroyUrl?: pulumi.Input<string | undefined>;
    webhooksOnChannelDestroyedMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelDestroyedUrl?: pulumi.Input<string | undefined>;
    webhooksOnChannelUpdateMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelUpdateUrl?: pulumi.Input<string | undefined>;
    webhooksOnChannelUpdatedMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelUpdatedUrl?: pulumi.Input<string | undefined>;
    webhooksOnMemberAddMethod?: pulumi.Input<string | undefined>;
    webhooksOnMemberAddUrl?: pulumi.Input<string | undefined>;
    webhooksOnMemberAddedMethod?: pulumi.Input<string | undefined>;
    webhooksOnMemberAddedUrl?: pulumi.Input<string | undefined>;
    webhooksOnMemberRemoveMethod?: pulumi.Input<string | undefined>;
    webhooksOnMemberRemoveUrl?: pulumi.Input<string | undefined>;
    webhooksOnMemberRemovedMethod?: pulumi.Input<string | undefined>;
    webhooksOnMemberRemovedUrl?: pulumi.Input<string | undefined>;
    webhooksOnMessageRemoveMethod?: pulumi.Input<string | undefined>;
    webhooksOnMessageRemoveUrl?: pulumi.Input<string | undefined>;
    webhooksOnMessageRemovedMethod?: pulumi.Input<string | undefined>;
    webhooksOnMessageRemovedUrl?: pulumi.Input<string | undefined>;
    webhooksOnMessageSendMethod?: pulumi.Input<string | undefined>;
    webhooksOnMessageSendUrl?: pulumi.Input<string | undefined>;
    webhooksOnMessageSentMethod?: pulumi.Input<string | undefined>;
    webhooksOnMessageSentUrl?: pulumi.Input<string | undefined>;
    webhooksOnMessageUpdateMethod?: pulumi.Input<string | undefined>;
    webhooksOnMessageUpdateUrl?: pulumi.Input<string | undefined>;
    webhooksOnMessageUpdatedMethod?: pulumi.Input<string | undefined>;
    webhooksOnMessageUpdatedUrl?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ChatServicesV1 resource.
 */
export interface ChatServicesV1Args {
    consumptionReportInterval?: pulumi.Input<number | undefined>;
    defaultChannelCreatorRoleSid?: pulumi.Input<string | undefined>;
    defaultChannelRoleSid?: pulumi.Input<string | undefined>;
    defaultServiceRoleSid?: pulumi.Input<string | undefined>;
    friendlyName: pulumi.Input<string>;
    limitsChannelMembers?: pulumi.Input<number | undefined>;
    limitsUserChannels?: pulumi.Input<number | undefined>;
    notificationsAddedToChannelEnabled?: pulumi.Input<boolean | undefined>;
    notificationsAddedToChannelTemplate?: pulumi.Input<string | undefined>;
    notificationsInvitedToChannelEnabled?: pulumi.Input<boolean | undefined>;
    notificationsInvitedToChannelTemplate?: pulumi.Input<string | undefined>;
    notificationsNewMessageEnabled?: pulumi.Input<boolean | undefined>;
    notificationsNewMessageTemplate?: pulumi.Input<string | undefined>;
    notificationsRemovedFromChannelEnabled?: pulumi.Input<boolean | undefined>;
    notificationsRemovedFromChannelTemplate?: pulumi.Input<string | undefined>;
    postWebhookUrl?: pulumi.Input<string | undefined>;
    preWebhookUrl?: pulumi.Input<string | undefined>;
    reachabilityEnabled?: pulumi.Input<boolean | undefined>;
    readStatusEnabled?: pulumi.Input<boolean | undefined>;
    typingIndicatorTimeout?: pulumi.Input<number | undefined>;
    webhookFilters?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    webhookMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelAddMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelAddUrl?: pulumi.Input<string | undefined>;
    webhooksOnChannelAddedMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelAddedUrl?: pulumi.Input<string | undefined>;
    webhooksOnChannelDestroyMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelDestroyUrl?: pulumi.Input<string | undefined>;
    webhooksOnChannelDestroyedMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelDestroyedUrl?: pulumi.Input<string | undefined>;
    webhooksOnChannelUpdateMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelUpdateUrl?: pulumi.Input<string | undefined>;
    webhooksOnChannelUpdatedMethod?: pulumi.Input<string | undefined>;
    webhooksOnChannelUpdatedUrl?: pulumi.Input<string | undefined>;
    webhooksOnMemberAddMethod?: pulumi.Input<string | undefined>;
    webhooksOnMemberAddUrl?: pulumi.Input<string | undefined>;
    webhooksOnMemberAddedMethod?: pulumi.Input<string | undefined>;
    webhooksOnMemberAddedUrl?: pulumi.Input<string | undefined>;
    webhooksOnMemberRemoveMethod?: pulumi.Input<string | undefined>;
    webhooksOnMemberRemoveUrl?: pulumi.Input<string | undefined>;
    webhooksOnMemberRemovedMethod?: pulumi.Input<string | undefined>;
    webhooksOnMemberRemovedUrl?: pulumi.Input<string | undefined>;
    webhooksOnMessageRemoveMethod?: pulumi.Input<string | undefined>;
    webhooksOnMessageRemoveUrl?: pulumi.Input<string | undefined>;
    webhooksOnMessageRemovedMethod?: pulumi.Input<string | undefined>;
    webhooksOnMessageRemovedUrl?: pulumi.Input<string | undefined>;
    webhooksOnMessageSendMethod?: pulumi.Input<string | undefined>;
    webhooksOnMessageSendUrl?: pulumi.Input<string | undefined>;
    webhooksOnMessageSentMethod?: pulumi.Input<string | undefined>;
    webhooksOnMessageSentUrl?: pulumi.Input<string | undefined>;
    webhooksOnMessageUpdateMethod?: pulumi.Input<string | undefined>;
    webhooksOnMessageUpdateUrl?: pulumi.Input<string | undefined>;
    webhooksOnMessageUpdatedMethod?: pulumi.Input<string | undefined>;
    webhooksOnMessageUpdatedUrl?: pulumi.Input<string | undefined>;
}
