// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ChatServicesChannelsMembersV1 extends pulumi.CustomResource {
    /**
     * Get an existing ChatServicesChannelsMembersV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ChatServicesChannelsMembersV1State, opts?: pulumi.CustomResourceOptions): ChatServicesChannelsMembersV1 {
        return new ChatServicesChannelsMembersV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/chatServicesChannelsMembersV1:ChatServicesChannelsMembersV1';

    /**
     * Returns true if the given object is an instance of ChatServicesChannelsMembersV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ChatServicesChannelsMembersV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ChatServicesChannelsMembersV1.__pulumiType;
    }

    declare public readonly channelSid: pulumi.Output<string>;
    declare public readonly identity: pulumi.Output<string>;
    declare public readonly lastConsumedMessageIndex: pulumi.Output<number>;
    declare public readonly roleSid: pulumi.Output<string>;
    declare public readonly serviceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a ChatServicesChannelsMembersV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ChatServicesChannelsMembersV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ChatServicesChannelsMembersV1Args | ChatServicesChannelsMembersV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ChatServicesChannelsMembersV1State | undefined;
            resourceInputs["channelSid"] = state?.channelSid;
            resourceInputs["identity"] = state?.identity;
            resourceInputs["lastConsumedMessageIndex"] = state?.lastConsumedMessageIndex;
            resourceInputs["roleSid"] = state?.roleSid;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as ChatServicesChannelsMembersV1Args | undefined;
            if (args?.channelSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'channelSid'");
            }
            if (args?.identity === undefined && !opts.urn) {
                throw new Error("Missing required property 'identity'");
            }
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            resourceInputs["channelSid"] = args?.channelSid;
            resourceInputs["identity"] = args?.identity;
            resourceInputs["lastConsumedMessageIndex"] = args?.lastConsumedMessageIndex;
            resourceInputs["roleSid"] = args?.roleSid;
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ChatServicesChannelsMembersV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ChatServicesChannelsMembersV1 resources.
 */
export interface ChatServicesChannelsMembersV1State {
    channelSid?: pulumi.Input<string | undefined>;
    identity?: pulumi.Input<string | undefined>;
    lastConsumedMessageIndex?: pulumi.Input<number | undefined>;
    roleSid?: pulumi.Input<string | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ChatServicesChannelsMembersV1 resource.
 */
export interface ChatServicesChannelsMembersV1Args {
    channelSid: pulumi.Input<string>;
    identity: pulumi.Input<string>;
    lastConsumedMessageIndex?: pulumi.Input<number | undefined>;
    roleSid?: pulumi.Input<string | undefined>;
    serviceSid: pulumi.Input<string>;
}
