// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ChatServicesChannelsMessagesV1 extends pulumi.CustomResource {
    /**
     * Get an existing ChatServicesChannelsMessagesV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ChatServicesChannelsMessagesV1State, opts?: pulumi.CustomResourceOptions): ChatServicesChannelsMessagesV1 {
        return new ChatServicesChannelsMessagesV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/chatServicesChannelsMessagesV1:ChatServicesChannelsMessagesV1';

    /**
     * Returns true if the given object is an instance of ChatServicesChannelsMessagesV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ChatServicesChannelsMessagesV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ChatServicesChannelsMessagesV1.__pulumiType;
    }

    declare public readonly attributes: pulumi.Output<string>;
    declare public readonly body: pulumi.Output<string>;
    declare public readonly channelSid: pulumi.Output<string>;
    declare public readonly from: pulumi.Output<string>;
    declare public readonly serviceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a ChatServicesChannelsMessagesV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ChatServicesChannelsMessagesV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ChatServicesChannelsMessagesV1Args | ChatServicesChannelsMessagesV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ChatServicesChannelsMessagesV1State | undefined;
            resourceInputs["attributes"] = state?.attributes;
            resourceInputs["body"] = state?.body;
            resourceInputs["channelSid"] = state?.channelSid;
            resourceInputs["from"] = state?.from;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as ChatServicesChannelsMessagesV1Args | undefined;
            if (args?.body === undefined && !opts.urn) {
                throw new Error("Missing required property 'body'");
            }
            if (args?.channelSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'channelSid'");
            }
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            resourceInputs["attributes"] = args?.attributes;
            resourceInputs["body"] = args?.body;
            resourceInputs["channelSid"] = args?.channelSid;
            resourceInputs["from"] = args?.from;
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ChatServicesChannelsMessagesV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ChatServicesChannelsMessagesV1 resources.
 */
export interface ChatServicesChannelsMessagesV1State {
    attributes?: pulumi.Input<string | undefined>;
    body?: pulumi.Input<string | undefined>;
    channelSid?: pulumi.Input<string | undefined>;
    from?: pulumi.Input<string | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ChatServicesChannelsMessagesV1 resource.
 */
export interface ChatServicesChannelsMessagesV1Args {
    attributes?: pulumi.Input<string | undefined>;
    body: pulumi.Input<string>;
    channelSid: pulumi.Input<string>;
    from?: pulumi.Input<string | undefined>;
    serviceSid: pulumi.Input<string>;
}
