// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ConversationsServicesV1 extends pulumi.CustomResource {
    /**
     * Get an existing ConversationsServicesV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConversationsServicesV1State, opts?: pulumi.CustomResourceOptions): ConversationsServicesV1 {
        return new ConversationsServicesV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/conversationsServicesV1:ConversationsServicesV1';

    /**
     * Returns true if the given object is an instance of ConversationsServicesV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConversationsServicesV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConversationsServicesV1.__pulumiType;
    }

    declare public readonly friendlyName: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a ConversationsServicesV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConversationsServicesV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConversationsServicesV1Args | ConversationsServicesV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConversationsServicesV1State | undefined;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as ConversationsServicesV1Args | undefined;
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ConversationsServicesV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ConversationsServicesV1 resources.
 */
export interface ConversationsServicesV1State {
    friendlyName?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ConversationsServicesV1 resource.
 */
export interface ConversationsServicesV1Args {
    friendlyName: pulumi.Input<string>;
}
