// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ConversationsConversationsMessagesV1 extends pulumi.CustomResource {
    /**
     * Get an existing ConversationsConversationsMessagesV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConversationsConversationsMessagesV1State, opts?: pulumi.CustomResourceOptions): ConversationsConversationsMessagesV1 {
        return new ConversationsConversationsMessagesV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/conversationsConversationsMessagesV1:ConversationsConversationsMessagesV1';

    /**
     * Returns true if the given object is an instance of ConversationsConversationsMessagesV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConversationsConversationsMessagesV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConversationsConversationsMessagesV1.__pulumiType;
    }

    declare public readonly attributes: pulumi.Output<string>;
    declare public readonly author: pulumi.Output<string>;
    declare public readonly body: pulumi.Output<string>;
    declare public readonly contentSid: pulumi.Output<string>;
    declare public readonly contentVariables: pulumi.Output<string>;
    declare public readonly conversationSid: pulumi.Output<string>;
    declare public readonly dateCreated: pulumi.Output<string>;
    declare public readonly dateUpdated: pulumi.Output<string>;
    declare public readonly mediaSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly subject: pulumi.Output<string>;
    declare public readonly xTwilioWebhookEnabled: pulumi.Output<string>;

    /**
     * Create a ConversationsConversationsMessagesV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConversationsConversationsMessagesV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConversationsConversationsMessagesV1Args | ConversationsConversationsMessagesV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConversationsConversationsMessagesV1State | undefined;
            resourceInputs["attributes"] = state?.attributes;
            resourceInputs["author"] = state?.author;
            resourceInputs["body"] = state?.body;
            resourceInputs["contentSid"] = state?.contentSid;
            resourceInputs["contentVariables"] = state?.contentVariables;
            resourceInputs["conversationSid"] = state?.conversationSid;
            resourceInputs["dateCreated"] = state?.dateCreated;
            resourceInputs["dateUpdated"] = state?.dateUpdated;
            resourceInputs["mediaSid"] = state?.mediaSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["subject"] = state?.subject;
            resourceInputs["xTwilioWebhookEnabled"] = state?.xTwilioWebhookEnabled;
        } else {
            const args = argsOrState as ConversationsConversationsMessagesV1Args | undefined;
            if (args?.conversationSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'conversationSid'");
            }
            resourceInputs["attributes"] = args?.attributes;
            resourceInputs["author"] = args?.author;
            resourceInputs["body"] = args?.body;
            resourceInputs["contentSid"] = args?.contentSid;
            resourceInputs["contentVariables"] = args?.contentVariables;
            resourceInputs["conversationSid"] = args?.conversationSid;
            resourceInputs["dateCreated"] = args?.dateCreated;
            resourceInputs["dateUpdated"] = args?.dateUpdated;
            resourceInputs["mediaSid"] = args?.mediaSid;
            resourceInputs["subject"] = args?.subject;
            resourceInputs["xTwilioWebhookEnabled"] = args?.xTwilioWebhookEnabled;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ConversationsConversationsMessagesV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ConversationsConversationsMessagesV1 resources.
 */
export interface ConversationsConversationsMessagesV1State {
    attributes?: pulumi.Input<string | undefined>;
    author?: pulumi.Input<string | undefined>;
    body?: pulumi.Input<string | undefined>;
    contentSid?: pulumi.Input<string | undefined>;
    contentVariables?: pulumi.Input<string | undefined>;
    conversationSid?: pulumi.Input<string | undefined>;
    dateCreated?: pulumi.Input<string | undefined>;
    dateUpdated?: pulumi.Input<string | undefined>;
    mediaSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    subject?: pulumi.Input<string | undefined>;
    xTwilioWebhookEnabled?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ConversationsConversationsMessagesV1 resource.
 */
export interface ConversationsConversationsMessagesV1Args {
    attributes?: pulumi.Input<string | undefined>;
    author?: pulumi.Input<string | undefined>;
    body?: pulumi.Input<string | undefined>;
    contentSid?: pulumi.Input<string | undefined>;
    contentVariables?: pulumi.Input<string | undefined>;
    conversationSid: pulumi.Input<string>;
    dateCreated?: pulumi.Input<string | undefined>;
    dateUpdated?: pulumi.Input<string | undefined>;
    mediaSid?: pulumi.Input<string | undefined>;
    subject?: pulumi.Input<string | undefined>;
    xTwilioWebhookEnabled?: pulumi.Input<string | undefined>;
}
