// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ConversationsServicesConversationsV1 extends pulumi.CustomResource {
    /**
     * Get an existing ConversationsServicesConversationsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConversationsServicesConversationsV1State, opts?: pulumi.CustomResourceOptions): ConversationsServicesConversationsV1 {
        return new ConversationsServicesConversationsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/conversationsServicesConversationsV1:ConversationsServicesConversationsV1';

    /**
     * Returns true if the given object is an instance of ConversationsServicesConversationsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConversationsServicesConversationsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConversationsServicesConversationsV1.__pulumiType;
    }

    declare public readonly attributes: pulumi.Output<string>;
    declare public readonly bindingsEmailAddress: pulumi.Output<string>;
    declare public readonly bindingsEmailName: pulumi.Output<string>;
    declare public readonly chatServiceSid: pulumi.Output<string>;
    declare public readonly dateCreated: pulumi.Output<string>;
    declare public readonly dateUpdated: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly messagingServiceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly state: pulumi.Output<string>;
    declare public readonly timersClosed: pulumi.Output<string>;
    declare public readonly timersInactive: pulumi.Output<string>;
    declare public readonly uniqueName: pulumi.Output<string>;
    declare public readonly xTwilioWebhookEnabled: pulumi.Output<string>;

    /**
     * Create a ConversationsServicesConversationsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConversationsServicesConversationsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConversationsServicesConversationsV1Args | ConversationsServicesConversationsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConversationsServicesConversationsV1State | undefined;
            resourceInputs["attributes"] = state?.attributes;
            resourceInputs["bindingsEmailAddress"] = state?.bindingsEmailAddress;
            resourceInputs["bindingsEmailName"] = state?.bindingsEmailName;
            resourceInputs["chatServiceSid"] = state?.chatServiceSid;
            resourceInputs["dateCreated"] = state?.dateCreated;
            resourceInputs["dateUpdated"] = state?.dateUpdated;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["messagingServiceSid"] = state?.messagingServiceSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["state"] = state?.state;
            resourceInputs["timersClosed"] = state?.timersClosed;
            resourceInputs["timersInactive"] = state?.timersInactive;
            resourceInputs["uniqueName"] = state?.uniqueName;
            resourceInputs["xTwilioWebhookEnabled"] = state?.xTwilioWebhookEnabled;
        } else {
            const args = argsOrState as ConversationsServicesConversationsV1Args | undefined;
            if (args?.chatServiceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'chatServiceSid'");
            }
            resourceInputs["attributes"] = args?.attributes;
            resourceInputs["bindingsEmailAddress"] = args?.bindingsEmailAddress;
            resourceInputs["bindingsEmailName"] = args?.bindingsEmailName;
            resourceInputs["chatServiceSid"] = args?.chatServiceSid;
            resourceInputs["dateCreated"] = args?.dateCreated;
            resourceInputs["dateUpdated"] = args?.dateUpdated;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["messagingServiceSid"] = args?.messagingServiceSid;
            resourceInputs["state"] = args?.state;
            resourceInputs["timersClosed"] = args?.timersClosed;
            resourceInputs["timersInactive"] = args?.timersInactive;
            resourceInputs["uniqueName"] = args?.uniqueName;
            resourceInputs["xTwilioWebhookEnabled"] = args?.xTwilioWebhookEnabled;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ConversationsServicesConversationsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ConversationsServicesConversationsV1 resources.
 */
export interface ConversationsServicesConversationsV1State {
    attributes?: pulumi.Input<string | undefined>;
    bindingsEmailAddress?: pulumi.Input<string | undefined>;
    bindingsEmailName?: pulumi.Input<string | undefined>;
    chatServiceSid?: pulumi.Input<string | undefined>;
    dateCreated?: pulumi.Input<string | undefined>;
    dateUpdated?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    messagingServiceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    state?: pulumi.Input<string | undefined>;
    timersClosed?: pulumi.Input<string | undefined>;
    timersInactive?: pulumi.Input<string | undefined>;
    uniqueName?: pulumi.Input<string | undefined>;
    xTwilioWebhookEnabled?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ConversationsServicesConversationsV1 resource.
 */
export interface ConversationsServicesConversationsV1Args {
    attributes?: pulumi.Input<string | undefined>;
    bindingsEmailAddress?: pulumi.Input<string | undefined>;
    bindingsEmailName?: pulumi.Input<string | undefined>;
    chatServiceSid: pulumi.Input<string>;
    dateCreated?: pulumi.Input<string | undefined>;
    dateUpdated?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    messagingServiceSid?: pulumi.Input<string | undefined>;
    state?: pulumi.Input<string | undefined>;
    timersClosed?: pulumi.Input<string | undefined>;
    timersInactive?: pulumi.Input<string | undefined>;
    uniqueName?: pulumi.Input<string | undefined>;
    xTwilioWebhookEnabled?: pulumi.Input<string | undefined>;
}
