// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ConversationsServicesConversationsWebhooksV1 extends pulumi.CustomResource {
    /**
     * Get an existing ConversationsServicesConversationsWebhooksV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConversationsServicesConversationsWebhooksV1State, opts?: pulumi.CustomResourceOptions): ConversationsServicesConversationsWebhooksV1 {
        return new ConversationsServicesConversationsWebhooksV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/conversationsServicesConversationsWebhooksV1:ConversationsServicesConversationsWebhooksV1';

    /**
     * Returns true if the given object is an instance of ConversationsServicesConversationsWebhooksV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConversationsServicesConversationsWebhooksV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConversationsServicesConversationsWebhooksV1.__pulumiType;
    }

    declare public readonly chatServiceSid: pulumi.Output<string>;
    declare public readonly configurationFilters: pulumi.Output<string[]>;
    declare public readonly configurationFlowSid: pulumi.Output<string>;
    declare public readonly configurationMethod: pulumi.Output<string>;
    declare public readonly configurationReplayAfter: pulumi.Output<number>;
    declare public readonly configurationTriggers: pulumi.Output<string[]>;
    declare public readonly configurationUrl: pulumi.Output<string>;
    declare public readonly conversationSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly target: pulumi.Output<string>;

    /**
     * Create a ConversationsServicesConversationsWebhooksV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConversationsServicesConversationsWebhooksV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConversationsServicesConversationsWebhooksV1Args | ConversationsServicesConversationsWebhooksV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConversationsServicesConversationsWebhooksV1State | undefined;
            resourceInputs["chatServiceSid"] = state?.chatServiceSid;
            resourceInputs["configurationFilters"] = state?.configurationFilters;
            resourceInputs["configurationFlowSid"] = state?.configurationFlowSid;
            resourceInputs["configurationMethod"] = state?.configurationMethod;
            resourceInputs["configurationReplayAfter"] = state?.configurationReplayAfter;
            resourceInputs["configurationTriggers"] = state?.configurationTriggers;
            resourceInputs["configurationUrl"] = state?.configurationUrl;
            resourceInputs["conversationSid"] = state?.conversationSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["target"] = state?.target;
        } else {
            const args = argsOrState as ConversationsServicesConversationsWebhooksV1Args | undefined;
            if (args?.chatServiceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'chatServiceSid'");
            }
            if (args?.conversationSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'conversationSid'");
            }
            if (args?.target === undefined && !opts.urn) {
                throw new Error("Missing required property 'target'");
            }
            resourceInputs["chatServiceSid"] = args?.chatServiceSid;
            resourceInputs["configurationFilters"] = args?.configurationFilters;
            resourceInputs["configurationFlowSid"] = args?.configurationFlowSid;
            resourceInputs["configurationMethod"] = args?.configurationMethod;
            resourceInputs["configurationReplayAfter"] = args?.configurationReplayAfter;
            resourceInputs["configurationTriggers"] = args?.configurationTriggers;
            resourceInputs["configurationUrl"] = args?.configurationUrl;
            resourceInputs["conversationSid"] = args?.conversationSid;
            resourceInputs["target"] = args?.target;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ConversationsServicesConversationsWebhooksV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ConversationsServicesConversationsWebhooksV1 resources.
 */
export interface ConversationsServicesConversationsWebhooksV1State {
    chatServiceSid?: pulumi.Input<string | undefined>;
    configurationFilters?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    configurationFlowSid?: pulumi.Input<string | undefined>;
    configurationMethod?: pulumi.Input<string | undefined>;
    configurationReplayAfter?: pulumi.Input<number | undefined>;
    configurationTriggers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    configurationUrl?: pulumi.Input<string | undefined>;
    conversationSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    target?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ConversationsServicesConversationsWebhooksV1 resource.
 */
export interface ConversationsServicesConversationsWebhooksV1Args {
    chatServiceSid: pulumi.Input<string>;
    configurationFilters?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    configurationFlowSid?: pulumi.Input<string | undefined>;
    configurationMethod?: pulumi.Input<string | undefined>;
    configurationReplayAfter?: pulumi.Input<number | undefined>;
    configurationTriggers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    configurationUrl?: pulumi.Input<string | undefined>;
    conversationSid: pulumi.Input<string>;
    target: pulumi.Input<string>;
}
