// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class EventsSubscriptionsV1 extends pulumi.CustomResource {
    /**
     * Get an existing EventsSubscriptionsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EventsSubscriptionsV1State, opts?: pulumi.CustomResourceOptions): EventsSubscriptionsV1 {
        return new EventsSubscriptionsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/eventsSubscriptionsV1:EventsSubscriptionsV1';

    /**
     * Returns true if the given object is an instance of EventsSubscriptionsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EventsSubscriptionsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EventsSubscriptionsV1.__pulumiType;
    }

    declare public readonly description: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly sinkSid: pulumi.Output<string>;
    declare public readonly types: pulumi.Output<string[]>;

    /**
     * Create a EventsSubscriptionsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EventsSubscriptionsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EventsSubscriptionsV1Args | EventsSubscriptionsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EventsSubscriptionsV1State | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["sinkSid"] = state?.sinkSid;
            resourceInputs["types"] = state?.types;
        } else {
            const args = argsOrState as EventsSubscriptionsV1Args | undefined;
            if (args?.description === undefined && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            if (args?.sinkSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'sinkSid'");
            }
            if (args?.types === undefined && !opts.urn) {
                throw new Error("Missing required property 'types'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["sinkSid"] = args?.sinkSid;
            resourceInputs["types"] = args?.types;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EventsSubscriptionsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EventsSubscriptionsV1 resources.
 */
export interface EventsSubscriptionsV1State {
    description?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    sinkSid?: pulumi.Input<string | undefined>;
    types?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a EventsSubscriptionsV1 resource.
 */
export interface EventsSubscriptionsV1Args {
    description: pulumi.Input<string>;
    sinkSid: pulumi.Input<string>;
    types: pulumi.Input<pulumi.Input<string>[]>;
}
