// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class EventsSubscriptionsSubscribedEventsV1 extends pulumi.CustomResource {
    /**
     * Get an existing EventsSubscriptionsSubscribedEventsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EventsSubscriptionsSubscribedEventsV1State, opts?: pulumi.CustomResourceOptions): EventsSubscriptionsSubscribedEventsV1 {
        return new EventsSubscriptionsSubscribedEventsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/eventsSubscriptionsSubscribedEventsV1:EventsSubscriptionsSubscribedEventsV1';

    /**
     * Returns true if the given object is an instance of EventsSubscriptionsSubscribedEventsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EventsSubscriptionsSubscribedEventsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EventsSubscriptionsSubscribedEventsV1.__pulumiType;
    }

    declare public readonly schemaVersion: pulumi.Output<number>;
    declare public readonly subscriptionSid: pulumi.Output<string>;
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a EventsSubscriptionsSubscribedEventsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EventsSubscriptionsSubscribedEventsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EventsSubscriptionsSubscribedEventsV1Args | EventsSubscriptionsSubscribedEventsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EventsSubscriptionsSubscribedEventsV1State | undefined;
            resourceInputs["schemaVersion"] = state?.schemaVersion;
            resourceInputs["subscriptionSid"] = state?.subscriptionSid;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as EventsSubscriptionsSubscribedEventsV1Args | undefined;
            if (args?.subscriptionSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'subscriptionSid'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["schemaVersion"] = args?.schemaVersion;
            resourceInputs["subscriptionSid"] = args?.subscriptionSid;
            resourceInputs["type"] = args?.type;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EventsSubscriptionsSubscribedEventsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EventsSubscriptionsSubscribedEventsV1 resources.
 */
export interface EventsSubscriptionsSubscribedEventsV1State {
    schemaVersion?: pulumi.Input<number | undefined>;
    subscriptionSid?: pulumi.Input<string | undefined>;
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a EventsSubscriptionsSubscribedEventsV1 resource.
 */
export interface EventsSubscriptionsSubscribedEventsV1Args {
    schemaVersion?: pulumi.Input<number | undefined>;
    subscriptionSid: pulumi.Input<string>;
    type: pulumi.Input<string>;
}
