// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class FlexFlexFlowsV1 extends pulumi.CustomResource {
    /**
     * Get an existing FlexFlexFlowsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FlexFlexFlowsV1State, opts?: pulumi.CustomResourceOptions): FlexFlexFlowsV1 {
        return new FlexFlexFlowsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/flexFlexFlowsV1:FlexFlexFlowsV1';

    /**
     * Returns true if the given object is an instance of FlexFlexFlowsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FlexFlexFlowsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FlexFlexFlowsV1.__pulumiType;
    }

    declare public readonly channelType: pulumi.Output<string>;
    declare public readonly chatServiceSid: pulumi.Output<string>;
    declare public readonly contactIdentity: pulumi.Output<string>;
    declare public readonly enabled: pulumi.Output<boolean>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly integrationChannel: pulumi.Output<string>;
    declare public readonly integrationCreationOnMessage: pulumi.Output<boolean>;
    declare public readonly integrationFlowSid: pulumi.Output<string>;
    declare public readonly integrationPriority: pulumi.Output<number>;
    declare public readonly integrationRetryCount: pulumi.Output<number>;
    declare public readonly integrationTimeout: pulumi.Output<number>;
    declare public readonly integrationType: pulumi.Output<string>;
    declare public readonly integrationUrl: pulumi.Output<string>;
    declare public readonly integrationWorkflowSid: pulumi.Output<string>;
    declare public readonly integrationWorkspaceSid: pulumi.Output<string>;
    declare public readonly janitorEnabled: pulumi.Output<boolean>;
    declare public readonly longLived: pulumi.Output<boolean>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a FlexFlexFlowsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FlexFlexFlowsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FlexFlexFlowsV1Args | FlexFlexFlowsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FlexFlexFlowsV1State | undefined;
            resourceInputs["channelType"] = state?.channelType;
            resourceInputs["chatServiceSid"] = state?.chatServiceSid;
            resourceInputs["contactIdentity"] = state?.contactIdentity;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["integrationChannel"] = state?.integrationChannel;
            resourceInputs["integrationCreationOnMessage"] = state?.integrationCreationOnMessage;
            resourceInputs["integrationFlowSid"] = state?.integrationFlowSid;
            resourceInputs["integrationPriority"] = state?.integrationPriority;
            resourceInputs["integrationRetryCount"] = state?.integrationRetryCount;
            resourceInputs["integrationTimeout"] = state?.integrationTimeout;
            resourceInputs["integrationType"] = state?.integrationType;
            resourceInputs["integrationUrl"] = state?.integrationUrl;
            resourceInputs["integrationWorkflowSid"] = state?.integrationWorkflowSid;
            resourceInputs["integrationWorkspaceSid"] = state?.integrationWorkspaceSid;
            resourceInputs["janitorEnabled"] = state?.janitorEnabled;
            resourceInputs["longLived"] = state?.longLived;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as FlexFlexFlowsV1Args | undefined;
            if (args?.channelType === undefined && !opts.urn) {
                throw new Error("Missing required property 'channelType'");
            }
            if (args?.chatServiceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'chatServiceSid'");
            }
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            resourceInputs["channelType"] = args?.channelType;
            resourceInputs["chatServiceSid"] = args?.chatServiceSid;
            resourceInputs["contactIdentity"] = args?.contactIdentity;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["integrationChannel"] = args?.integrationChannel;
            resourceInputs["integrationCreationOnMessage"] = args?.integrationCreationOnMessage;
            resourceInputs["integrationFlowSid"] = args?.integrationFlowSid;
            resourceInputs["integrationPriority"] = args?.integrationPriority;
            resourceInputs["integrationRetryCount"] = args?.integrationRetryCount;
            resourceInputs["integrationTimeout"] = args?.integrationTimeout;
            resourceInputs["integrationType"] = args?.integrationType;
            resourceInputs["integrationUrl"] = args?.integrationUrl;
            resourceInputs["integrationWorkflowSid"] = args?.integrationWorkflowSid;
            resourceInputs["integrationWorkspaceSid"] = args?.integrationWorkspaceSid;
            resourceInputs["janitorEnabled"] = args?.janitorEnabled;
            resourceInputs["longLived"] = args?.longLived;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FlexFlexFlowsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FlexFlexFlowsV1 resources.
 */
export interface FlexFlexFlowsV1State {
    channelType?: pulumi.Input<string | undefined>;
    chatServiceSid?: pulumi.Input<string | undefined>;
    contactIdentity?: pulumi.Input<string | undefined>;
    enabled?: pulumi.Input<boolean | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    integrationChannel?: pulumi.Input<string | undefined>;
    integrationCreationOnMessage?: pulumi.Input<boolean | undefined>;
    integrationFlowSid?: pulumi.Input<string | undefined>;
    integrationPriority?: pulumi.Input<number | undefined>;
    integrationRetryCount?: pulumi.Input<number | undefined>;
    integrationTimeout?: pulumi.Input<number | undefined>;
    integrationType?: pulumi.Input<string | undefined>;
    integrationUrl?: pulumi.Input<string | undefined>;
    integrationWorkflowSid?: pulumi.Input<string | undefined>;
    integrationWorkspaceSid?: pulumi.Input<string | undefined>;
    janitorEnabled?: pulumi.Input<boolean | undefined>;
    longLived?: pulumi.Input<boolean | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a FlexFlexFlowsV1 resource.
 */
export interface FlexFlexFlowsV1Args {
    channelType: pulumi.Input<string>;
    chatServiceSid: pulumi.Input<string>;
    contactIdentity?: pulumi.Input<string | undefined>;
    enabled?: pulumi.Input<boolean | undefined>;
    friendlyName: pulumi.Input<string>;
    integrationChannel?: pulumi.Input<string | undefined>;
    integrationCreationOnMessage?: pulumi.Input<boolean | undefined>;
    integrationFlowSid?: pulumi.Input<string | undefined>;
    integrationPriority?: pulumi.Input<number | undefined>;
    integrationRetryCount?: pulumi.Input<number | undefined>;
    integrationTimeout?: pulumi.Input<number | undefined>;
    integrationType?: pulumi.Input<string | undefined>;
    integrationUrl?: pulumi.Input<string | undefined>;
    integrationWorkflowSid?: pulumi.Input<string | undefined>;
    integrationWorkspaceSid?: pulumi.Input<string | undefined>;
    janitorEnabled?: pulumi.Input<boolean | undefined>;
    longLived?: pulumi.Input<boolean | undefined>;
}
