// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class FlexInsightsQualityManagementQuestionnairesV1 extends pulumi.CustomResource {
    /**
     * Get an existing FlexInsightsQualityManagementQuestionnairesV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FlexInsightsQualityManagementQuestionnairesV1State, opts?: pulumi.CustomResourceOptions): FlexInsightsQualityManagementQuestionnairesV1 {
        return new FlexInsightsQualityManagementQuestionnairesV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/flexInsightsQualityManagementQuestionnairesV1:FlexInsightsQualityManagementQuestionnairesV1';

    /**
     * Returns true if the given object is an instance of FlexInsightsQualityManagementQuestionnairesV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FlexInsightsQualityManagementQuestionnairesV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FlexInsightsQualityManagementQuestionnairesV1.__pulumiType;
    }

    declare public readonly active: pulumi.Output<boolean>;
    declare public readonly authorization: pulumi.Output<string>;
    declare public readonly description: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly questionSids: pulumi.Output<string[]>;
    declare public /*out*/ readonly questionnaireSid: pulumi.Output<string>;

    /**
     * Create a FlexInsightsQualityManagementQuestionnairesV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: FlexInsightsQualityManagementQuestionnairesV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FlexInsightsQualityManagementQuestionnairesV1Args | FlexInsightsQualityManagementQuestionnairesV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FlexInsightsQualityManagementQuestionnairesV1State | undefined;
            resourceInputs["active"] = state?.active;
            resourceInputs["authorization"] = state?.authorization;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["questionSids"] = state?.questionSids;
            resourceInputs["questionnaireSid"] = state?.questionnaireSid;
        } else {
            const args = argsOrState as FlexInsightsQualityManagementQuestionnairesV1Args | undefined;
            resourceInputs["active"] = args?.active;
            resourceInputs["authorization"] = args?.authorization;
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["questionSids"] = args?.questionSids;
            resourceInputs["questionnaireSid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FlexInsightsQualityManagementQuestionnairesV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FlexInsightsQualityManagementQuestionnairesV1 resources.
 */
export interface FlexInsightsQualityManagementQuestionnairesV1State {
    active?: pulumi.Input<boolean | undefined>;
    authorization?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    questionSids?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    questionnaireSid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a FlexInsightsQualityManagementQuestionnairesV1 resource.
 */
export interface FlexInsightsQualityManagementQuestionnairesV1Args {
    active?: pulumi.Input<boolean | undefined>;
    authorization?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    questionSids?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
