// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class FlexWebChannelsV1 extends pulumi.CustomResource {
    /**
     * Get an existing FlexWebChannelsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FlexWebChannelsV1State, opts?: pulumi.CustomResourceOptions): FlexWebChannelsV1 {
        return new FlexWebChannelsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/flexWebChannelsV1:FlexWebChannelsV1';

    /**
     * Returns true if the given object is an instance of FlexWebChannelsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FlexWebChannelsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FlexWebChannelsV1.__pulumiType;
    }

    declare public readonly chatFriendlyName: pulumi.Output<string>;
    declare public readonly chatStatus: pulumi.Output<string>;
    declare public readonly chatUniqueName: pulumi.Output<string>;
    declare public readonly customerFriendlyName: pulumi.Output<string>;
    declare public readonly flexFlowSid: pulumi.Output<string>;
    declare public readonly identity: pulumi.Output<string>;
    declare public readonly postEngagementData: pulumi.Output<string>;
    declare public readonly preEngagementData: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a FlexWebChannelsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FlexWebChannelsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FlexWebChannelsV1Args | FlexWebChannelsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FlexWebChannelsV1State | undefined;
            resourceInputs["chatFriendlyName"] = state?.chatFriendlyName;
            resourceInputs["chatStatus"] = state?.chatStatus;
            resourceInputs["chatUniqueName"] = state?.chatUniqueName;
            resourceInputs["customerFriendlyName"] = state?.customerFriendlyName;
            resourceInputs["flexFlowSid"] = state?.flexFlowSid;
            resourceInputs["identity"] = state?.identity;
            resourceInputs["postEngagementData"] = state?.postEngagementData;
            resourceInputs["preEngagementData"] = state?.preEngagementData;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as FlexWebChannelsV1Args | undefined;
            if (args?.chatFriendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'chatFriendlyName'");
            }
            if (args?.customerFriendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'customerFriendlyName'");
            }
            if (args?.flexFlowSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'flexFlowSid'");
            }
            if (args?.identity === undefined && !opts.urn) {
                throw new Error("Missing required property 'identity'");
            }
            resourceInputs["chatFriendlyName"] = args?.chatFriendlyName;
            resourceInputs["chatStatus"] = args?.chatStatus;
            resourceInputs["chatUniqueName"] = args?.chatUniqueName;
            resourceInputs["customerFriendlyName"] = args?.customerFriendlyName;
            resourceInputs["flexFlowSid"] = args?.flexFlowSid;
            resourceInputs["identity"] = args?.identity;
            resourceInputs["postEngagementData"] = args?.postEngagementData;
            resourceInputs["preEngagementData"] = args?.preEngagementData;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FlexWebChannelsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FlexWebChannelsV1 resources.
 */
export interface FlexWebChannelsV1State {
    chatFriendlyName?: pulumi.Input<string | undefined>;
    chatStatus?: pulumi.Input<string | undefined>;
    chatUniqueName?: pulumi.Input<string | undefined>;
    customerFriendlyName?: pulumi.Input<string | undefined>;
    flexFlowSid?: pulumi.Input<string | undefined>;
    identity?: pulumi.Input<string | undefined>;
    postEngagementData?: pulumi.Input<string | undefined>;
    preEngagementData?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a FlexWebChannelsV1 resource.
 */
export interface FlexWebChannelsV1Args {
    chatFriendlyName: pulumi.Input<string>;
    chatStatus?: pulumi.Input<string | undefined>;
    chatUniqueName?: pulumi.Input<string | undefined>;
    customerFriendlyName: pulumi.Input<string>;
    flexFlowSid: pulumi.Input<string>;
    identity: pulumi.Input<string>;
    postEngagementData?: pulumi.Input<string | undefined>;
    preEngagementData?: pulumi.Input<string | undefined>;
}
