// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class FlexChannelsV1 extends pulumi.CustomResource {
    /**
     * Get an existing FlexChannelsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FlexChannelsV1State, opts?: pulumi.CustomResourceOptions): FlexChannelsV1 {
        return new FlexChannelsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/flexChannelsV1:FlexChannelsV1';

    /**
     * Returns true if the given object is an instance of FlexChannelsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FlexChannelsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FlexChannelsV1.__pulumiType;
    }

    declare public readonly chatFriendlyName: pulumi.Output<string>;
    declare public readonly chatUniqueName: pulumi.Output<string>;
    declare public readonly chatUserFriendlyName: pulumi.Output<string>;
    declare public readonly flexFlowSid: pulumi.Output<string>;
    declare public readonly identity: pulumi.Output<string>;
    declare public readonly longLived: pulumi.Output<boolean>;
    declare public readonly preEngagementData: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly target: pulumi.Output<string>;
    declare public readonly taskAttributes: pulumi.Output<string>;
    declare public readonly taskSid: pulumi.Output<string>;

    /**
     * Create a FlexChannelsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FlexChannelsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FlexChannelsV1Args | FlexChannelsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FlexChannelsV1State | undefined;
            resourceInputs["chatFriendlyName"] = state?.chatFriendlyName;
            resourceInputs["chatUniqueName"] = state?.chatUniqueName;
            resourceInputs["chatUserFriendlyName"] = state?.chatUserFriendlyName;
            resourceInputs["flexFlowSid"] = state?.flexFlowSid;
            resourceInputs["identity"] = state?.identity;
            resourceInputs["longLived"] = state?.longLived;
            resourceInputs["preEngagementData"] = state?.preEngagementData;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["target"] = state?.target;
            resourceInputs["taskAttributes"] = state?.taskAttributes;
            resourceInputs["taskSid"] = state?.taskSid;
        } else {
            const args = argsOrState as FlexChannelsV1Args | undefined;
            if (args?.chatFriendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'chatFriendlyName'");
            }
            if (args?.chatUserFriendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'chatUserFriendlyName'");
            }
            if (args?.flexFlowSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'flexFlowSid'");
            }
            if (args?.identity === undefined && !opts.urn) {
                throw new Error("Missing required property 'identity'");
            }
            resourceInputs["chatFriendlyName"] = args?.chatFriendlyName;
            resourceInputs["chatUniqueName"] = args?.chatUniqueName;
            resourceInputs["chatUserFriendlyName"] = args?.chatUserFriendlyName;
            resourceInputs["flexFlowSid"] = args?.flexFlowSid;
            resourceInputs["identity"] = args?.identity;
            resourceInputs["longLived"] = args?.longLived;
            resourceInputs["preEngagementData"] = args?.preEngagementData;
            resourceInputs["target"] = args?.target;
            resourceInputs["taskAttributes"] = args?.taskAttributes;
            resourceInputs["taskSid"] = args?.taskSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FlexChannelsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FlexChannelsV1 resources.
 */
export interface FlexChannelsV1State {
    chatFriendlyName?: pulumi.Input<string | undefined>;
    chatUniqueName?: pulumi.Input<string | undefined>;
    chatUserFriendlyName?: pulumi.Input<string | undefined>;
    flexFlowSid?: pulumi.Input<string | undefined>;
    identity?: pulumi.Input<string | undefined>;
    longLived?: pulumi.Input<boolean | undefined>;
    preEngagementData?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    target?: pulumi.Input<string | undefined>;
    taskAttributes?: pulumi.Input<string | undefined>;
    taskSid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a FlexChannelsV1 resource.
 */
export interface FlexChannelsV1Args {
    chatFriendlyName: pulumi.Input<string>;
    chatUniqueName?: pulumi.Input<string | undefined>;
    chatUserFriendlyName: pulumi.Input<string>;
    flexFlowSid: pulumi.Input<string>;
    identity: pulumi.Input<string>;
    longLived?: pulumi.Input<boolean | undefined>;
    preEngagementData?: pulumi.Input<string | undefined>;
    target?: pulumi.Input<string | undefined>;
    taskAttributes?: pulumi.Input<string | undefined>;
    taskSid?: pulumi.Input<string | undefined>;
}
