// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IntelligenceOperatorsCustomV2 extends pulumi.CustomResource {
    /**
     * Get an existing IntelligenceOperatorsCustomV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntelligenceOperatorsCustomV2State, opts?: pulumi.CustomResourceOptions): IntelligenceOperatorsCustomV2 {
        return new IntelligenceOperatorsCustomV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/intelligenceOperatorsCustomV2:IntelligenceOperatorsCustomV2';

    /**
     * Returns true if the given object is an instance of IntelligenceOperatorsCustomV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntelligenceOperatorsCustomV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntelligenceOperatorsCustomV2.__pulumiType;
    }

    declare public readonly config: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly ifMatch: pulumi.Output<string>;
    declare public readonly operatorType: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a IntelligenceOperatorsCustomV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntelligenceOperatorsCustomV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntelligenceOperatorsCustomV2Args | IntelligenceOperatorsCustomV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntelligenceOperatorsCustomV2State | undefined;
            resourceInputs["config"] = state?.config;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["ifMatch"] = state?.ifMatch;
            resourceInputs["operatorType"] = state?.operatorType;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as IntelligenceOperatorsCustomV2Args | undefined;
            if (args?.config === undefined && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            if (args?.operatorType === undefined && !opts.urn) {
                throw new Error("Missing required property 'operatorType'");
            }
            resourceInputs["config"] = args?.config;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["ifMatch"] = args?.ifMatch;
            resourceInputs["operatorType"] = args?.operatorType;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntelligenceOperatorsCustomV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntelligenceOperatorsCustomV2 resources.
 */
export interface IntelligenceOperatorsCustomV2State {
    config?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    ifMatch?: pulumi.Input<string | undefined>;
    operatorType?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntelligenceOperatorsCustomV2 resource.
 */
export interface IntelligenceOperatorsCustomV2Args {
    config: pulumi.Input<string>;
    friendlyName: pulumi.Input<string>;
    ifMatch?: pulumi.Input<string | undefined>;
    operatorType: pulumi.Input<string>;
}
