// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IpMessagingServicesChannelsV1 extends pulumi.CustomResource {
    /**
     * Get an existing IpMessagingServicesChannelsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IpMessagingServicesChannelsV1State, opts?: pulumi.CustomResourceOptions): IpMessagingServicesChannelsV1 {
        return new IpMessagingServicesChannelsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/ipMessagingServicesChannelsV1:IpMessagingServicesChannelsV1';

    /**
     * Returns true if the given object is an instance of IpMessagingServicesChannelsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IpMessagingServicesChannelsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IpMessagingServicesChannelsV1.__pulumiType;
    }

    declare public readonly attributes: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly serviceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly type: pulumi.Output<string>;
    declare public readonly uniqueName: pulumi.Output<string>;

    /**
     * Create a IpMessagingServicesChannelsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IpMessagingServicesChannelsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IpMessagingServicesChannelsV1Args | IpMessagingServicesChannelsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IpMessagingServicesChannelsV1State | undefined;
            resourceInputs["attributes"] = state?.attributes;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["type"] = state?.type;
            resourceInputs["uniqueName"] = state?.uniqueName;
        } else {
            const args = argsOrState as IpMessagingServicesChannelsV1Args | undefined;
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            resourceInputs["attributes"] = args?.attributes;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["type"] = args?.type;
            resourceInputs["uniqueName"] = args?.uniqueName;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IpMessagingServicesChannelsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IpMessagingServicesChannelsV1 resources.
 */
export interface IpMessagingServicesChannelsV1State {
    attributes?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    type?: pulumi.Input<string | undefined>;
    uniqueName?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IpMessagingServicesChannelsV1 resource.
 */
export interface IpMessagingServicesChannelsV1Args {
    attributes?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    serviceSid: pulumi.Input<string>;
    type?: pulumi.Input<string | undefined>;
    uniqueName?: pulumi.Input<string | undefined>;
}
