// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IpMessagingServicesRolesV2 extends pulumi.CustomResource {
    /**
     * Get an existing IpMessagingServicesRolesV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IpMessagingServicesRolesV2State, opts?: pulumi.CustomResourceOptions): IpMessagingServicesRolesV2 {
        return new IpMessagingServicesRolesV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/ipMessagingServicesRolesV2:IpMessagingServicesRolesV2';

    /**
     * Returns true if the given object is an instance of IpMessagingServicesRolesV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IpMessagingServicesRolesV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IpMessagingServicesRolesV2.__pulumiType;
    }

    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly permissions: pulumi.Output<string[]>;
    declare public readonly serviceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a IpMessagingServicesRolesV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IpMessagingServicesRolesV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IpMessagingServicesRolesV2Args | IpMessagingServicesRolesV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IpMessagingServicesRolesV2State | undefined;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["permissions"] = state?.permissions;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as IpMessagingServicesRolesV2Args | undefined;
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            if (args?.permissions === undefined && !opts.urn) {
                throw new Error("Missing required property 'permissions'");
            }
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["permissions"] = args?.permissions;
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["type"] = args?.type;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IpMessagingServicesRolesV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IpMessagingServicesRolesV2 resources.
 */
export interface IpMessagingServicesRolesV2State {
    friendlyName?: pulumi.Input<string | undefined>;
    permissions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IpMessagingServicesRolesV2 resource.
 */
export interface IpMessagingServicesRolesV2Args {
    friendlyName: pulumi.Input<string>;
    permissions: pulumi.Input<pulumi.Input<string>[]>;
    serviceSid: pulumi.Input<string>;
    type: pulumi.Input<string>;
}
