// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IpMessagingServicesChannelsWebhooksV2 extends pulumi.CustomResource {
    /**
     * Get an existing IpMessagingServicesChannelsWebhooksV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IpMessagingServicesChannelsWebhooksV2State, opts?: pulumi.CustomResourceOptions): IpMessagingServicesChannelsWebhooksV2 {
        return new IpMessagingServicesChannelsWebhooksV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/ipMessagingServicesChannelsWebhooksV2:IpMessagingServicesChannelsWebhooksV2';

    /**
     * Returns true if the given object is an instance of IpMessagingServicesChannelsWebhooksV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IpMessagingServicesChannelsWebhooksV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IpMessagingServicesChannelsWebhooksV2.__pulumiType;
    }

    declare public readonly channelSid: pulumi.Output<string>;
    declare public readonly configurationFilters: pulumi.Output<string[]>;
    declare public readonly configurationFlowSid: pulumi.Output<string>;
    declare public readonly configurationMethod: pulumi.Output<string>;
    declare public readonly configurationRetryCount: pulumi.Output<number>;
    declare public readonly configurationTriggers: pulumi.Output<string[]>;
    declare public readonly configurationUrl: pulumi.Output<string>;
    declare public readonly serviceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a IpMessagingServicesChannelsWebhooksV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IpMessagingServicesChannelsWebhooksV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IpMessagingServicesChannelsWebhooksV2Args | IpMessagingServicesChannelsWebhooksV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IpMessagingServicesChannelsWebhooksV2State | undefined;
            resourceInputs["channelSid"] = state?.channelSid;
            resourceInputs["configurationFilters"] = state?.configurationFilters;
            resourceInputs["configurationFlowSid"] = state?.configurationFlowSid;
            resourceInputs["configurationMethod"] = state?.configurationMethod;
            resourceInputs["configurationRetryCount"] = state?.configurationRetryCount;
            resourceInputs["configurationTriggers"] = state?.configurationTriggers;
            resourceInputs["configurationUrl"] = state?.configurationUrl;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as IpMessagingServicesChannelsWebhooksV2Args | undefined;
            if (args?.channelSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'channelSid'");
            }
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["channelSid"] = args?.channelSid;
            resourceInputs["configurationFilters"] = args?.configurationFilters;
            resourceInputs["configurationFlowSid"] = args?.configurationFlowSid;
            resourceInputs["configurationMethod"] = args?.configurationMethod;
            resourceInputs["configurationRetryCount"] = args?.configurationRetryCount;
            resourceInputs["configurationTriggers"] = args?.configurationTriggers;
            resourceInputs["configurationUrl"] = args?.configurationUrl;
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["type"] = args?.type;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IpMessagingServicesChannelsWebhooksV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IpMessagingServicesChannelsWebhooksV2 resources.
 */
export interface IpMessagingServicesChannelsWebhooksV2State {
    channelSid?: pulumi.Input<string | undefined>;
    configurationFilters?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    configurationFlowSid?: pulumi.Input<string | undefined>;
    configurationMethod?: pulumi.Input<string | undefined>;
    configurationRetryCount?: pulumi.Input<number | undefined>;
    configurationTriggers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    configurationUrl?: pulumi.Input<string | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IpMessagingServicesChannelsWebhooksV2 resource.
 */
export interface IpMessagingServicesChannelsWebhooksV2Args {
    channelSid: pulumi.Input<string>;
    configurationFilters?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    configurationFlowSid?: pulumi.Input<string | undefined>;
    configurationMethod?: pulumi.Input<string | undefined>;
    configurationRetryCount?: pulumi.Input<number | undefined>;
    configurationTriggers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    configurationUrl?: pulumi.Input<string | undefined>;
    serviceSid: pulumi.Input<string>;
    type: pulumi.Input<string>;
}
