// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IpMessagingServicesChannelsMessagesV2 extends pulumi.CustomResource {
    /**
     * Get an existing IpMessagingServicesChannelsMessagesV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IpMessagingServicesChannelsMessagesV2State, opts?: pulumi.CustomResourceOptions): IpMessagingServicesChannelsMessagesV2 {
        return new IpMessagingServicesChannelsMessagesV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/ipMessagingServicesChannelsMessagesV2:IpMessagingServicesChannelsMessagesV2';

    /**
     * Returns true if the given object is an instance of IpMessagingServicesChannelsMessagesV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IpMessagingServicesChannelsMessagesV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IpMessagingServicesChannelsMessagesV2.__pulumiType;
    }

    declare public readonly attributes: pulumi.Output<string>;
    declare public readonly body: pulumi.Output<string>;
    declare public readonly channelSid: pulumi.Output<string>;
    declare public readonly dateCreated: pulumi.Output<string>;
    declare public readonly dateUpdated: pulumi.Output<string>;
    declare public readonly from: pulumi.Output<string>;
    declare public readonly lastUpdatedBy: pulumi.Output<string>;
    declare public readonly mediaSid: pulumi.Output<string>;
    declare public readonly serviceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly xTwilioWebhookEnabled: pulumi.Output<string>;

    /**
     * Create a IpMessagingServicesChannelsMessagesV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IpMessagingServicesChannelsMessagesV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IpMessagingServicesChannelsMessagesV2Args | IpMessagingServicesChannelsMessagesV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IpMessagingServicesChannelsMessagesV2State | undefined;
            resourceInputs["attributes"] = state?.attributes;
            resourceInputs["body"] = state?.body;
            resourceInputs["channelSid"] = state?.channelSid;
            resourceInputs["dateCreated"] = state?.dateCreated;
            resourceInputs["dateUpdated"] = state?.dateUpdated;
            resourceInputs["from"] = state?.from;
            resourceInputs["lastUpdatedBy"] = state?.lastUpdatedBy;
            resourceInputs["mediaSid"] = state?.mediaSid;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["xTwilioWebhookEnabled"] = state?.xTwilioWebhookEnabled;
        } else {
            const args = argsOrState as IpMessagingServicesChannelsMessagesV2Args | undefined;
            if (args?.channelSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'channelSid'");
            }
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            resourceInputs["attributes"] = args?.attributes;
            resourceInputs["body"] = args?.body;
            resourceInputs["channelSid"] = args?.channelSid;
            resourceInputs["dateCreated"] = args?.dateCreated;
            resourceInputs["dateUpdated"] = args?.dateUpdated;
            resourceInputs["from"] = args?.from;
            resourceInputs["lastUpdatedBy"] = args?.lastUpdatedBy;
            resourceInputs["mediaSid"] = args?.mediaSid;
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["xTwilioWebhookEnabled"] = args?.xTwilioWebhookEnabled;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IpMessagingServicesChannelsMessagesV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IpMessagingServicesChannelsMessagesV2 resources.
 */
export interface IpMessagingServicesChannelsMessagesV2State {
    attributes?: pulumi.Input<string | undefined>;
    body?: pulumi.Input<string | undefined>;
    channelSid?: pulumi.Input<string | undefined>;
    dateCreated?: pulumi.Input<string | undefined>;
    dateUpdated?: pulumi.Input<string | undefined>;
    from?: pulumi.Input<string | undefined>;
    lastUpdatedBy?: pulumi.Input<string | undefined>;
    mediaSid?: pulumi.Input<string | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    xTwilioWebhookEnabled?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IpMessagingServicesChannelsMessagesV2 resource.
 */
export interface IpMessagingServicesChannelsMessagesV2Args {
    attributes?: pulumi.Input<string | undefined>;
    body?: pulumi.Input<string | undefined>;
    channelSid: pulumi.Input<string>;
    dateCreated?: pulumi.Input<string | undefined>;
    dateUpdated?: pulumi.Input<string | undefined>;
    from?: pulumi.Input<string | undefined>;
    lastUpdatedBy?: pulumi.Input<string | undefined>;
    mediaSid?: pulumi.Input<string | undefined>;
    serviceSid: pulumi.Input<string>;
    xTwilioWebhookEnabled?: pulumi.Input<string | undefined>;
}
