// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IpMessagingCredentialsV1 extends pulumi.CustomResource {
    /**
     * Get an existing IpMessagingCredentialsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IpMessagingCredentialsV1State, opts?: pulumi.CustomResourceOptions): IpMessagingCredentialsV1 {
        return new IpMessagingCredentialsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/ipMessagingCredentialsV1:IpMessagingCredentialsV1';

    /**
     * Returns true if the given object is an instance of IpMessagingCredentialsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IpMessagingCredentialsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IpMessagingCredentialsV1.__pulumiType;
    }

    declare public readonly apiKey: pulumi.Output<string>;
    declare public readonly certificate: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly privateKey: pulumi.Output<string>;
    declare public readonly sandbox: pulumi.Output<boolean>;
    declare public readonly secret: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a IpMessagingCredentialsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IpMessagingCredentialsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IpMessagingCredentialsV1Args | IpMessagingCredentialsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IpMessagingCredentialsV1State | undefined;
            resourceInputs["apiKey"] = state?.apiKey;
            resourceInputs["certificate"] = state?.certificate;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["privateKey"] = state?.privateKey;
            resourceInputs["sandbox"] = state?.sandbox;
            resourceInputs["secret"] = state?.secret;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as IpMessagingCredentialsV1Args | undefined;
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["apiKey"] = args?.apiKey;
            resourceInputs["certificate"] = args?.certificate;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["privateKey"] = args?.privateKey;
            resourceInputs["sandbox"] = args?.sandbox;
            resourceInputs["secret"] = args?.secret;
            resourceInputs["type"] = args?.type;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IpMessagingCredentialsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IpMessagingCredentialsV1 resources.
 */
export interface IpMessagingCredentialsV1State {
    apiKey?: pulumi.Input<string | undefined>;
    certificate?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    privateKey?: pulumi.Input<string | undefined>;
    sandbox?: pulumi.Input<boolean | undefined>;
    secret?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IpMessagingCredentialsV1 resource.
 */
export interface IpMessagingCredentialsV1Args {
    apiKey?: pulumi.Input<string | undefined>;
    certificate?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    privateKey?: pulumi.Input<string | undefined>;
    sandbox?: pulumi.Input<boolean | undefined>;
    secret?: pulumi.Input<string | undefined>;
    type: pulumi.Input<string>;
}
