// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class MessagingServicesComplianceUsa2pV1 extends pulumi.CustomResource {
    /**
     * Get an existing MessagingServicesComplianceUsa2pV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MessagingServicesComplianceUsa2pV1State, opts?: pulumi.CustomResourceOptions): MessagingServicesComplianceUsa2pV1 {
        return new MessagingServicesComplianceUsa2pV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/messagingServicesComplianceUsa2pV1:MessagingServicesComplianceUsa2pV1';

    /**
     * Returns true if the given object is an instance of MessagingServicesComplianceUsa2pV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MessagingServicesComplianceUsa2pV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MessagingServicesComplianceUsa2pV1.__pulumiType;
    }

    declare public readonly ageGated: pulumi.Output<boolean>;
    declare public readonly brandRegistrationSid: pulumi.Output<string>;
    declare public readonly description: pulumi.Output<string>;
    declare public readonly directLending: pulumi.Output<boolean>;
    declare public readonly hasEmbeddedLinks: pulumi.Output<boolean>;
    declare public readonly hasEmbeddedPhone: pulumi.Output<boolean>;
    declare public readonly helpKeywords: pulumi.Output<string[]>;
    declare public readonly helpMessage: pulumi.Output<string>;
    declare public readonly messageFlow: pulumi.Output<string>;
    declare public readonly messageSamples: pulumi.Output<string[]>;
    declare public readonly messagingServiceSid: pulumi.Output<string>;
    declare public readonly optInKeywords: pulumi.Output<string[]>;
    declare public readonly optInMessage: pulumi.Output<string>;
    declare public readonly optOutKeywords: pulumi.Output<string[]>;
    declare public readonly optOutMessage: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly subscriberOptIn: pulumi.Output<boolean>;
    declare public readonly usAppToPersonUsecase: pulumi.Output<string>;

    /**
     * Create a MessagingServicesComplianceUsa2pV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MessagingServicesComplianceUsa2pV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MessagingServicesComplianceUsa2pV1Args | MessagingServicesComplianceUsa2pV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MessagingServicesComplianceUsa2pV1State | undefined;
            resourceInputs["ageGated"] = state?.ageGated;
            resourceInputs["brandRegistrationSid"] = state?.brandRegistrationSid;
            resourceInputs["description"] = state?.description;
            resourceInputs["directLending"] = state?.directLending;
            resourceInputs["hasEmbeddedLinks"] = state?.hasEmbeddedLinks;
            resourceInputs["hasEmbeddedPhone"] = state?.hasEmbeddedPhone;
            resourceInputs["helpKeywords"] = state?.helpKeywords;
            resourceInputs["helpMessage"] = state?.helpMessage;
            resourceInputs["messageFlow"] = state?.messageFlow;
            resourceInputs["messageSamples"] = state?.messageSamples;
            resourceInputs["messagingServiceSid"] = state?.messagingServiceSid;
            resourceInputs["optInKeywords"] = state?.optInKeywords;
            resourceInputs["optInMessage"] = state?.optInMessage;
            resourceInputs["optOutKeywords"] = state?.optOutKeywords;
            resourceInputs["optOutMessage"] = state?.optOutMessage;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["subscriberOptIn"] = state?.subscriberOptIn;
            resourceInputs["usAppToPersonUsecase"] = state?.usAppToPersonUsecase;
        } else {
            const args = argsOrState as MessagingServicesComplianceUsa2pV1Args | undefined;
            if (args?.brandRegistrationSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'brandRegistrationSid'");
            }
            if (args?.description === undefined && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            if (args?.hasEmbeddedLinks === undefined && !opts.urn) {
                throw new Error("Missing required property 'hasEmbeddedLinks'");
            }
            if (args?.hasEmbeddedPhone === undefined && !opts.urn) {
                throw new Error("Missing required property 'hasEmbeddedPhone'");
            }
            if (args?.messageFlow === undefined && !opts.urn) {
                throw new Error("Missing required property 'messageFlow'");
            }
            if (args?.messageSamples === undefined && !opts.urn) {
                throw new Error("Missing required property 'messageSamples'");
            }
            if (args?.messagingServiceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'messagingServiceSid'");
            }
            if (args?.usAppToPersonUsecase === undefined && !opts.urn) {
                throw new Error("Missing required property 'usAppToPersonUsecase'");
            }
            resourceInputs["ageGated"] = args?.ageGated;
            resourceInputs["brandRegistrationSid"] = args?.brandRegistrationSid;
            resourceInputs["description"] = args?.description;
            resourceInputs["directLending"] = args?.directLending;
            resourceInputs["hasEmbeddedLinks"] = args?.hasEmbeddedLinks;
            resourceInputs["hasEmbeddedPhone"] = args?.hasEmbeddedPhone;
            resourceInputs["helpKeywords"] = args?.helpKeywords;
            resourceInputs["helpMessage"] = args?.helpMessage;
            resourceInputs["messageFlow"] = args?.messageFlow;
            resourceInputs["messageSamples"] = args?.messageSamples;
            resourceInputs["messagingServiceSid"] = args?.messagingServiceSid;
            resourceInputs["optInKeywords"] = args?.optInKeywords;
            resourceInputs["optInMessage"] = args?.optInMessage;
            resourceInputs["optOutKeywords"] = args?.optOutKeywords;
            resourceInputs["optOutMessage"] = args?.optOutMessage;
            resourceInputs["subscriberOptIn"] = args?.subscriberOptIn;
            resourceInputs["usAppToPersonUsecase"] = args?.usAppToPersonUsecase;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MessagingServicesComplianceUsa2pV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering MessagingServicesComplianceUsa2pV1 resources.
 */
export interface MessagingServicesComplianceUsa2pV1State {
    ageGated?: pulumi.Input<boolean | undefined>;
    brandRegistrationSid?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    directLending?: pulumi.Input<boolean | undefined>;
    hasEmbeddedLinks?: pulumi.Input<boolean | undefined>;
    hasEmbeddedPhone?: pulumi.Input<boolean | undefined>;
    helpKeywords?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    helpMessage?: pulumi.Input<string | undefined>;
    messageFlow?: pulumi.Input<string | undefined>;
    messageSamples?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    messagingServiceSid?: pulumi.Input<string | undefined>;
    optInKeywords?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    optInMessage?: pulumi.Input<string | undefined>;
    optOutKeywords?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    optOutMessage?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    subscriberOptIn?: pulumi.Input<boolean | undefined>;
    usAppToPersonUsecase?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a MessagingServicesComplianceUsa2pV1 resource.
 */
export interface MessagingServicesComplianceUsa2pV1Args {
    ageGated?: pulumi.Input<boolean | undefined>;
    brandRegistrationSid: pulumi.Input<string>;
    description: pulumi.Input<string>;
    directLending?: pulumi.Input<boolean | undefined>;
    hasEmbeddedLinks: pulumi.Input<boolean>;
    hasEmbeddedPhone: pulumi.Input<boolean>;
    helpKeywords?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    helpMessage?: pulumi.Input<string | undefined>;
    messageFlow: pulumi.Input<string>;
    messageSamples: pulumi.Input<pulumi.Input<string>[]>;
    messagingServiceSid: pulumi.Input<string>;
    optInKeywords?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    optInMessage?: pulumi.Input<string | undefined>;
    optOutKeywords?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    optOutMessage?: pulumi.Input<string | undefined>;
    subscriberOptIn?: pulumi.Input<boolean | undefined>;
    usAppToPersonUsecase: pulumi.Input<string>;
}
