// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class MessagingServicesV1 extends pulumi.CustomResource {
    /**
     * Get an existing MessagingServicesV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MessagingServicesV1State, opts?: pulumi.CustomResourceOptions): MessagingServicesV1 {
        return new MessagingServicesV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/messagingServicesV1:MessagingServicesV1';

    /**
     * Returns true if the given object is an instance of MessagingServicesV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MessagingServicesV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MessagingServicesV1.__pulumiType;
    }

    declare public readonly areaCodeGeomatch: pulumi.Output<boolean>;
    declare public readonly fallbackMethod: pulumi.Output<string>;
    declare public readonly fallbackToLongCode: pulumi.Output<boolean>;
    declare public readonly fallbackUrl: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly inboundMethod: pulumi.Output<string>;
    declare public readonly inboundRequestUrl: pulumi.Output<string>;
    declare public readonly mmsConverter: pulumi.Output<boolean>;
    declare public readonly scanMessageContent: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly smartEncoding: pulumi.Output<boolean>;
    declare public readonly statusCallback: pulumi.Output<string>;
    declare public readonly stickySender: pulumi.Output<boolean>;
    declare public readonly synchronousValidation: pulumi.Output<boolean>;
    declare public readonly useInboundWebhookOnNumber: pulumi.Output<boolean>;
    declare public readonly usecase: pulumi.Output<string>;
    declare public readonly validityPeriod: pulumi.Output<number>;

    /**
     * Create a MessagingServicesV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MessagingServicesV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MessagingServicesV1Args | MessagingServicesV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MessagingServicesV1State | undefined;
            resourceInputs["areaCodeGeomatch"] = state?.areaCodeGeomatch;
            resourceInputs["fallbackMethod"] = state?.fallbackMethod;
            resourceInputs["fallbackToLongCode"] = state?.fallbackToLongCode;
            resourceInputs["fallbackUrl"] = state?.fallbackUrl;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["inboundMethod"] = state?.inboundMethod;
            resourceInputs["inboundRequestUrl"] = state?.inboundRequestUrl;
            resourceInputs["mmsConverter"] = state?.mmsConverter;
            resourceInputs["scanMessageContent"] = state?.scanMessageContent;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["smartEncoding"] = state?.smartEncoding;
            resourceInputs["statusCallback"] = state?.statusCallback;
            resourceInputs["stickySender"] = state?.stickySender;
            resourceInputs["synchronousValidation"] = state?.synchronousValidation;
            resourceInputs["useInboundWebhookOnNumber"] = state?.useInboundWebhookOnNumber;
            resourceInputs["usecase"] = state?.usecase;
            resourceInputs["validityPeriod"] = state?.validityPeriod;
        } else {
            const args = argsOrState as MessagingServicesV1Args | undefined;
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            resourceInputs["areaCodeGeomatch"] = args?.areaCodeGeomatch;
            resourceInputs["fallbackMethod"] = args?.fallbackMethod;
            resourceInputs["fallbackToLongCode"] = args?.fallbackToLongCode;
            resourceInputs["fallbackUrl"] = args?.fallbackUrl;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["inboundMethod"] = args?.inboundMethod;
            resourceInputs["inboundRequestUrl"] = args?.inboundRequestUrl;
            resourceInputs["mmsConverter"] = args?.mmsConverter;
            resourceInputs["scanMessageContent"] = args?.scanMessageContent;
            resourceInputs["smartEncoding"] = args?.smartEncoding;
            resourceInputs["statusCallback"] = args?.statusCallback;
            resourceInputs["stickySender"] = args?.stickySender;
            resourceInputs["synchronousValidation"] = args?.synchronousValidation;
            resourceInputs["useInboundWebhookOnNumber"] = args?.useInboundWebhookOnNumber;
            resourceInputs["usecase"] = args?.usecase;
            resourceInputs["validityPeriod"] = args?.validityPeriod;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MessagingServicesV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering MessagingServicesV1 resources.
 */
export interface MessagingServicesV1State {
    areaCodeGeomatch?: pulumi.Input<boolean | undefined>;
    fallbackMethod?: pulumi.Input<string | undefined>;
    fallbackToLongCode?: pulumi.Input<boolean | undefined>;
    fallbackUrl?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    inboundMethod?: pulumi.Input<string | undefined>;
    inboundRequestUrl?: pulumi.Input<string | undefined>;
    mmsConverter?: pulumi.Input<boolean | undefined>;
    scanMessageContent?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    smartEncoding?: pulumi.Input<boolean | undefined>;
    statusCallback?: pulumi.Input<string | undefined>;
    stickySender?: pulumi.Input<boolean | undefined>;
    synchronousValidation?: pulumi.Input<boolean | undefined>;
    useInboundWebhookOnNumber?: pulumi.Input<boolean | undefined>;
    usecase?: pulumi.Input<string | undefined>;
    validityPeriod?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a MessagingServicesV1 resource.
 */
export interface MessagingServicesV1Args {
    areaCodeGeomatch?: pulumi.Input<boolean | undefined>;
    fallbackMethod?: pulumi.Input<string | undefined>;
    fallbackToLongCode?: pulumi.Input<boolean | undefined>;
    fallbackUrl?: pulumi.Input<string | undefined>;
    friendlyName: pulumi.Input<string>;
    inboundMethod?: pulumi.Input<string | undefined>;
    inboundRequestUrl?: pulumi.Input<string | undefined>;
    mmsConverter?: pulumi.Input<boolean | undefined>;
    scanMessageContent?: pulumi.Input<string | undefined>;
    smartEncoding?: pulumi.Input<boolean | undefined>;
    statusCallback?: pulumi.Input<string | undefined>;
    stickySender?: pulumi.Input<boolean | undefined>;
    synchronousValidation?: pulumi.Input<boolean | undefined>;
    useInboundWebhookOnNumber?: pulumi.Input<boolean | undefined>;
    usecase?: pulumi.Input<string | undefined>;
    validityPeriod?: pulumi.Input<number | undefined>;
}
