// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class MicrovisorDevicesSecretsV1 extends pulumi.CustomResource {
    /**
     * Get an existing MicrovisorDevicesSecretsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MicrovisorDevicesSecretsV1State, opts?: pulumi.CustomResourceOptions): MicrovisorDevicesSecretsV1 {
        return new MicrovisorDevicesSecretsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/microvisorDevicesSecretsV1:MicrovisorDevicesSecretsV1';

    /**
     * Returns true if the given object is an instance of MicrovisorDevicesSecretsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MicrovisorDevicesSecretsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MicrovisorDevicesSecretsV1.__pulumiType;
    }

    declare public readonly deviceSid: pulumi.Output<string>;
    declare public readonly key: pulumi.Output<string>;
    declare public readonly value: pulumi.Output<string>;

    /**
     * Create a MicrovisorDevicesSecretsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MicrovisorDevicesSecretsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MicrovisorDevicesSecretsV1Args | MicrovisorDevicesSecretsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MicrovisorDevicesSecretsV1State | undefined;
            resourceInputs["deviceSid"] = state?.deviceSid;
            resourceInputs["key"] = state?.key;
            resourceInputs["value"] = state?.value;
        } else {
            const args = argsOrState as MicrovisorDevicesSecretsV1Args | undefined;
            if (args?.deviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'deviceSid'");
            }
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["deviceSid"] = args?.deviceSid;
            resourceInputs["key"] = args?.key;
            resourceInputs["value"] = args?.value;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MicrovisorDevicesSecretsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering MicrovisorDevicesSecretsV1 resources.
 */
export interface MicrovisorDevicesSecretsV1State {
    deviceSid?: pulumi.Input<string | undefined>;
    key?: pulumi.Input<string | undefined>;
    value?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a MicrovisorDevicesSecretsV1 resource.
 */
export interface MicrovisorDevicesSecretsV1Args {
    deviceSid: pulumi.Input<string>;
    key: pulumi.Input<string>;
    value: pulumi.Input<string>;
}
