// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class NotifyServicesBindingsV1 extends pulumi.CustomResource {
    /**
     * Get an existing NotifyServicesBindingsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NotifyServicesBindingsV1State, opts?: pulumi.CustomResourceOptions): NotifyServicesBindingsV1 {
        return new NotifyServicesBindingsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/notifyServicesBindingsV1:NotifyServicesBindingsV1';

    /**
     * Returns true if the given object is an instance of NotifyServicesBindingsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NotifyServicesBindingsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NotifyServicesBindingsV1.__pulumiType;
    }

    declare public readonly address: pulumi.Output<string>;
    declare public readonly bindingType: pulumi.Output<string>;
    declare public readonly credentialSid: pulumi.Output<string>;
    declare public readonly endpoint: pulumi.Output<string>;
    declare public readonly identity: pulumi.Output<string>;
    declare public readonly notificationProtocolVersion: pulumi.Output<string>;
    declare public readonly serviceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly tags: pulumi.Output<string[]>;

    /**
     * Create a NotifyServicesBindingsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NotifyServicesBindingsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NotifyServicesBindingsV1Args | NotifyServicesBindingsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NotifyServicesBindingsV1State | undefined;
            resourceInputs["address"] = state?.address;
            resourceInputs["bindingType"] = state?.bindingType;
            resourceInputs["credentialSid"] = state?.credentialSid;
            resourceInputs["endpoint"] = state?.endpoint;
            resourceInputs["identity"] = state?.identity;
            resourceInputs["notificationProtocolVersion"] = state?.notificationProtocolVersion;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["tags"] = state?.tags;
        } else {
            const args = argsOrState as NotifyServicesBindingsV1Args | undefined;
            if (args?.address === undefined && !opts.urn) {
                throw new Error("Missing required property 'address'");
            }
            if (args?.bindingType === undefined && !opts.urn) {
                throw new Error("Missing required property 'bindingType'");
            }
            if (args?.identity === undefined && !opts.urn) {
                throw new Error("Missing required property 'identity'");
            }
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            resourceInputs["address"] = args?.address;
            resourceInputs["bindingType"] = args?.bindingType;
            resourceInputs["credentialSid"] = args?.credentialSid;
            resourceInputs["endpoint"] = args?.endpoint;
            resourceInputs["identity"] = args?.identity;
            resourceInputs["notificationProtocolVersion"] = args?.notificationProtocolVersion;
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NotifyServicesBindingsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NotifyServicesBindingsV1 resources.
 */
export interface NotifyServicesBindingsV1State {
    address?: pulumi.Input<string | undefined>;
    bindingType?: pulumi.Input<string | undefined>;
    credentialSid?: pulumi.Input<string | undefined>;
    endpoint?: pulumi.Input<string | undefined>;
    identity?: pulumi.Input<string | undefined>;
    notificationProtocolVersion?: pulumi.Input<string | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a NotifyServicesBindingsV1 resource.
 */
export interface NotifyServicesBindingsV1Args {
    address: pulumi.Input<string>;
    bindingType: pulumi.Input<string>;
    credentialSid?: pulumi.Input<string | undefined>;
    endpoint?: pulumi.Input<string | undefined>;
    identity: pulumi.Input<string>;
    notificationProtocolVersion?: pulumi.Input<string | undefined>;
    serviceSid: pulumi.Input<string>;
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
