// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class NumbersRegulatoryComplianceEndUsersV2 extends pulumi.CustomResource {
    /**
     * Get an existing NumbersRegulatoryComplianceEndUsersV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NumbersRegulatoryComplianceEndUsersV2State, opts?: pulumi.CustomResourceOptions): NumbersRegulatoryComplianceEndUsersV2 {
        return new NumbersRegulatoryComplianceEndUsersV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/numbersRegulatoryComplianceEndUsersV2:NumbersRegulatoryComplianceEndUsersV2';

    /**
     * Returns true if the given object is an instance of NumbersRegulatoryComplianceEndUsersV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NumbersRegulatoryComplianceEndUsersV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NumbersRegulatoryComplianceEndUsersV2.__pulumiType;
    }

    declare public readonly attributes: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a NumbersRegulatoryComplianceEndUsersV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NumbersRegulatoryComplianceEndUsersV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NumbersRegulatoryComplianceEndUsersV2Args | NumbersRegulatoryComplianceEndUsersV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NumbersRegulatoryComplianceEndUsersV2State | undefined;
            resourceInputs["attributes"] = state?.attributes;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as NumbersRegulatoryComplianceEndUsersV2Args | undefined;
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["attributes"] = args?.attributes;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["type"] = args?.type;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NumbersRegulatoryComplianceEndUsersV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NumbersRegulatoryComplianceEndUsersV2 resources.
 */
export interface NumbersRegulatoryComplianceEndUsersV2State {
    attributes?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a NumbersRegulatoryComplianceEndUsersV2 resource.
 */
export interface NumbersRegulatoryComplianceEndUsersV2Args {
    attributes?: pulumi.Input<string | undefined>;
    friendlyName: pulumi.Input<string>;
    type: pulumi.Input<string>;
}
