// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the twilio package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'twilio';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * Your SubAccount SID can be found on the Twilio dashboard at www.twilio.com/console.
     */
    declare public readonly accountSid: pulumi.Output<string | undefined>;
    /**
     * https://www.twilio.com/docs/global-infrastructure/edge-locations#public-edge-locations
     */
    declare public readonly edge: pulumi.Output<string | undefined>;
    /**
     * Your Auth Token/ API Secret can be found on the Twilio dashboard at www.twilio.com/console.
     */
    declare public readonly password: pulumi.Output<string | undefined>;
    /**
     * https://www.twilio.com/docs/global-infrastructure/edge-locations/legacy-regions
     */
    declare public readonly region: pulumi.Output<string | undefined>;
    /**
     * Your Account SID/ API Key can be found on the Twilio dashboard at www.twilio.com/console.
     */
    declare public readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["accountSid"] = (args?.accountSid) ?? utilities.getEnv("TWILIO_SUBACCOUNT_SID", "TWILIO_ACCOUNT_SID");
            resourceInputs["edge"] = (args?.edge) ?? utilities.getEnv("TWILIO_EDGE");
            resourceInputs["password"] = (args?.password) ?? utilities.getEnv("TWILIO_API_SECRET", "TWILIO_AUTH_TOKEN");
            resourceInputs["region"] = (args?.region) ?? utilities.getEnv("TWILIO_REGION");
            resourceInputs["username"] = (args?.username) ?? utilities.getEnv("TWILIO_API_KEY", "TWILIO_ACCOUNT_SID");
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }

    /**
     * This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
     */
    terraformConfig(): pulumi.Output<Provider.TerraformConfigResult> {
        return pulumi.runtime.call("pulumi:providers:twilio/terraformConfig", {
            "__self__": this,
        }, this);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Your SubAccount SID can be found on the Twilio dashboard at www.twilio.com/console.
     */
    accountSid?: pulumi.Input<string | undefined>;
    /**
     * https://www.twilio.com/docs/global-infrastructure/edge-locations#public-edge-locations
     */
    edge?: pulumi.Input<string | undefined>;
    /**
     * Your Auth Token/ API Secret can be found on the Twilio dashboard at www.twilio.com/console.
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * https://www.twilio.com/docs/global-infrastructure/edge-locations/legacy-regions
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * Your Account SID/ API Key can be found on the Twilio dashboard at www.twilio.com/console.
     */
    username?: pulumi.Input<string | undefined>;
}

export namespace Provider {
    /**
     * The results of the Provider.terraformConfig method.
     */
    export interface TerraformConfigResult {
        readonly result: {[key: string]: any};
    }

}
