// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ProxyServicesShortCodesV1 extends pulumi.CustomResource {
    /**
     * Get an existing ProxyServicesShortCodesV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProxyServicesShortCodesV1State, opts?: pulumi.CustomResourceOptions): ProxyServicesShortCodesV1 {
        return new ProxyServicesShortCodesV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/proxyServicesShortCodesV1:ProxyServicesShortCodesV1';

    /**
     * Returns true if the given object is an instance of ProxyServicesShortCodesV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProxyServicesShortCodesV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProxyServicesShortCodesV1.__pulumiType;
    }

    declare public readonly isReserved: pulumi.Output<boolean>;
    declare public readonly serviceSid: pulumi.Output<string>;
    declare public readonly sid: pulumi.Output<string>;

    /**
     * Create a ProxyServicesShortCodesV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProxyServicesShortCodesV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProxyServicesShortCodesV1Args | ProxyServicesShortCodesV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProxyServicesShortCodesV1State | undefined;
            resourceInputs["isReserved"] = state?.isReserved;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as ProxyServicesShortCodesV1Args | undefined;
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            if (args?.sid === undefined && !opts.urn) {
                throw new Error("Missing required property 'sid'");
            }
            resourceInputs["isReserved"] = args?.isReserved;
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["sid"] = args?.sid;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProxyServicesShortCodesV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ProxyServicesShortCodesV1 resources.
 */
export interface ProxyServicesShortCodesV1State {
    isReserved?: pulumi.Input<boolean | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ProxyServicesShortCodesV1 resource.
 */
export interface ProxyServicesShortCodesV1Args {
    isReserved?: pulumi.Input<boolean | undefined>;
    serviceSid: pulumi.Input<string>;
    sid: pulumi.Input<string>;
}
