// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ServerlessServicesEnvironmentsVariablesV1 extends pulumi.CustomResource {
    /**
     * Get an existing ServerlessServicesEnvironmentsVariablesV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServerlessServicesEnvironmentsVariablesV1State, opts?: pulumi.CustomResourceOptions): ServerlessServicesEnvironmentsVariablesV1 {
        return new ServerlessServicesEnvironmentsVariablesV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/serverlessServicesEnvironmentsVariablesV1:ServerlessServicesEnvironmentsVariablesV1';

    /**
     * Returns true if the given object is an instance of ServerlessServicesEnvironmentsVariablesV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServerlessServicesEnvironmentsVariablesV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServerlessServicesEnvironmentsVariablesV1.__pulumiType;
    }

    declare public readonly environmentSid: pulumi.Output<string>;
    declare public readonly key: pulumi.Output<string>;
    declare public readonly serviceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly value: pulumi.Output<string>;

    /**
     * Create a ServerlessServicesEnvironmentsVariablesV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServerlessServicesEnvironmentsVariablesV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServerlessServicesEnvironmentsVariablesV1Args | ServerlessServicesEnvironmentsVariablesV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServerlessServicesEnvironmentsVariablesV1State | undefined;
            resourceInputs["environmentSid"] = state?.environmentSid;
            resourceInputs["key"] = state?.key;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["value"] = state?.value;
        } else {
            const args = argsOrState as ServerlessServicesEnvironmentsVariablesV1Args | undefined;
            if (args?.environmentSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentSid'");
            }
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["environmentSid"] = args?.environmentSid;
            resourceInputs["key"] = args?.key;
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["value"] = args?.value;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServerlessServicesEnvironmentsVariablesV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ServerlessServicesEnvironmentsVariablesV1 resources.
 */
export interface ServerlessServicesEnvironmentsVariablesV1State {
    environmentSid?: pulumi.Input<string | undefined>;
    key?: pulumi.Input<string | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    value?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ServerlessServicesEnvironmentsVariablesV1 resource.
 */
export interface ServerlessServicesEnvironmentsVariablesV1Args {
    environmentSid: pulumi.Input<string>;
    key: pulumi.Input<string>;
    serviceSid: pulumi.Input<string>;
    value: pulumi.Input<string>;
}
