// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ServerlessServicesAssetsV1 extends pulumi.CustomResource {
    /**
     * Get an existing ServerlessServicesAssetsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServerlessServicesAssetsV1State, opts?: pulumi.CustomResourceOptions): ServerlessServicesAssetsV1 {
        return new ServerlessServicesAssetsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/serverlessServicesAssetsV1:ServerlessServicesAssetsV1';

    /**
     * Returns true if the given object is an instance of ServerlessServicesAssetsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServerlessServicesAssetsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServerlessServicesAssetsV1.__pulumiType;
    }

    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly serviceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a ServerlessServicesAssetsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServerlessServicesAssetsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServerlessServicesAssetsV1Args | ServerlessServicesAssetsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServerlessServicesAssetsV1State | undefined;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as ServerlessServicesAssetsV1Args | undefined;
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServerlessServicesAssetsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ServerlessServicesAssetsV1 resources.
 */
export interface ServerlessServicesAssetsV1State {
    friendlyName?: pulumi.Input<string | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ServerlessServicesAssetsV1 resource.
 */
export interface ServerlessServicesAssetsV1Args {
    friendlyName: pulumi.Input<string>;
    serviceSid: pulumi.Input<string>;
}
