// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class StudioFlowsEngagementsV1 extends pulumi.CustomResource {
    /**
     * Get an existing StudioFlowsEngagementsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StudioFlowsEngagementsV1State, opts?: pulumi.CustomResourceOptions): StudioFlowsEngagementsV1 {
        return new StudioFlowsEngagementsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/studioFlowsEngagementsV1:StudioFlowsEngagementsV1';

    /**
     * Returns true if the given object is an instance of StudioFlowsEngagementsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StudioFlowsEngagementsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StudioFlowsEngagementsV1.__pulumiType;
    }

    declare public readonly flowSid: pulumi.Output<string>;
    declare public readonly from: pulumi.Output<string>;
    declare public readonly parameters: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly to: pulumi.Output<string>;

    /**
     * Create a StudioFlowsEngagementsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StudioFlowsEngagementsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StudioFlowsEngagementsV1Args | StudioFlowsEngagementsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StudioFlowsEngagementsV1State | undefined;
            resourceInputs["flowSid"] = state?.flowSid;
            resourceInputs["from"] = state?.from;
            resourceInputs["parameters"] = state?.parameters;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["to"] = state?.to;
        } else {
            const args = argsOrState as StudioFlowsEngagementsV1Args | undefined;
            if (args?.flowSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'flowSid'");
            }
            if (args?.from === undefined && !opts.urn) {
                throw new Error("Missing required property 'from'");
            }
            if (args?.to === undefined && !opts.urn) {
                throw new Error("Missing required property 'to'");
            }
            resourceInputs["flowSid"] = args?.flowSid;
            resourceInputs["from"] = args?.from;
            resourceInputs["parameters"] = args?.parameters;
            resourceInputs["to"] = args?.to;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StudioFlowsEngagementsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering StudioFlowsEngagementsV1 resources.
 */
export interface StudioFlowsEngagementsV1State {
    flowSid?: pulumi.Input<string | undefined>;
    from?: pulumi.Input<string | undefined>;
    parameters?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    to?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a StudioFlowsEngagementsV1 resource.
 */
export interface StudioFlowsEngagementsV1Args {
    flowSid: pulumi.Input<string>;
    from: pulumi.Input<string>;
    parameters?: pulumi.Input<string | undefined>;
    to: pulumi.Input<string>;
}
