// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SyncServicesStreamsV1 extends pulumi.CustomResource {
    /**
     * Get an existing SyncServicesStreamsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SyncServicesStreamsV1State, opts?: pulumi.CustomResourceOptions): SyncServicesStreamsV1 {
        return new SyncServicesStreamsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/syncServicesStreamsV1:SyncServicesStreamsV1';

    /**
     * Returns true if the given object is an instance of SyncServicesStreamsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SyncServicesStreamsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SyncServicesStreamsV1.__pulumiType;
    }

    declare public readonly serviceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly ttl: pulumi.Output<number>;
    declare public readonly uniqueName: pulumi.Output<string>;

    /**
     * Create a SyncServicesStreamsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SyncServicesStreamsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SyncServicesStreamsV1Args | SyncServicesStreamsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SyncServicesStreamsV1State | undefined;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["ttl"] = state?.ttl;
            resourceInputs["uniqueName"] = state?.uniqueName;
        } else {
            const args = argsOrState as SyncServicesStreamsV1Args | undefined;
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["ttl"] = args?.ttl;
            resourceInputs["uniqueName"] = args?.uniqueName;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SyncServicesStreamsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SyncServicesStreamsV1 resources.
 */
export interface SyncServicesStreamsV1State {
    serviceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    ttl?: pulumi.Input<number | undefined>;
    uniqueName?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SyncServicesStreamsV1 resource.
 */
export interface SyncServicesStreamsV1Args {
    serviceSid: pulumi.Input<string>;
    ttl?: pulumi.Input<number | undefined>;
    uniqueName?: pulumi.Input<string | undefined>;
}
