// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SyncServicesMapsItemsV1 extends pulumi.CustomResource {
    /**
     * Get an existing SyncServicesMapsItemsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SyncServicesMapsItemsV1State, opts?: pulumi.CustomResourceOptions): SyncServicesMapsItemsV1 {
        return new SyncServicesMapsItemsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/syncServicesMapsItemsV1:SyncServicesMapsItemsV1';

    /**
     * Returns true if the given object is an instance of SyncServicesMapsItemsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SyncServicesMapsItemsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SyncServicesMapsItemsV1.__pulumiType;
    }

    declare public readonly collectionTtl: pulumi.Output<number>;
    declare public readonly data: pulumi.Output<string>;
    declare public readonly ifMatch: pulumi.Output<string>;
    declare public readonly itemTtl: pulumi.Output<number>;
    declare public readonly key: pulumi.Output<string>;
    declare public readonly mapSid: pulumi.Output<string>;
    declare public readonly serviceSid: pulumi.Output<string>;
    declare public readonly ttl: pulumi.Output<number>;

    /**
     * Create a SyncServicesMapsItemsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SyncServicesMapsItemsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SyncServicesMapsItemsV1Args | SyncServicesMapsItemsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SyncServicesMapsItemsV1State | undefined;
            resourceInputs["collectionTtl"] = state?.collectionTtl;
            resourceInputs["data"] = state?.data;
            resourceInputs["ifMatch"] = state?.ifMatch;
            resourceInputs["itemTtl"] = state?.itemTtl;
            resourceInputs["key"] = state?.key;
            resourceInputs["mapSid"] = state?.mapSid;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["ttl"] = state?.ttl;
        } else {
            const args = argsOrState as SyncServicesMapsItemsV1Args | undefined;
            if (args?.data === undefined && !opts.urn) {
                throw new Error("Missing required property 'data'");
            }
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if (args?.mapSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'mapSid'");
            }
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            resourceInputs["collectionTtl"] = args?.collectionTtl;
            resourceInputs["data"] = args?.data;
            resourceInputs["ifMatch"] = args?.ifMatch;
            resourceInputs["itemTtl"] = args?.itemTtl;
            resourceInputs["key"] = args?.key;
            resourceInputs["mapSid"] = args?.mapSid;
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["ttl"] = args?.ttl;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SyncServicesMapsItemsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SyncServicesMapsItemsV1 resources.
 */
export interface SyncServicesMapsItemsV1State {
    collectionTtl?: pulumi.Input<number | undefined>;
    data?: pulumi.Input<string | undefined>;
    ifMatch?: pulumi.Input<string | undefined>;
    itemTtl?: pulumi.Input<number | undefined>;
    key?: pulumi.Input<string | undefined>;
    mapSid?: pulumi.Input<string | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
    ttl?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a SyncServicesMapsItemsV1 resource.
 */
export interface SyncServicesMapsItemsV1Args {
    collectionTtl?: pulumi.Input<number | undefined>;
    data: pulumi.Input<string>;
    ifMatch?: pulumi.Input<string | undefined>;
    itemTtl?: pulumi.Input<number | undefined>;
    key: pulumi.Input<string>;
    mapSid: pulumi.Input<string>;
    serviceSid: pulumi.Input<string>;
    ttl?: pulumi.Input<number | undefined>;
}
