// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TaskrouterWorkspacesV1 extends pulumi.CustomResource {
    /**
     * Get an existing TaskrouterWorkspacesV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TaskrouterWorkspacesV1State, opts?: pulumi.CustomResourceOptions): TaskrouterWorkspacesV1 {
        return new TaskrouterWorkspacesV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/taskrouterWorkspacesV1:TaskrouterWorkspacesV1';

    /**
     * Returns true if the given object is an instance of TaskrouterWorkspacesV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TaskrouterWorkspacesV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TaskrouterWorkspacesV1.__pulumiType;
    }

    declare public readonly defaultActivitySid: pulumi.Output<string>;
    declare public readonly eventCallbackUrl: pulumi.Output<string>;
    declare public readonly eventsFilter: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly multiTaskEnabled: pulumi.Output<boolean>;
    declare public readonly prioritizeQueueOrder: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly template: pulumi.Output<string>;
    declare public readonly timeoutActivitySid: pulumi.Output<string>;

    /**
     * Create a TaskrouterWorkspacesV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TaskrouterWorkspacesV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TaskrouterWorkspacesV1Args | TaskrouterWorkspacesV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TaskrouterWorkspacesV1State | undefined;
            resourceInputs["defaultActivitySid"] = state?.defaultActivitySid;
            resourceInputs["eventCallbackUrl"] = state?.eventCallbackUrl;
            resourceInputs["eventsFilter"] = state?.eventsFilter;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["multiTaskEnabled"] = state?.multiTaskEnabled;
            resourceInputs["prioritizeQueueOrder"] = state?.prioritizeQueueOrder;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["template"] = state?.template;
            resourceInputs["timeoutActivitySid"] = state?.timeoutActivitySid;
        } else {
            const args = argsOrState as TaskrouterWorkspacesV1Args | undefined;
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            resourceInputs["defaultActivitySid"] = args?.defaultActivitySid;
            resourceInputs["eventCallbackUrl"] = args?.eventCallbackUrl;
            resourceInputs["eventsFilter"] = args?.eventsFilter;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["multiTaskEnabled"] = args?.multiTaskEnabled;
            resourceInputs["prioritizeQueueOrder"] = args?.prioritizeQueueOrder;
            resourceInputs["template"] = args?.template;
            resourceInputs["timeoutActivitySid"] = args?.timeoutActivitySid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TaskrouterWorkspacesV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TaskrouterWorkspacesV1 resources.
 */
export interface TaskrouterWorkspacesV1State {
    defaultActivitySid?: pulumi.Input<string | undefined>;
    eventCallbackUrl?: pulumi.Input<string | undefined>;
    eventsFilter?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    multiTaskEnabled?: pulumi.Input<boolean | undefined>;
    prioritizeQueueOrder?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    template?: pulumi.Input<string | undefined>;
    timeoutActivitySid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TaskrouterWorkspacesV1 resource.
 */
export interface TaskrouterWorkspacesV1Args {
    defaultActivitySid?: pulumi.Input<string | undefined>;
    eventCallbackUrl?: pulumi.Input<string | undefined>;
    eventsFilter?: pulumi.Input<string | undefined>;
    friendlyName: pulumi.Input<string>;
    multiTaskEnabled?: pulumi.Input<boolean | undefined>;
    prioritizeQueueOrder?: pulumi.Input<string | undefined>;
    template?: pulumi.Input<string | undefined>;
    timeoutActivitySid?: pulumi.Input<string | undefined>;
}
