// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TaskrouterWorkspacesActivitiesV1 extends pulumi.CustomResource {
    /**
     * Get an existing TaskrouterWorkspacesActivitiesV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TaskrouterWorkspacesActivitiesV1State, opts?: pulumi.CustomResourceOptions): TaskrouterWorkspacesActivitiesV1 {
        return new TaskrouterWorkspacesActivitiesV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/taskrouterWorkspacesActivitiesV1:TaskrouterWorkspacesActivitiesV1';

    /**
     * Returns true if the given object is an instance of TaskrouterWorkspacesActivitiesV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TaskrouterWorkspacesActivitiesV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TaskrouterWorkspacesActivitiesV1.__pulumiType;
    }

    declare public readonly available: pulumi.Output<boolean>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly workspaceSid: pulumi.Output<string>;

    /**
     * Create a TaskrouterWorkspacesActivitiesV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TaskrouterWorkspacesActivitiesV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TaskrouterWorkspacesActivitiesV1Args | TaskrouterWorkspacesActivitiesV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TaskrouterWorkspacesActivitiesV1State | undefined;
            resourceInputs["available"] = state?.available;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["workspaceSid"] = state?.workspaceSid;
        } else {
            const args = argsOrState as TaskrouterWorkspacesActivitiesV1Args | undefined;
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            if (args?.workspaceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'workspaceSid'");
            }
            resourceInputs["available"] = args?.available;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["workspaceSid"] = args?.workspaceSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TaskrouterWorkspacesActivitiesV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TaskrouterWorkspacesActivitiesV1 resources.
 */
export interface TaskrouterWorkspacesActivitiesV1State {
    available?: pulumi.Input<boolean | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    workspaceSid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TaskrouterWorkspacesActivitiesV1 resource.
 */
export interface TaskrouterWorkspacesActivitiesV1Args {
    available?: pulumi.Input<boolean | undefined>;
    friendlyName: pulumi.Input<string>;
    workspaceSid: pulumi.Input<string>;
}
