// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TrunkingTrunksV1 extends pulumi.CustomResource {
    /**
     * Get an existing TrunkingTrunksV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TrunkingTrunksV1State, opts?: pulumi.CustomResourceOptions): TrunkingTrunksV1 {
        return new TrunkingTrunksV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/trunkingTrunksV1:TrunkingTrunksV1';

    /**
     * Returns true if the given object is an instance of TrunkingTrunksV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TrunkingTrunksV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TrunkingTrunksV1.__pulumiType;
    }

    declare public readonly cnamLookupEnabled: pulumi.Output<boolean>;
    declare public readonly disasterRecoveryMethod: pulumi.Output<string>;
    declare public readonly disasterRecoveryUrl: pulumi.Output<string>;
    declare public readonly domainName: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly secure: pulumi.Output<boolean>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly transferCallerId: pulumi.Output<string>;
    declare public readonly transferMode: pulumi.Output<string>;

    /**
     * Create a TrunkingTrunksV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: TrunkingTrunksV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TrunkingTrunksV1Args | TrunkingTrunksV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TrunkingTrunksV1State | undefined;
            resourceInputs["cnamLookupEnabled"] = state?.cnamLookupEnabled;
            resourceInputs["disasterRecoveryMethod"] = state?.disasterRecoveryMethod;
            resourceInputs["disasterRecoveryUrl"] = state?.disasterRecoveryUrl;
            resourceInputs["domainName"] = state?.domainName;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["secure"] = state?.secure;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["transferCallerId"] = state?.transferCallerId;
            resourceInputs["transferMode"] = state?.transferMode;
        } else {
            const args = argsOrState as TrunkingTrunksV1Args | undefined;
            resourceInputs["cnamLookupEnabled"] = args?.cnamLookupEnabled;
            resourceInputs["disasterRecoveryMethod"] = args?.disasterRecoveryMethod;
            resourceInputs["disasterRecoveryUrl"] = args?.disasterRecoveryUrl;
            resourceInputs["domainName"] = args?.domainName;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["secure"] = args?.secure;
            resourceInputs["transferCallerId"] = args?.transferCallerId;
            resourceInputs["transferMode"] = args?.transferMode;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TrunkingTrunksV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TrunkingTrunksV1 resources.
 */
export interface TrunkingTrunksV1State {
    cnamLookupEnabled?: pulumi.Input<boolean | undefined>;
    disasterRecoveryMethod?: pulumi.Input<string | undefined>;
    disasterRecoveryUrl?: pulumi.Input<string | undefined>;
    domainName?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    secure?: pulumi.Input<boolean | undefined>;
    sid?: pulumi.Input<string | undefined>;
    transferCallerId?: pulumi.Input<string | undefined>;
    transferMode?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TrunkingTrunksV1 resource.
 */
export interface TrunkingTrunksV1Args {
    cnamLookupEnabled?: pulumi.Input<boolean | undefined>;
    disasterRecoveryMethod?: pulumi.Input<string | undefined>;
    disasterRecoveryUrl?: pulumi.Input<string | undefined>;
    domainName?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    secure?: pulumi.Input<boolean | undefined>;
    transferCallerId?: pulumi.Input<string | undefined>;
    transferMode?: pulumi.Input<string | undefined>;
}
