// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TrunkingTrunksCredentialListsV1 extends pulumi.CustomResource {
    /**
     * Get an existing TrunkingTrunksCredentialListsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TrunkingTrunksCredentialListsV1State, opts?: pulumi.CustomResourceOptions): TrunkingTrunksCredentialListsV1 {
        return new TrunkingTrunksCredentialListsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/trunkingTrunksCredentialListsV1:TrunkingTrunksCredentialListsV1';

    /**
     * Returns true if the given object is an instance of TrunkingTrunksCredentialListsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TrunkingTrunksCredentialListsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TrunkingTrunksCredentialListsV1.__pulumiType;
    }

    declare public readonly credentialListSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly trunkSid: pulumi.Output<string>;

    /**
     * Create a TrunkingTrunksCredentialListsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TrunkingTrunksCredentialListsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TrunkingTrunksCredentialListsV1Args | TrunkingTrunksCredentialListsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TrunkingTrunksCredentialListsV1State | undefined;
            resourceInputs["credentialListSid"] = state?.credentialListSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["trunkSid"] = state?.trunkSid;
        } else {
            const args = argsOrState as TrunkingTrunksCredentialListsV1Args | undefined;
            if (args?.credentialListSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'credentialListSid'");
            }
            if (args?.trunkSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'trunkSid'");
            }
            resourceInputs["credentialListSid"] = args?.credentialListSid;
            resourceInputs["trunkSid"] = args?.trunkSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TrunkingTrunksCredentialListsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TrunkingTrunksCredentialListsV1 resources.
 */
export interface TrunkingTrunksCredentialListsV1State {
    credentialListSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    trunkSid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TrunkingTrunksCredentialListsV1 resource.
 */
export interface TrunkingTrunksCredentialListsV1Args {
    credentialListSid: pulumi.Input<string>;
    trunkSid: pulumi.Input<string>;
}
