// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TrunkingTrunksIpAccessControlListsV1 extends pulumi.CustomResource {
    /**
     * Get an existing TrunkingTrunksIpAccessControlListsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TrunkingTrunksIpAccessControlListsV1State, opts?: pulumi.CustomResourceOptions): TrunkingTrunksIpAccessControlListsV1 {
        return new TrunkingTrunksIpAccessControlListsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/trunkingTrunksIpAccessControlListsV1:TrunkingTrunksIpAccessControlListsV1';

    /**
     * Returns true if the given object is an instance of TrunkingTrunksIpAccessControlListsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TrunkingTrunksIpAccessControlListsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TrunkingTrunksIpAccessControlListsV1.__pulumiType;
    }

    declare public readonly ipAccessControlListSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly trunkSid: pulumi.Output<string>;

    /**
     * Create a TrunkingTrunksIpAccessControlListsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TrunkingTrunksIpAccessControlListsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TrunkingTrunksIpAccessControlListsV1Args | TrunkingTrunksIpAccessControlListsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TrunkingTrunksIpAccessControlListsV1State | undefined;
            resourceInputs["ipAccessControlListSid"] = state?.ipAccessControlListSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["trunkSid"] = state?.trunkSid;
        } else {
            const args = argsOrState as TrunkingTrunksIpAccessControlListsV1Args | undefined;
            if (args?.ipAccessControlListSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'ipAccessControlListSid'");
            }
            if (args?.trunkSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'trunkSid'");
            }
            resourceInputs["ipAccessControlListSid"] = args?.ipAccessControlListSid;
            resourceInputs["trunkSid"] = args?.trunkSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TrunkingTrunksIpAccessControlListsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TrunkingTrunksIpAccessControlListsV1 resources.
 */
export interface TrunkingTrunksIpAccessControlListsV1State {
    ipAccessControlListSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    trunkSid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TrunkingTrunksIpAccessControlListsV1 resource.
 */
export interface TrunkingTrunksIpAccessControlListsV1Args {
    ipAccessControlListSid: pulumi.Input<string>;
    trunkSid: pulumi.Input<string>;
}
