// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TrusthubCustomerProfilesV1 extends pulumi.CustomResource {
    /**
     * Get an existing TrusthubCustomerProfilesV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TrusthubCustomerProfilesV1State, opts?: pulumi.CustomResourceOptions): TrusthubCustomerProfilesV1 {
        return new TrusthubCustomerProfilesV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/trusthubCustomerProfilesV1:TrusthubCustomerProfilesV1';

    /**
     * Returns true if the given object is an instance of TrusthubCustomerProfilesV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TrusthubCustomerProfilesV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TrusthubCustomerProfilesV1.__pulumiType;
    }

    declare public readonly email: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly policySid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly status: pulumi.Output<string>;
    declare public readonly statusCallback: pulumi.Output<string>;

    /**
     * Create a TrusthubCustomerProfilesV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TrusthubCustomerProfilesV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TrusthubCustomerProfilesV1Args | TrusthubCustomerProfilesV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TrusthubCustomerProfilesV1State | undefined;
            resourceInputs["email"] = state?.email;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["policySid"] = state?.policySid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["status"] = state?.status;
            resourceInputs["statusCallback"] = state?.statusCallback;
        } else {
            const args = argsOrState as TrusthubCustomerProfilesV1Args | undefined;
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            if (args?.policySid === undefined && !opts.urn) {
                throw new Error("Missing required property 'policySid'");
            }
            resourceInputs["email"] = args?.email;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["policySid"] = args?.policySid;
            resourceInputs["status"] = args?.status;
            resourceInputs["statusCallback"] = args?.statusCallback;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TrusthubCustomerProfilesV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TrusthubCustomerProfilesV1 resources.
 */
export interface TrusthubCustomerProfilesV1State {
    email?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    policySid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    status?: pulumi.Input<string | undefined>;
    statusCallback?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TrusthubCustomerProfilesV1 resource.
 */
export interface TrusthubCustomerProfilesV1Args {
    email: pulumi.Input<string>;
    friendlyName: pulumi.Input<string>;
    policySid: pulumi.Input<string>;
    status?: pulumi.Input<string | undefined>;
    statusCallback?: pulumi.Input<string | undefined>;
}
