// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TrusthubTrustProductsEntityAssignmentsV1 extends pulumi.CustomResource {
    /**
     * Get an existing TrusthubTrustProductsEntityAssignmentsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TrusthubTrustProductsEntityAssignmentsV1State, opts?: pulumi.CustomResourceOptions): TrusthubTrustProductsEntityAssignmentsV1 {
        return new TrusthubTrustProductsEntityAssignmentsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/trusthubTrustProductsEntityAssignmentsV1:TrusthubTrustProductsEntityAssignmentsV1';

    /**
     * Returns true if the given object is an instance of TrusthubTrustProductsEntityAssignmentsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TrusthubTrustProductsEntityAssignmentsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TrusthubTrustProductsEntityAssignmentsV1.__pulumiType;
    }

    declare public readonly objectSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly trustProductSid: pulumi.Output<string>;

    /**
     * Create a TrusthubTrustProductsEntityAssignmentsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TrusthubTrustProductsEntityAssignmentsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TrusthubTrustProductsEntityAssignmentsV1Args | TrusthubTrustProductsEntityAssignmentsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TrusthubTrustProductsEntityAssignmentsV1State | undefined;
            resourceInputs["objectSid"] = state?.objectSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["trustProductSid"] = state?.trustProductSid;
        } else {
            const args = argsOrState as TrusthubTrustProductsEntityAssignmentsV1Args | undefined;
            if (args?.objectSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'objectSid'");
            }
            if (args?.trustProductSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'trustProductSid'");
            }
            resourceInputs["objectSid"] = args?.objectSid;
            resourceInputs["trustProductSid"] = args?.trustProductSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TrusthubTrustProductsEntityAssignmentsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TrusthubTrustProductsEntityAssignmentsV1 resources.
 */
export interface TrusthubTrustProductsEntityAssignmentsV1State {
    objectSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    trustProductSid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TrusthubTrustProductsEntityAssignmentsV1 resource.
 */
export interface TrusthubTrustProductsEntityAssignmentsV1Args {
    objectSid: pulumi.Input<string>;
    trustProductSid: pulumi.Input<string>;
}
