// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TrusthubCustomerProfilesEntityAssignmentsV1 extends pulumi.CustomResource {
    /**
     * Get an existing TrusthubCustomerProfilesEntityAssignmentsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TrusthubCustomerProfilesEntityAssignmentsV1State, opts?: pulumi.CustomResourceOptions): TrusthubCustomerProfilesEntityAssignmentsV1 {
        return new TrusthubCustomerProfilesEntityAssignmentsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/trusthubCustomerProfilesEntityAssignmentsV1:TrusthubCustomerProfilesEntityAssignmentsV1';

    /**
     * Returns true if the given object is an instance of TrusthubCustomerProfilesEntityAssignmentsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TrusthubCustomerProfilesEntityAssignmentsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TrusthubCustomerProfilesEntityAssignmentsV1.__pulumiType;
    }

    declare public readonly customerProfileSid: pulumi.Output<string>;
    declare public readonly objectSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a TrusthubCustomerProfilesEntityAssignmentsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TrusthubCustomerProfilesEntityAssignmentsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TrusthubCustomerProfilesEntityAssignmentsV1Args | TrusthubCustomerProfilesEntityAssignmentsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TrusthubCustomerProfilesEntityAssignmentsV1State | undefined;
            resourceInputs["customerProfileSid"] = state?.customerProfileSid;
            resourceInputs["objectSid"] = state?.objectSid;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as TrusthubCustomerProfilesEntityAssignmentsV1Args | undefined;
            if (args?.customerProfileSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'customerProfileSid'");
            }
            if (args?.objectSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'objectSid'");
            }
            resourceInputs["customerProfileSid"] = args?.customerProfileSid;
            resourceInputs["objectSid"] = args?.objectSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TrusthubCustomerProfilesEntityAssignmentsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TrusthubCustomerProfilesEntityAssignmentsV1 resources.
 */
export interface TrusthubCustomerProfilesEntityAssignmentsV1State {
    customerProfileSid?: pulumi.Input<string | undefined>;
    objectSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TrusthubCustomerProfilesEntityAssignmentsV1 resource.
 */
export interface TrusthubCustomerProfilesEntityAssignmentsV1Args {
    customerProfileSid: pulumi.Input<string>;
    objectSid: pulumi.Input<string>;
}
