// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TrusthubCustomerProfilesChannelEndpointAssignmentsV1 extends pulumi.CustomResource {
    /**
     * Get an existing TrusthubCustomerProfilesChannelEndpointAssignmentsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TrusthubCustomerProfilesChannelEndpointAssignmentsV1State, opts?: pulumi.CustomResourceOptions): TrusthubCustomerProfilesChannelEndpointAssignmentsV1 {
        return new TrusthubCustomerProfilesChannelEndpointAssignmentsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/trusthubCustomerProfilesChannelEndpointAssignmentsV1:TrusthubCustomerProfilesChannelEndpointAssignmentsV1';

    /**
     * Returns true if the given object is an instance of TrusthubCustomerProfilesChannelEndpointAssignmentsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TrusthubCustomerProfilesChannelEndpointAssignmentsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TrusthubCustomerProfilesChannelEndpointAssignmentsV1.__pulumiType;
    }

    declare public readonly channelEndpointSid: pulumi.Output<string>;
    declare public readonly channelEndpointType: pulumi.Output<string>;
    declare public readonly customerProfileSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a TrusthubCustomerProfilesChannelEndpointAssignmentsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TrusthubCustomerProfilesChannelEndpointAssignmentsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TrusthubCustomerProfilesChannelEndpointAssignmentsV1Args | TrusthubCustomerProfilesChannelEndpointAssignmentsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TrusthubCustomerProfilesChannelEndpointAssignmentsV1State | undefined;
            resourceInputs["channelEndpointSid"] = state?.channelEndpointSid;
            resourceInputs["channelEndpointType"] = state?.channelEndpointType;
            resourceInputs["customerProfileSid"] = state?.customerProfileSid;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as TrusthubCustomerProfilesChannelEndpointAssignmentsV1Args | undefined;
            if (args?.channelEndpointSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'channelEndpointSid'");
            }
            if (args?.channelEndpointType === undefined && !opts.urn) {
                throw new Error("Missing required property 'channelEndpointType'");
            }
            if (args?.customerProfileSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'customerProfileSid'");
            }
            resourceInputs["channelEndpointSid"] = args?.channelEndpointSid;
            resourceInputs["channelEndpointType"] = args?.channelEndpointType;
            resourceInputs["customerProfileSid"] = args?.customerProfileSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TrusthubCustomerProfilesChannelEndpointAssignmentsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TrusthubCustomerProfilesChannelEndpointAssignmentsV1 resources.
 */
export interface TrusthubCustomerProfilesChannelEndpointAssignmentsV1State {
    channelEndpointSid?: pulumi.Input<string | undefined>;
    channelEndpointType?: pulumi.Input<string | undefined>;
    customerProfileSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TrusthubCustomerProfilesChannelEndpointAssignmentsV1 resource.
 */
export interface TrusthubCustomerProfilesChannelEndpointAssignmentsV1Args {
    channelEndpointSid: pulumi.Input<string>;
    channelEndpointType: pulumi.Input<string>;
    customerProfileSid: pulumi.Input<string>;
}
