// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class VerifyServicesMessagingConfigurationsV2 extends pulumi.CustomResource {
    /**
     * Get an existing VerifyServicesMessagingConfigurationsV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VerifyServicesMessagingConfigurationsV2State, opts?: pulumi.CustomResourceOptions): VerifyServicesMessagingConfigurationsV2 {
        return new VerifyServicesMessagingConfigurationsV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/verifyServicesMessagingConfigurationsV2:VerifyServicesMessagingConfigurationsV2';

    /**
     * Returns true if the given object is an instance of VerifyServicesMessagingConfigurationsV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VerifyServicesMessagingConfigurationsV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VerifyServicesMessagingConfigurationsV2.__pulumiType;
    }

    declare public readonly country: pulumi.Output<string>;
    declare public readonly messagingServiceSid: pulumi.Output<string>;
    declare public readonly serviceSid: pulumi.Output<string>;

    /**
     * Create a VerifyServicesMessagingConfigurationsV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VerifyServicesMessagingConfigurationsV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VerifyServicesMessagingConfigurationsV2Args | VerifyServicesMessagingConfigurationsV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VerifyServicesMessagingConfigurationsV2State | undefined;
            resourceInputs["country"] = state?.country;
            resourceInputs["messagingServiceSid"] = state?.messagingServiceSid;
            resourceInputs["serviceSid"] = state?.serviceSid;
        } else {
            const args = argsOrState as VerifyServicesMessagingConfigurationsV2Args | undefined;
            if (args?.country === undefined && !opts.urn) {
                throw new Error("Missing required property 'country'");
            }
            if (args?.messagingServiceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'messagingServiceSid'");
            }
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            resourceInputs["country"] = args?.country;
            resourceInputs["messagingServiceSid"] = args?.messagingServiceSid;
            resourceInputs["serviceSid"] = args?.serviceSid;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VerifyServicesMessagingConfigurationsV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VerifyServicesMessagingConfigurationsV2 resources.
 */
export interface VerifyServicesMessagingConfigurationsV2State {
    country?: pulumi.Input<string | undefined>;
    messagingServiceSid?: pulumi.Input<string | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VerifyServicesMessagingConfigurationsV2 resource.
 */
export interface VerifyServicesMessagingConfigurationsV2Args {
    country: pulumi.Input<string>;
    messagingServiceSid: pulumi.Input<string>;
    serviceSid: pulumi.Input<string>;
}
