// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class VerifyServicesEntitiesFactorsV2 extends pulumi.CustomResource {
    /**
     * Get an existing VerifyServicesEntitiesFactorsV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VerifyServicesEntitiesFactorsV2State, opts?: pulumi.CustomResourceOptions): VerifyServicesEntitiesFactorsV2 {
        return new VerifyServicesEntitiesFactorsV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/verifyServicesEntitiesFactorsV2:VerifyServicesEntitiesFactorsV2';

    /**
     * Returns true if the given object is an instance of VerifyServicesEntitiesFactorsV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VerifyServicesEntitiesFactorsV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VerifyServicesEntitiesFactorsV2.__pulumiType;
    }

    declare public readonly authPayload: pulumi.Output<string>;
    declare public readonly bindingAlg: pulumi.Output<string>;
    declare public readonly bindingPublicKey: pulumi.Output<string>;
    declare public readonly bindingSecret: pulumi.Output<string>;
    declare public readonly configAlg: pulumi.Output<string>;
    declare public readonly configAppId: pulumi.Output<string>;
    declare public readonly configCodeLength: pulumi.Output<number>;
    declare public readonly configNotificationPlatform: pulumi.Output<string>;
    declare public readonly configNotificationToken: pulumi.Output<string>;
    declare public readonly configSdkVersion: pulumi.Output<string>;
    declare public readonly configSkew: pulumi.Output<number>;
    declare public readonly configTimeStep: pulumi.Output<number>;
    declare public readonly factorType: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly identity: pulumi.Output<string>;
    declare public readonly metadata: pulumi.Output<string>;
    declare public readonly serviceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a VerifyServicesEntitiesFactorsV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VerifyServicesEntitiesFactorsV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VerifyServicesEntitiesFactorsV2Args | VerifyServicesEntitiesFactorsV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VerifyServicesEntitiesFactorsV2State | undefined;
            resourceInputs["authPayload"] = state?.authPayload;
            resourceInputs["bindingAlg"] = state?.bindingAlg;
            resourceInputs["bindingPublicKey"] = state?.bindingPublicKey;
            resourceInputs["bindingSecret"] = state?.bindingSecret;
            resourceInputs["configAlg"] = state?.configAlg;
            resourceInputs["configAppId"] = state?.configAppId;
            resourceInputs["configCodeLength"] = state?.configCodeLength;
            resourceInputs["configNotificationPlatform"] = state?.configNotificationPlatform;
            resourceInputs["configNotificationToken"] = state?.configNotificationToken;
            resourceInputs["configSdkVersion"] = state?.configSdkVersion;
            resourceInputs["configSkew"] = state?.configSkew;
            resourceInputs["configTimeStep"] = state?.configTimeStep;
            resourceInputs["factorType"] = state?.factorType;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["identity"] = state?.identity;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as VerifyServicesEntitiesFactorsV2Args | undefined;
            if (args?.factorType === undefined && !opts.urn) {
                throw new Error("Missing required property 'factorType'");
            }
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            if (args?.identity === undefined && !opts.urn) {
                throw new Error("Missing required property 'identity'");
            }
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            resourceInputs["authPayload"] = args?.authPayload;
            resourceInputs["bindingAlg"] = args?.bindingAlg;
            resourceInputs["bindingPublicKey"] = args?.bindingPublicKey;
            resourceInputs["bindingSecret"] = args?.bindingSecret;
            resourceInputs["configAlg"] = args?.configAlg;
            resourceInputs["configAppId"] = args?.configAppId;
            resourceInputs["configCodeLength"] = args?.configCodeLength;
            resourceInputs["configNotificationPlatform"] = args?.configNotificationPlatform;
            resourceInputs["configNotificationToken"] = args?.configNotificationToken;
            resourceInputs["configSdkVersion"] = args?.configSdkVersion;
            resourceInputs["configSkew"] = args?.configSkew;
            resourceInputs["configTimeStep"] = args?.configTimeStep;
            resourceInputs["factorType"] = args?.factorType;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["identity"] = args?.identity;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VerifyServicesEntitiesFactorsV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VerifyServicesEntitiesFactorsV2 resources.
 */
export interface VerifyServicesEntitiesFactorsV2State {
    authPayload?: pulumi.Input<string | undefined>;
    bindingAlg?: pulumi.Input<string | undefined>;
    bindingPublicKey?: pulumi.Input<string | undefined>;
    bindingSecret?: pulumi.Input<string | undefined>;
    configAlg?: pulumi.Input<string | undefined>;
    configAppId?: pulumi.Input<string | undefined>;
    configCodeLength?: pulumi.Input<number | undefined>;
    configNotificationPlatform?: pulumi.Input<string | undefined>;
    configNotificationToken?: pulumi.Input<string | undefined>;
    configSdkVersion?: pulumi.Input<string | undefined>;
    configSkew?: pulumi.Input<number | undefined>;
    configTimeStep?: pulumi.Input<number | undefined>;
    factorType?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    identity?: pulumi.Input<string | undefined>;
    metadata?: pulumi.Input<string | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VerifyServicesEntitiesFactorsV2 resource.
 */
export interface VerifyServicesEntitiesFactorsV2Args {
    authPayload?: pulumi.Input<string | undefined>;
    bindingAlg?: pulumi.Input<string | undefined>;
    bindingPublicKey?: pulumi.Input<string | undefined>;
    bindingSecret?: pulumi.Input<string | undefined>;
    configAlg?: pulumi.Input<string | undefined>;
    configAppId?: pulumi.Input<string | undefined>;
    configCodeLength?: pulumi.Input<number | undefined>;
    configNotificationPlatform?: pulumi.Input<string | undefined>;
    configNotificationToken?: pulumi.Input<string | undefined>;
    configSdkVersion?: pulumi.Input<string | undefined>;
    configSkew?: pulumi.Input<number | undefined>;
    configTimeStep?: pulumi.Input<number | undefined>;
    factorType: pulumi.Input<string>;
    friendlyName: pulumi.Input<string>;
    identity: pulumi.Input<string>;
    metadata?: pulumi.Input<string | undefined>;
    serviceSid: pulumi.Input<string>;
}
