// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class VerifyServicesEntitiesV2 extends pulumi.CustomResource {
    /**
     * Get an existing VerifyServicesEntitiesV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VerifyServicesEntitiesV2State, opts?: pulumi.CustomResourceOptions): VerifyServicesEntitiesV2 {
        return new VerifyServicesEntitiesV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/verifyServicesEntitiesV2:VerifyServicesEntitiesV2';

    /**
     * Returns true if the given object is an instance of VerifyServicesEntitiesV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VerifyServicesEntitiesV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VerifyServicesEntitiesV2.__pulumiType;
    }

    declare public readonly identity: pulumi.Output<string>;
    declare public readonly serviceSid: pulumi.Output<string>;

    /**
     * Create a VerifyServicesEntitiesV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VerifyServicesEntitiesV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VerifyServicesEntitiesV2Args | VerifyServicesEntitiesV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VerifyServicesEntitiesV2State | undefined;
            resourceInputs["identity"] = state?.identity;
            resourceInputs["serviceSid"] = state?.serviceSid;
        } else {
            const args = argsOrState as VerifyServicesEntitiesV2Args | undefined;
            if (args?.identity === undefined && !opts.urn) {
                throw new Error("Missing required property 'identity'");
            }
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            resourceInputs["identity"] = args?.identity;
            resourceInputs["serviceSid"] = args?.serviceSid;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VerifyServicesEntitiesV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VerifyServicesEntitiesV2 resources.
 */
export interface VerifyServicesEntitiesV2State {
    identity?: pulumi.Input<string | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VerifyServicesEntitiesV2 resource.
 */
export interface VerifyServicesEntitiesV2Args {
    identity: pulumi.Input<string>;
    serviceSid: pulumi.Input<string>;
}
