// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class VerifyServicesV2 extends pulumi.CustomResource {
    /**
     * Get an existing VerifyServicesV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VerifyServicesV2State, opts?: pulumi.CustomResourceOptions): VerifyServicesV2 {
        return new VerifyServicesV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/verifyServicesV2:VerifyServicesV2';

    /**
     * Returns true if the given object is an instance of VerifyServicesV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VerifyServicesV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VerifyServicesV2.__pulumiType;
    }

    declare public readonly codeLength: pulumi.Output<number>;
    declare public readonly customCodeEnabled: pulumi.Output<boolean>;
    declare public readonly defaultTemplateSid: pulumi.Output<string>;
    declare public readonly doNotShareWarningEnabled: pulumi.Output<boolean>;
    declare public readonly dtmfInputRequired: pulumi.Output<boolean>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly lookupEnabled: pulumi.Output<boolean>;
    declare public readonly psd2Enabled: pulumi.Output<boolean>;
    declare public readonly pushApnCredentialSid: pulumi.Output<string>;
    declare public readonly pushFcmCredentialSid: pulumi.Output<string>;
    declare public readonly pushIncludeDate: pulumi.Output<boolean>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly skipSmsToLandlines: pulumi.Output<boolean>;
    declare public readonly totpCodeLength: pulumi.Output<number>;
    declare public readonly totpIssuer: pulumi.Output<string>;
    declare public readonly totpSkew: pulumi.Output<number>;
    declare public readonly totpTimeStep: pulumi.Output<number>;
    declare public readonly ttsName: pulumi.Output<string>;
    declare public readonly verifyEventSubscriptionEnabled: pulumi.Output<boolean>;
    declare public readonly whatsappFrom: pulumi.Output<string>;
    declare public readonly whatsappMsgServiceSid: pulumi.Output<string>;

    /**
     * Create a VerifyServicesV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VerifyServicesV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VerifyServicesV2Args | VerifyServicesV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VerifyServicesV2State | undefined;
            resourceInputs["codeLength"] = state?.codeLength;
            resourceInputs["customCodeEnabled"] = state?.customCodeEnabled;
            resourceInputs["defaultTemplateSid"] = state?.defaultTemplateSid;
            resourceInputs["doNotShareWarningEnabled"] = state?.doNotShareWarningEnabled;
            resourceInputs["dtmfInputRequired"] = state?.dtmfInputRequired;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["lookupEnabled"] = state?.lookupEnabled;
            resourceInputs["psd2Enabled"] = state?.psd2Enabled;
            resourceInputs["pushApnCredentialSid"] = state?.pushApnCredentialSid;
            resourceInputs["pushFcmCredentialSid"] = state?.pushFcmCredentialSid;
            resourceInputs["pushIncludeDate"] = state?.pushIncludeDate;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["skipSmsToLandlines"] = state?.skipSmsToLandlines;
            resourceInputs["totpCodeLength"] = state?.totpCodeLength;
            resourceInputs["totpIssuer"] = state?.totpIssuer;
            resourceInputs["totpSkew"] = state?.totpSkew;
            resourceInputs["totpTimeStep"] = state?.totpTimeStep;
            resourceInputs["ttsName"] = state?.ttsName;
            resourceInputs["verifyEventSubscriptionEnabled"] = state?.verifyEventSubscriptionEnabled;
            resourceInputs["whatsappFrom"] = state?.whatsappFrom;
            resourceInputs["whatsappMsgServiceSid"] = state?.whatsappMsgServiceSid;
        } else {
            const args = argsOrState as VerifyServicesV2Args | undefined;
            if (args?.friendlyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'friendlyName'");
            }
            resourceInputs["codeLength"] = args?.codeLength;
            resourceInputs["customCodeEnabled"] = args?.customCodeEnabled;
            resourceInputs["defaultTemplateSid"] = args?.defaultTemplateSid;
            resourceInputs["doNotShareWarningEnabled"] = args?.doNotShareWarningEnabled;
            resourceInputs["dtmfInputRequired"] = args?.dtmfInputRequired;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["lookupEnabled"] = args?.lookupEnabled;
            resourceInputs["psd2Enabled"] = args?.psd2Enabled;
            resourceInputs["pushApnCredentialSid"] = args?.pushApnCredentialSid;
            resourceInputs["pushFcmCredentialSid"] = args?.pushFcmCredentialSid;
            resourceInputs["pushIncludeDate"] = args?.pushIncludeDate;
            resourceInputs["skipSmsToLandlines"] = args?.skipSmsToLandlines;
            resourceInputs["totpCodeLength"] = args?.totpCodeLength;
            resourceInputs["totpIssuer"] = args?.totpIssuer;
            resourceInputs["totpSkew"] = args?.totpSkew;
            resourceInputs["totpTimeStep"] = args?.totpTimeStep;
            resourceInputs["ttsName"] = args?.ttsName;
            resourceInputs["verifyEventSubscriptionEnabled"] = args?.verifyEventSubscriptionEnabled;
            resourceInputs["whatsappFrom"] = args?.whatsappFrom;
            resourceInputs["whatsappMsgServiceSid"] = args?.whatsappMsgServiceSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VerifyServicesV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VerifyServicesV2 resources.
 */
export interface VerifyServicesV2State {
    codeLength?: pulumi.Input<number | undefined>;
    customCodeEnabled?: pulumi.Input<boolean | undefined>;
    defaultTemplateSid?: pulumi.Input<string | undefined>;
    doNotShareWarningEnabled?: pulumi.Input<boolean | undefined>;
    dtmfInputRequired?: pulumi.Input<boolean | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    lookupEnabled?: pulumi.Input<boolean | undefined>;
    psd2Enabled?: pulumi.Input<boolean | undefined>;
    pushApnCredentialSid?: pulumi.Input<string | undefined>;
    pushFcmCredentialSid?: pulumi.Input<string | undefined>;
    pushIncludeDate?: pulumi.Input<boolean | undefined>;
    sid?: pulumi.Input<string | undefined>;
    skipSmsToLandlines?: pulumi.Input<boolean | undefined>;
    totpCodeLength?: pulumi.Input<number | undefined>;
    totpIssuer?: pulumi.Input<string | undefined>;
    totpSkew?: pulumi.Input<number | undefined>;
    totpTimeStep?: pulumi.Input<number | undefined>;
    ttsName?: pulumi.Input<string | undefined>;
    verifyEventSubscriptionEnabled?: pulumi.Input<boolean | undefined>;
    whatsappFrom?: pulumi.Input<string | undefined>;
    whatsappMsgServiceSid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VerifyServicesV2 resource.
 */
export interface VerifyServicesV2Args {
    codeLength?: pulumi.Input<number | undefined>;
    customCodeEnabled?: pulumi.Input<boolean | undefined>;
    defaultTemplateSid?: pulumi.Input<string | undefined>;
    doNotShareWarningEnabled?: pulumi.Input<boolean | undefined>;
    dtmfInputRequired?: pulumi.Input<boolean | undefined>;
    friendlyName: pulumi.Input<string>;
    lookupEnabled?: pulumi.Input<boolean | undefined>;
    psd2Enabled?: pulumi.Input<boolean | undefined>;
    pushApnCredentialSid?: pulumi.Input<string | undefined>;
    pushFcmCredentialSid?: pulumi.Input<string | undefined>;
    pushIncludeDate?: pulumi.Input<boolean | undefined>;
    skipSmsToLandlines?: pulumi.Input<boolean | undefined>;
    totpCodeLength?: pulumi.Input<number | undefined>;
    totpIssuer?: pulumi.Input<string | undefined>;
    totpSkew?: pulumi.Input<number | undefined>;
    totpTimeStep?: pulumi.Input<number | undefined>;
    ttsName?: pulumi.Input<string | undefined>;
    verifyEventSubscriptionEnabled?: pulumi.Input<boolean | undefined>;
    whatsappFrom?: pulumi.Input<string | undefined>;
    whatsappMsgServiceSid?: pulumi.Input<string | undefined>;
}
