// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class VerifyServicesRateLimitsV2 extends pulumi.CustomResource {
    /**
     * Get an existing VerifyServicesRateLimitsV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VerifyServicesRateLimitsV2State, opts?: pulumi.CustomResourceOptions): VerifyServicesRateLimitsV2 {
        return new VerifyServicesRateLimitsV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/verifyServicesRateLimitsV2:VerifyServicesRateLimitsV2';

    /**
     * Returns true if the given object is an instance of VerifyServicesRateLimitsV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VerifyServicesRateLimitsV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VerifyServicesRateLimitsV2.__pulumiType;
    }

    declare public readonly description: pulumi.Output<string>;
    declare public readonly serviceSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly uniqueName: pulumi.Output<string>;

    /**
     * Create a VerifyServicesRateLimitsV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VerifyServicesRateLimitsV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VerifyServicesRateLimitsV2Args | VerifyServicesRateLimitsV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VerifyServicesRateLimitsV2State | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["serviceSid"] = state?.serviceSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["uniqueName"] = state?.uniqueName;
        } else {
            const args = argsOrState as VerifyServicesRateLimitsV2Args | undefined;
            if (args?.serviceSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceSid'");
            }
            if (args?.uniqueName === undefined && !opts.urn) {
                throw new Error("Missing required property 'uniqueName'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["serviceSid"] = args?.serviceSid;
            resourceInputs["uniqueName"] = args?.uniqueName;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VerifyServicesRateLimitsV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VerifyServicesRateLimitsV2 resources.
 */
export interface VerifyServicesRateLimitsV2State {
    description?: pulumi.Input<string | undefined>;
    serviceSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    uniqueName?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VerifyServicesRateLimitsV2 resource.
 */
export interface VerifyServicesRateLimitsV2Args {
    description?: pulumi.Input<string | undefined>;
    serviceSid: pulumi.Input<string>;
    uniqueName: pulumi.Input<string>;
}
