// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class VideoCompositionsV1 extends pulumi.CustomResource {
    /**
     * Get an existing VideoCompositionsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VideoCompositionsV1State, opts?: pulumi.CustomResourceOptions): VideoCompositionsV1 {
        return new VideoCompositionsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/videoCompositionsV1:VideoCompositionsV1';

    /**
     * Returns true if the given object is an instance of VideoCompositionsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VideoCompositionsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VideoCompositionsV1.__pulumiType;
    }

    declare public readonly audioSources: pulumi.Output<string[]>;
    declare public readonly audioSourcesExcludeds: pulumi.Output<string[]>;
    declare public readonly format: pulumi.Output<string>;
    declare public readonly resolution: pulumi.Output<string>;
    declare public readonly roomSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly statusCallback: pulumi.Output<string>;
    declare public readonly statusCallbackMethod: pulumi.Output<string>;
    declare public readonly trim: pulumi.Output<boolean>;
    declare public readonly videoLayout: pulumi.Output<string>;

    /**
     * Create a VideoCompositionsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VideoCompositionsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VideoCompositionsV1Args | VideoCompositionsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VideoCompositionsV1State | undefined;
            resourceInputs["audioSources"] = state?.audioSources;
            resourceInputs["audioSourcesExcludeds"] = state?.audioSourcesExcludeds;
            resourceInputs["format"] = state?.format;
            resourceInputs["resolution"] = state?.resolution;
            resourceInputs["roomSid"] = state?.roomSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["statusCallback"] = state?.statusCallback;
            resourceInputs["statusCallbackMethod"] = state?.statusCallbackMethod;
            resourceInputs["trim"] = state?.trim;
            resourceInputs["videoLayout"] = state?.videoLayout;
        } else {
            const args = argsOrState as VideoCompositionsV1Args | undefined;
            if (args?.roomSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'roomSid'");
            }
            resourceInputs["audioSources"] = args?.audioSources;
            resourceInputs["audioSourcesExcludeds"] = args?.audioSourcesExcludeds;
            resourceInputs["format"] = args?.format;
            resourceInputs["resolution"] = args?.resolution;
            resourceInputs["roomSid"] = args?.roomSid;
            resourceInputs["statusCallback"] = args?.statusCallback;
            resourceInputs["statusCallbackMethod"] = args?.statusCallbackMethod;
            resourceInputs["trim"] = args?.trim;
            resourceInputs["videoLayout"] = args?.videoLayout;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VideoCompositionsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VideoCompositionsV1 resources.
 */
export interface VideoCompositionsV1State {
    audioSources?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    audioSourcesExcludeds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    format?: pulumi.Input<string | undefined>;
    resolution?: pulumi.Input<string | undefined>;
    roomSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    statusCallback?: pulumi.Input<string | undefined>;
    statusCallbackMethod?: pulumi.Input<string | undefined>;
    trim?: pulumi.Input<boolean | undefined>;
    videoLayout?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VideoCompositionsV1 resource.
 */
export interface VideoCompositionsV1Args {
    audioSources?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    audioSourcesExcludeds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    format?: pulumi.Input<string | undefined>;
    resolution?: pulumi.Input<string | undefined>;
    roomSid: pulumi.Input<string>;
    statusCallback?: pulumi.Input<string | undefined>;
    statusCallbackMethod?: pulumi.Input<string | undefined>;
    trim?: pulumi.Input<boolean | undefined>;
    videoLayout?: pulumi.Input<string | undefined>;
}
