// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class VoiceConnectionPoliciesTargetsV1 extends pulumi.CustomResource {
    /**
     * Get an existing VoiceConnectionPoliciesTargetsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VoiceConnectionPoliciesTargetsV1State, opts?: pulumi.CustomResourceOptions): VoiceConnectionPoliciesTargetsV1 {
        return new VoiceConnectionPoliciesTargetsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/voiceConnectionPoliciesTargetsV1:VoiceConnectionPoliciesTargetsV1';

    /**
     * Returns true if the given object is an instance of VoiceConnectionPoliciesTargetsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VoiceConnectionPoliciesTargetsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VoiceConnectionPoliciesTargetsV1.__pulumiType;
    }

    declare public readonly connectionPolicySid: pulumi.Output<string>;
    declare public readonly enabled: pulumi.Output<boolean>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly priority: pulumi.Output<number>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly target: pulumi.Output<string>;
    declare public readonly weight: pulumi.Output<number>;

    /**
     * Create a VoiceConnectionPoliciesTargetsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VoiceConnectionPoliciesTargetsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VoiceConnectionPoliciesTargetsV1Args | VoiceConnectionPoliciesTargetsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VoiceConnectionPoliciesTargetsV1State | undefined;
            resourceInputs["connectionPolicySid"] = state?.connectionPolicySid;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["priority"] = state?.priority;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["target"] = state?.target;
            resourceInputs["weight"] = state?.weight;
        } else {
            const args = argsOrState as VoiceConnectionPoliciesTargetsV1Args | undefined;
            if (args?.connectionPolicySid === undefined && !opts.urn) {
                throw new Error("Missing required property 'connectionPolicySid'");
            }
            if (args?.target === undefined && !opts.urn) {
                throw new Error("Missing required property 'target'");
            }
            resourceInputs["connectionPolicySid"] = args?.connectionPolicySid;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["priority"] = args?.priority;
            resourceInputs["target"] = args?.target;
            resourceInputs["weight"] = args?.weight;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VoiceConnectionPoliciesTargetsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VoiceConnectionPoliciesTargetsV1 resources.
 */
export interface VoiceConnectionPoliciesTargetsV1State {
    connectionPolicySid?: pulumi.Input<string | undefined>;
    enabled?: pulumi.Input<boolean | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    priority?: pulumi.Input<number | undefined>;
    sid?: pulumi.Input<string | undefined>;
    target?: pulumi.Input<string | undefined>;
    weight?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a VoiceConnectionPoliciesTargetsV1 resource.
 */
export interface VoiceConnectionPoliciesTargetsV1Args {
    connectionPolicySid: pulumi.Input<string>;
    enabled?: pulumi.Input<boolean | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    priority?: pulumi.Input<number | undefined>;
    target: pulumi.Input<string>;
    weight?: pulumi.Input<number | undefined>;
}
