// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class VoiceSourceIpMappingsV1 extends pulumi.CustomResource {
    /**
     * Get an existing VoiceSourceIpMappingsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VoiceSourceIpMappingsV1State, opts?: pulumi.CustomResourceOptions): VoiceSourceIpMappingsV1 {
        return new VoiceSourceIpMappingsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/voiceSourceIpMappingsV1:VoiceSourceIpMappingsV1';

    /**
     * Returns true if the given object is an instance of VoiceSourceIpMappingsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VoiceSourceIpMappingsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VoiceSourceIpMappingsV1.__pulumiType;
    }

    declare public readonly ipRecordSid: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly sipDomainSid: pulumi.Output<string>;

    /**
     * Create a VoiceSourceIpMappingsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VoiceSourceIpMappingsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VoiceSourceIpMappingsV1Args | VoiceSourceIpMappingsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VoiceSourceIpMappingsV1State | undefined;
            resourceInputs["ipRecordSid"] = state?.ipRecordSid;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["sipDomainSid"] = state?.sipDomainSid;
        } else {
            const args = argsOrState as VoiceSourceIpMappingsV1Args | undefined;
            if (args?.ipRecordSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'ipRecordSid'");
            }
            if (args?.sipDomainSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'sipDomainSid'");
            }
            resourceInputs["ipRecordSid"] = args?.ipRecordSid;
            resourceInputs["sipDomainSid"] = args?.sipDomainSid;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VoiceSourceIpMappingsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VoiceSourceIpMappingsV1 resources.
 */
export interface VoiceSourceIpMappingsV1State {
    ipRecordSid?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
    sipDomainSid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VoiceSourceIpMappingsV1 resource.
 */
export interface VoiceSourceIpMappingsV1Args {
    ipRecordSid: pulumi.Input<string>;
    sipDomainSid: pulumi.Input<string>;
}
