// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class VoiceIpRecordsV1 extends pulumi.CustomResource {
    /**
     * Get an existing VoiceIpRecordsV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VoiceIpRecordsV1State, opts?: pulumi.CustomResourceOptions): VoiceIpRecordsV1 {
        return new VoiceIpRecordsV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/voiceIpRecordsV1:VoiceIpRecordsV1';

    /**
     * Returns true if the given object is an instance of VoiceIpRecordsV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VoiceIpRecordsV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VoiceIpRecordsV1.__pulumiType;
    }

    declare public readonly cidrPrefixLength: pulumi.Output<number>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly ipAddress: pulumi.Output<string>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;

    /**
     * Create a VoiceIpRecordsV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VoiceIpRecordsV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VoiceIpRecordsV1Args | VoiceIpRecordsV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VoiceIpRecordsV1State | undefined;
            resourceInputs["cidrPrefixLength"] = state?.cidrPrefixLength;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["ipAddress"] = state?.ipAddress;
            resourceInputs["sid"] = state?.sid;
        } else {
            const args = argsOrState as VoiceIpRecordsV1Args | undefined;
            if (args?.ipAddress === undefined && !opts.urn) {
                throw new Error("Missing required property 'ipAddress'");
            }
            resourceInputs["cidrPrefixLength"] = args?.cidrPrefixLength;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["ipAddress"] = args?.ipAddress;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VoiceIpRecordsV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VoiceIpRecordsV1 resources.
 */
export interface VoiceIpRecordsV1State {
    cidrPrefixLength?: pulumi.Input<number | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    ipAddress?: pulumi.Input<string | undefined>;
    sid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VoiceIpRecordsV1 resource.
 */
export interface VoiceIpRecordsV1Args {
    cidrPrefixLength?: pulumi.Input<number | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    ipAddress: pulumi.Input<string>;
}
