// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class WirelessRatePlansV1 extends pulumi.CustomResource {
    /**
     * Get an existing WirelessRatePlansV1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WirelessRatePlansV1State, opts?: pulumi.CustomResourceOptions): WirelessRatePlansV1 {
        return new WirelessRatePlansV1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'twilio:index/wirelessRatePlansV1:WirelessRatePlansV1';

    /**
     * Returns true if the given object is an instance of WirelessRatePlansV1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WirelessRatePlansV1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WirelessRatePlansV1.__pulumiType;
    }

    declare public readonly dataEnabled: pulumi.Output<boolean>;
    declare public readonly dataLimit: pulumi.Output<number>;
    declare public readonly dataMetering: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string>;
    declare public readonly internationalRoamingDataLimit: pulumi.Output<number>;
    declare public readonly internationalRoamings: pulumi.Output<string[]>;
    declare public readonly messagingEnabled: pulumi.Output<boolean>;
    declare public readonly nationalRoamingDataLimit: pulumi.Output<number>;
    declare public readonly nationalRoamingEnabled: pulumi.Output<boolean>;
    declare public /*out*/ readonly sid: pulumi.Output<string>;
    declare public readonly uniqueName: pulumi.Output<string>;
    declare public readonly voiceEnabled: pulumi.Output<boolean>;

    /**
     * Create a WirelessRatePlansV1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: WirelessRatePlansV1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WirelessRatePlansV1Args | WirelessRatePlansV1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WirelessRatePlansV1State | undefined;
            resourceInputs["dataEnabled"] = state?.dataEnabled;
            resourceInputs["dataLimit"] = state?.dataLimit;
            resourceInputs["dataMetering"] = state?.dataMetering;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["internationalRoamingDataLimit"] = state?.internationalRoamingDataLimit;
            resourceInputs["internationalRoamings"] = state?.internationalRoamings;
            resourceInputs["messagingEnabled"] = state?.messagingEnabled;
            resourceInputs["nationalRoamingDataLimit"] = state?.nationalRoamingDataLimit;
            resourceInputs["nationalRoamingEnabled"] = state?.nationalRoamingEnabled;
            resourceInputs["sid"] = state?.sid;
            resourceInputs["uniqueName"] = state?.uniqueName;
            resourceInputs["voiceEnabled"] = state?.voiceEnabled;
        } else {
            const args = argsOrState as WirelessRatePlansV1Args | undefined;
            resourceInputs["dataEnabled"] = args?.dataEnabled;
            resourceInputs["dataLimit"] = args?.dataLimit;
            resourceInputs["dataMetering"] = args?.dataMetering;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["internationalRoamingDataLimit"] = args?.internationalRoamingDataLimit;
            resourceInputs["internationalRoamings"] = args?.internationalRoamings;
            resourceInputs["messagingEnabled"] = args?.messagingEnabled;
            resourceInputs["nationalRoamingDataLimit"] = args?.nationalRoamingDataLimit;
            resourceInputs["nationalRoamingEnabled"] = args?.nationalRoamingEnabled;
            resourceInputs["uniqueName"] = args?.uniqueName;
            resourceInputs["voiceEnabled"] = args?.voiceEnabled;
            resourceInputs["sid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WirelessRatePlansV1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering WirelessRatePlansV1 resources.
 */
export interface WirelessRatePlansV1State {
    dataEnabled?: pulumi.Input<boolean | undefined>;
    dataLimit?: pulumi.Input<number | undefined>;
    dataMetering?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    internationalRoamingDataLimit?: pulumi.Input<number | undefined>;
    internationalRoamings?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    messagingEnabled?: pulumi.Input<boolean | undefined>;
    nationalRoamingDataLimit?: pulumi.Input<number | undefined>;
    nationalRoamingEnabled?: pulumi.Input<boolean | undefined>;
    sid?: pulumi.Input<string | undefined>;
    uniqueName?: pulumi.Input<string | undefined>;
    voiceEnabled?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a WirelessRatePlansV1 resource.
 */
export interface WirelessRatePlansV1Args {
    dataEnabled?: pulumi.Input<boolean | undefined>;
    dataLimit?: pulumi.Input<number | undefined>;
    dataMetering?: pulumi.Input<string | undefined>;
    friendlyName?: pulumi.Input<string | undefined>;
    internationalRoamingDataLimit?: pulumi.Input<number | undefined>;
    internationalRoamings?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    messagingEnabled?: pulumi.Input<boolean | undefined>;
    nationalRoamingDataLimit?: pulumi.Input<number | undefined>;
    nationalRoamingEnabled?: pulumi.Input<boolean | undefined>;
    uniqueName?: pulumi.Input<string | undefined>;
    voiceEnabled?: pulumi.Input<boolean | undefined>;
}
